ARG REPOSITORY
FROM ${REPOSITORY}/silveo-geocube-base:latest AS builder
WORKDIR /build
ENV GOTOOLCHAIN=auto
COPY go.* /build/
COPY vendor vendor
COPY internal internal
COPY interface interface
COPY cmd cmd
COPY cmd/server server
RUN cd server && go build -ldflags="-s -w" .

FROM alpine:3.21
RUN apk update && \
    apk upgrade && \
    apk add \
    make \
    ca-certificates \
    libcurl \
    libgcc \
    gcompat \
    proj \
    geos \
    libjpeg-turbo \
    libstdc++ \
    libwebp \
    sqlite-libs \
    tiff \
    libpng-dev \
    zstd-libs && \
    ldconfig /usr/local/lib

COPY --from=builder /usr/local/lib /usr/local/lib
COPY --from=builder /usr/local/share /usr/local/share
COPY --from=builder /build/server/server /
