// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/admin.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request to remove from the database all the pending entities (entities that are not linked to any dataset)
type TidyDBRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Simulate          bool                   `protobuf:"varint,1,opt,name=Simulate,proto3" json:"Simulate,omitempty"`                   // If true, a simulation is done, nothing is actually deleted
	PendingAOIs       bool                   `protobuf:"varint,2,opt,name=PendingAOIs,proto3" json:"PendingAOIs,omitempty"`             // Remove AOIs that are not linked to any Records
	PendingRecords    bool                   `protobuf:"varint,3,opt,name=PendingRecords,proto3" json:"PendingRecords,omitempty"`       // Remove Records that do not reference any Datasets
	PendingVariables  bool                   `protobuf:"varint,4,opt,name=PendingVariables,proto3" json:"PendingVariables,omitempty"`   // Remove Variables that have not any instances
	PendingInstances  bool                   `protobuf:"varint,5,opt,name=PendingInstances,proto3" json:"PendingInstances,omitempty"`   // Remove Instances that do not reference any Datasets
	PendingContainers bool                   `protobuf:"varint,6,opt,name=PendingContainers,proto3" json:"PendingContainers,omitempty"` // Remove Containers that do not contain any Datasets
	PendingParams     bool                   `protobuf:"varint,7,opt,name=PendingParams,proto3" json:"PendingParams,omitempty"`         // Remove ConsolidationParams that are not linked to any Variable or Job
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TidyDBRequest) Reset() {
	*x = TidyDBRequest{}
	mi := &file_pb_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TidyDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidyDBRequest) ProtoMessage() {}

func (x *TidyDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidyDBRequest.ProtoReflect.Descriptor instead.
func (*TidyDBRequest) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{0}
}

func (x *TidyDBRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

func (x *TidyDBRequest) GetPendingAOIs() bool {
	if x != nil {
		return x.PendingAOIs
	}
	return false
}

func (x *TidyDBRequest) GetPendingRecords() bool {
	if x != nil {
		return x.PendingRecords
	}
	return false
}

func (x *TidyDBRequest) GetPendingVariables() bool {
	if x != nil {
		return x.PendingVariables
	}
	return false
}

func (x *TidyDBRequest) GetPendingInstances() bool {
	if x != nil {
		return x.PendingInstances
	}
	return false
}

func (x *TidyDBRequest) GetPendingContainers() bool {
	if x != nil {
		return x.PendingContainers
	}
	return false
}

func (x *TidyDBRequest) GetPendingParams() bool {
	if x != nil {
		return x.PendingParams
	}
	return false
}

// *
// Return the number of entities that were deleted (or should have been deleted if Simulate=True)
type TidyDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NbAOIs        int64                  `protobuf:"varint,1,opt,name=NbAOIs,proto3" json:"NbAOIs,omitempty"`
	NbRecords     int64                  `protobuf:"varint,2,opt,name=NbRecords,proto3" json:"NbRecords,omitempty"`
	NbVariables   int64                  `protobuf:"varint,3,opt,name=NbVariables,proto3" json:"NbVariables,omitempty"`
	NbInstances   int64                  `protobuf:"varint,4,opt,name=NbInstances,proto3" json:"NbInstances,omitempty"`
	NbContainers  int64                  `protobuf:"varint,5,opt,name=NbContainers,proto3" json:"NbContainers,omitempty"`
	NbParams      int64                  `protobuf:"varint,6,opt,name=NbParams,proto3" json:"NbParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TidyDBResponse) Reset() {
	*x = TidyDBResponse{}
	mi := &file_pb_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TidyDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidyDBResponse) ProtoMessage() {}

func (x *TidyDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidyDBResponse.ProtoReflect.Descriptor instead.
func (*TidyDBResponse) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{1}
}

func (x *TidyDBResponse) GetNbAOIs() int64 {
	if x != nil {
		return x.NbAOIs
	}
	return 0
}

func (x *TidyDBResponse) GetNbRecords() int64 {
	if x != nil {
		return x.NbRecords
	}
	return 0
}

func (x *TidyDBResponse) GetNbVariables() int64 {
	if x != nil {
		return x.NbVariables
	}
	return 0
}

func (x *TidyDBResponse) GetNbInstances() int64 {
	if x != nil {
		return x.NbInstances
	}
	return 0
}

func (x *TidyDBResponse) GetNbContainers() int64 {
	if x != nil {
		return x.NbContainers
	}
	return 0
}

func (x *TidyDBResponse) GetNbParams() int64 {
	if x != nil {
		return x.NbParams
	}
	return 0
}

// *
// Update fields of datasets that can be tricky
type UpdateDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulate      bool                   `protobuf:"varint,1,opt,name=simulate,proto3" json:"simulate,omitempty"`                                 // If true, a simulation is done, nothing is actually updated
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`            // Instance id that references the datasets to be updated
	RecordIds     []string               `protobuf:"bytes,3,rep,name=record_ids,json=recordIds,proto3" json:"record_ids,omitempty"`               // Record ids that reference the datasets to be updated
	Dformat       *DataFormat            `protobuf:"bytes,8,opt,name=dformat,proto3" json:"dformat,omitempty"`                                    // Internal data format (DType can be Undefined)
	RealMinValue  float64                `protobuf:"fixed64,9,opt,name=real_min_value,json=realMinValue,proto3" json:"real_min_value,omitempty"`  // Real min value (dformat.min_value maps to real_min_value)
	RealMaxValue  float64                `protobuf:"fixed64,10,opt,name=real_max_value,json=realMaxValue,proto3" json:"real_max_value,omitempty"` // Real max value (dformat.max_value maps to real_max_value)
	Exponent      float64                `protobuf:"fixed64,11,opt,name=exponent,proto3" json:"exponent,omitempty"`                               // 1: linear scaling (RealMax - RealMin) * pow( (Value - Min) / (Max - Min), Exponent) + RealMin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatasetsRequest) Reset() {
	*x = UpdateDatasetsRequest{}
	mi := &file_pb_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatasetsRequest) ProtoMessage() {}

func (x *UpdateDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatasetsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDatasetsRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

func (x *UpdateDatasetsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdateDatasetsRequest) GetRecordIds() []string {
	if x != nil {
		return x.RecordIds
	}
	return nil
}

func (x *UpdateDatasetsRequest) GetDformat() *DataFormat {
	if x != nil {
		return x.Dformat
	}
	return nil
}

func (x *UpdateDatasetsRequest) GetRealMinValue() float64 {
	if x != nil {
		return x.RealMinValue
	}
	return 0
}

func (x *UpdateDatasetsRequest) GetRealMaxValue() float64 {
	if x != nil {
		return x.RealMaxValue
	}
	return 0
}

func (x *UpdateDatasetsRequest) GetExponent() float64 {
	if x != nil {
		return x.Exponent
	}
	return 0
}

// *
// Return the number of modifications per kind of modification
type UpdateDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]int64       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatasetsResponse) Reset() {
	*x = UpdateDatasetsResponse{}
	mi := &file_pb_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatasetsResponse) ProtoMessage() {}

func (x *UpdateDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatasetsResponse.ProtoReflect.Descriptor instead.
func (*UpdateDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDatasetsResponse) GetResults() map[string]int64 {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_pb_admin_proto protoreflect.FileDescriptor

const file_pb_admin_proto_rawDesc = "" +
	"\n" +
	"\x0epb/admin.proto\x12\ageocube\x1a\x13pb/dataformat.proto\x1a\x13pb/operations.proto\"\xa1\x02\n" +
	"\rTidyDBRequest\x12\x1a\n" +
	"\bSimulate\x18\x01 \x01(\bR\bSimulate\x12 \n" +
	"\vPendingAOIs\x18\x02 \x01(\bR\vPendingAOIs\x12&\n" +
	"\x0ePendingRecords\x18\x03 \x01(\bR\x0ePendingRecords\x12*\n" +
	"\x10PendingVariables\x18\x04 \x01(\bR\x10PendingVariables\x12*\n" +
	"\x10PendingInstances\x18\x05 \x01(\bR\x10PendingInstances\x12,\n" +
	"\x11PendingContainers\x18\x06 \x01(\bR\x11PendingContainers\x12$\n" +
	"\rPendingParams\x18\a \x01(\bR\rPendingParams\"\xca\x01\n" +
	"\x0eTidyDBResponse\x12\x16\n" +
	"\x06NbAOIs\x18\x01 \x01(\x03R\x06NbAOIs\x12\x1c\n" +
	"\tNbRecords\x18\x02 \x01(\x03R\tNbRecords\x12 \n" +
	"\vNbVariables\x18\x03 \x01(\x03R\vNbVariables\x12 \n" +
	"\vNbInstances\x18\x04 \x01(\x03R\vNbInstances\x12\"\n" +
	"\fNbContainers\x18\x05 \x01(\x03R\fNbContainers\x12\x1a\n" +
	"\bNbParams\x18\x06 \x01(\x03R\bNbParams\"\x8a\x02\n" +
	"\x15UpdateDatasetsRequest\x12\x1a\n" +
	"\bsimulate\x18\x01 \x01(\bR\bsimulate\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"record_ids\x18\x03 \x03(\tR\trecordIds\x12-\n" +
	"\adformat\x18\b \x01(\v2\x13.geocube.DataFormatR\adformat\x12$\n" +
	"\x0ereal_min_value\x18\t \x01(\x01R\frealMinValue\x12$\n" +
	"\x0ereal_max_value\x18\n" +
	" \x01(\x01R\frealMaxValue\x12\x1a\n" +
	"\bexponent\x18\v \x01(\x01R\bexponent\"\x9c\x01\n" +
	"\x16UpdateDatasetsResponse\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.geocube.UpdateDatasetsResponse.ResultsEntryR\aresults\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xee\x01\n" +
	"\x05Admin\x12;\n" +
	"\x06TidyDB\x12\x16.geocube.TidyDBRequest\x1a\x17.geocube.TidyDBResponse\"\x00\x12S\n" +
	"\x0eUpdateDatasets\x12\x1e.geocube.UpdateDatasetsRequest\x1a\x1f.geocube.UpdateDatasetsResponse\"\x00\x12S\n" +
	"\x0eDeleteDatasets\x12\x1e.geocube.DeleteDatasetsRequest\x1a\x1f.geocube.DeleteDatasetsResponse\"\x00B\x0eZ\f./pb;geocubeb\x06proto3"

var (
	file_pb_admin_proto_rawDescOnce sync.Once
	file_pb_admin_proto_rawDescData []byte
)

func file_pb_admin_proto_rawDescGZIP() []byte {
	file_pb_admin_proto_rawDescOnce.Do(func() {
		file_pb_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_admin_proto_rawDesc), len(file_pb_admin_proto_rawDesc)))
	})
	return file_pb_admin_proto_rawDescData
}

var file_pb_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_admin_proto_goTypes = []any{
	(*TidyDBRequest)(nil),          // 0: geocube.TidyDBRequest
	(*TidyDBResponse)(nil),         // 1: geocube.TidyDBResponse
	(*UpdateDatasetsRequest)(nil),  // 2: geocube.UpdateDatasetsRequest
	(*UpdateDatasetsResponse)(nil), // 3: geocube.UpdateDatasetsResponse
	nil,                            // 4: geocube.UpdateDatasetsResponse.ResultsEntry
	(*DataFormat)(nil),             // 5: geocube.DataFormat
	(*DeleteDatasetsRequest)(nil),  // 6: geocube.DeleteDatasetsRequest
	(*DeleteDatasetsResponse)(nil), // 7: geocube.DeleteDatasetsResponse
}
var file_pb_admin_proto_depIdxs = []int32{
	5, // 0: geocube.UpdateDatasetsRequest.dformat:type_name -> geocube.DataFormat
	4, // 1: geocube.UpdateDatasetsResponse.results:type_name -> geocube.UpdateDatasetsResponse.ResultsEntry
	0, // 2: geocube.Admin.TidyDB:input_type -> geocube.TidyDBRequest
	2, // 3: geocube.Admin.UpdateDatasets:input_type -> geocube.UpdateDatasetsRequest
	6, // 4: geocube.Admin.DeleteDatasets:input_type -> geocube.DeleteDatasetsRequest
	1, // 5: geocube.Admin.TidyDB:output_type -> geocube.TidyDBResponse
	3, // 6: geocube.Admin.UpdateDatasets:output_type -> geocube.UpdateDatasetsResponse
	7, // 7: geocube.Admin.DeleteDatasets:output_type -> geocube.DeleteDatasetsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_admin_proto_init() }
func file_pb_admin_proto_init() {
	if File_pb_admin_proto != nil {
		return
	}
	file_pb_dataformat_proto_init()
	file_pb_operations_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_admin_proto_rawDesc), len(file_pb_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_admin_proto_goTypes,
		DependencyIndexes: file_pb_admin_proto_depIdxs,
		MessageInfos:      file_pb_admin_proto_msgTypes,
	}.Build()
	File_pb_admin_proto = out.File
	file_pb_admin_proto_goTypes = nil
	file_pb_admin_proto_depIdxs = nil
}
