// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/datasetMeta.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// DatasetMeta contains all the metadata on files and fileformats to download and generate a slice of a cube
type DatasetMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InternalsMeta []*InternalMeta        `protobuf:"bytes,3,rep,name=internalsMeta,proto3" json:"internalsMeta,omitempty"` // Information on the images composing the slice
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetMeta) Reset() {
	*x = DatasetMeta{}
	mi := &file_pb_datasetMeta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetMeta) ProtoMessage() {}

func (x *DatasetMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_datasetMeta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetMeta.ProtoReflect.Descriptor instead.
func (*DatasetMeta) Descriptor() ([]byte, []int) {
	return file_pb_datasetMeta_proto_rawDescGZIP(), []int{0}
}

func (x *DatasetMeta) GetInternalsMeta() []*InternalMeta {
	if x != nil {
		return x.InternalsMeta
	}
	return nil
}

// *
// InternalMeta contains all the metadata on a file to download it and to map its internal values to the external range.
type InternalMeta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContainerUri    string                 `protobuf:"bytes,1,opt,name=container_uri,json=containerUri,proto3" json:"container_uri,omitempty"`          // URI of the file storing the data
	ContainerSubdir string                 `protobuf:"bytes,2,opt,name=container_subdir,json=containerSubdir,proto3" json:"container_subdir,omitempty"` // Subdir of the file storing the data
	Bands           []int64                `protobuf:"varint,3,rep,packed,name=bands,proto3" json:"bands,omitempty"`                                    // Subbands of the file requested
	Dformat         *DataFormat            `protobuf:"bytes,4,opt,name=dformat,proto3" json:"dformat,omitempty"`                                        // Internal dataformat of the data
	RangeMin        float64                `protobuf:"fixed64,5,opt,name=range_min,json=rangeMin,proto3" json:"range_min,omitempty"`                    // dformat.RangeMin will be mapped to this value
	RangeMax        float64                `protobuf:"fixed64,6,opt,name=range_max,json=rangeMax,proto3" json:"range_max,omitempty"`                    // dformat.RangeMax will be mapped to this value
	Exponent        float64                `protobuf:"fixed64,7,opt,name=exponent,proto3" json:"exponent,omitempty"`                                    // Exponent used to map the value from dformat to [RangeMin, RangeMax]
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InternalMeta) Reset() {
	*x = InternalMeta{}
	mi := &file_pb_datasetMeta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalMeta) ProtoMessage() {}

func (x *InternalMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_datasetMeta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalMeta.ProtoReflect.Descriptor instead.
func (*InternalMeta) Descriptor() ([]byte, []int) {
	return file_pb_datasetMeta_proto_rawDescGZIP(), []int{1}
}

func (x *InternalMeta) GetContainerUri() string {
	if x != nil {
		return x.ContainerUri
	}
	return ""
}

func (x *InternalMeta) GetContainerSubdir() string {
	if x != nil {
		return x.ContainerSubdir
	}
	return ""
}

func (x *InternalMeta) GetBands() []int64 {
	if x != nil {
		return x.Bands
	}
	return nil
}

func (x *InternalMeta) GetDformat() *DataFormat {
	if x != nil {
		return x.Dformat
	}
	return nil
}

func (x *InternalMeta) GetRangeMin() float64 {
	if x != nil {
		return x.RangeMin
	}
	return 0
}

func (x *InternalMeta) GetRangeMax() float64 {
	if x != nil {
		return x.RangeMax
	}
	return 0
}

func (x *InternalMeta) GetExponent() float64 {
	if x != nil {
		return x.Exponent
	}
	return 0
}

var File_pb_datasetMeta_proto protoreflect.FileDescriptor

const file_pb_datasetMeta_proto_rawDesc = "" +
	"\n" +
	"\x14pb/datasetMeta.proto\x12\ageocube\x1a\x13pb/dataformat.proto\"J\n" +
	"\vDatasetMeta\x12;\n" +
	"\rinternalsMeta\x18\x03 \x03(\v2\x15.geocube.InternalMetaR\rinternalsMeta\"\xf9\x01\n" +
	"\fInternalMeta\x12#\n" +
	"\rcontainer_uri\x18\x01 \x01(\tR\fcontainerUri\x12)\n" +
	"\x10container_subdir\x18\x02 \x01(\tR\x0fcontainerSubdir\x12\x14\n" +
	"\x05bands\x18\x03 \x03(\x03R\x05bands\x12-\n" +
	"\adformat\x18\x04 \x01(\v2\x13.geocube.DataFormatR\adformat\x12\x1b\n" +
	"\trange_min\x18\x05 \x01(\x01R\brangeMin\x12\x1b\n" +
	"\trange_max\x18\x06 \x01(\x01R\brangeMax\x12\x1a\n" +
	"\bexponent\x18\a \x01(\x01R\bexponentB\x0eZ\f./pb;geocubeb\x06proto3"

var (
	file_pb_datasetMeta_proto_rawDescOnce sync.Once
	file_pb_datasetMeta_proto_rawDescData []byte
)

func file_pb_datasetMeta_proto_rawDescGZIP() []byte {
	file_pb_datasetMeta_proto_rawDescOnce.Do(func() {
		file_pb_datasetMeta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_datasetMeta_proto_rawDesc), len(file_pb_datasetMeta_proto_rawDesc)))
	})
	return file_pb_datasetMeta_proto_rawDescData
}

var file_pb_datasetMeta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_datasetMeta_proto_goTypes = []any{
	(*DatasetMeta)(nil),  // 0: geocube.DatasetMeta
	(*InternalMeta)(nil), // 1: geocube.InternalMeta
	(*DataFormat)(nil),   // 2: geocube.DataFormat
}
var file_pb_datasetMeta_proto_depIdxs = []int32{
	1, // 0: geocube.DatasetMeta.internalsMeta:type_name -> geocube.InternalMeta
	2, // 1: geocube.InternalMeta.dformat:type_name -> geocube.DataFormat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_datasetMeta_proto_init() }
func file_pb_datasetMeta_proto_init() {
	if File_pb_datasetMeta_proto != nil {
		return
	}
	file_pb_dataformat_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_datasetMeta_proto_rawDesc), len(file_pb_datasetMeta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_datasetMeta_proto_goTypes,
		DependencyIndexes: file_pb_datasetMeta_proto_depIdxs,
		MessageInfos:      file_pb_datasetMeta_proto_msgTypes,
	}.Build()
	File_pb_datasetMeta_proto = out.File
	file_pb_datasetMeta_proto_goTypes = nil
	file_pb_datasetMeta_proto_depIdxs = nil
}
