// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/dataformat.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Type of data supported by the Geocube & GDAL
type DataFormat_Dtype int32

const (
	DataFormat_UNDEFINED DataFormat_Dtype = 0
	DataFormat_UInt8     DataFormat_Dtype = 1
	DataFormat_UInt16    DataFormat_Dtype = 2
	DataFormat_UInt32    DataFormat_Dtype = 3
	DataFormat_Int8      DataFormat_Dtype = 4
	DataFormat_Int16     DataFormat_Dtype = 5
	DataFormat_Int32     DataFormat_Dtype = 6
	DataFormat_Float32   DataFormat_Dtype = 7
	DataFormat_Float64   DataFormat_Dtype = 8
	DataFormat_Complex64 DataFormat_Dtype = 9 // Pair of float32
)

// Enum value maps for DataFormat_Dtype.
var (
	DataFormat_Dtype_name = map[int32]string{
		0: "UNDEFINED",
		1: "UInt8",
		2: "UInt16",
		3: "UInt32",
		4: "Int8",
		5: "Int16",
		6: "Int32",
		7: "Float32",
		8: "Float64",
		9: "Complex64",
	}
	DataFormat_Dtype_value = map[string]int32{
		"UNDEFINED": 0,
		"UInt8":     1,
		"UInt16":    2,
		"UInt32":    3,
		"Int8":      4,
		"Int16":     5,
		"Int32":     6,
		"Float32":   7,
		"Float64":   8,
		"Complex64": 9,
	}
)

func (x DataFormat_Dtype) Enum() *DataFormat_Dtype {
	p := new(DataFormat_Dtype)
	*p = x
	return p
}

func (x DataFormat_Dtype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataFormat_Dtype) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_dataformat_proto_enumTypes[0].Descriptor()
}

func (DataFormat_Dtype) Type() protoreflect.EnumType {
	return &file_pb_dataformat_proto_enumTypes[0]
}

func (x DataFormat_Dtype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataFormat_Dtype.Descriptor instead.
func (DataFormat_Dtype) EnumDescriptor() ([]byte, []int) {
	return file_pb_dataformat_proto_rawDescGZIP(), []int{0, 0}
}

// *
// Format of the data of a dataset.
// Format is defined by the type of the data, its no-data value and the range of values (its interpretation depends on the use)
type DataFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dtype         DataFormat_Dtype       `protobuf:"varint,1,opt,name=dtype,proto3,enum=geocube.DataFormat_Dtype" json:"dtype,omitempty"` // Type of the data
	NoData        float64                `protobuf:"fixed64,2,opt,name=no_data,json=noData,proto3" json:"no_data,omitempty"`              // No-data value (supports any float values, including NaN)
	MinValue      float64                `protobuf:"fixed64,3,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`        // Min value (usually used to map from one min value to another)
	MaxValue      float64                `protobuf:"fixed64,4,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`        // Max value (usually used to map from one min value to another)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFormat) Reset() {
	*x = DataFormat{}
	mi := &file_pb_dataformat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFormat) ProtoMessage() {}

func (x *DataFormat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_dataformat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFormat.ProtoReflect.Descriptor instead.
func (*DataFormat) Descriptor() ([]byte, []int) {
	return file_pb_dataformat_proto_rawDescGZIP(), []int{0}
}

func (x *DataFormat) GetDtype() DataFormat_Dtype {
	if x != nil {
		return x.Dtype
	}
	return DataFormat_UNDEFINED
}

func (x *DataFormat) GetNoData() float64 {
	if x != nil {
		return x.NoData
	}
	return 0
}

func (x *DataFormat) GetMinValue() float64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *DataFormat) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

var File_pb_dataformat_proto protoreflect.FileDescriptor

const file_pb_dataformat_proto_rawDesc = "" +
	"\n" +
	"\x13pb/dataformat.proto\x12\ageocube\"\x95\x02\n" +
	"\n" +
	"DataFormat\x12/\n" +
	"\x05dtype\x18\x01 \x01(\x0e2\x19.geocube.DataFormat.DtypeR\x05dtype\x12\x17\n" +
	"\ano_data\x18\x02 \x01(\x01R\x06noData\x12\x1b\n" +
	"\tmin_value\x18\x03 \x01(\x01R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x04 \x01(\x01R\bmaxValue\"\x82\x01\n" +
	"\x05Dtype\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\t\n" +
	"\x05UInt8\x10\x01\x12\n" +
	"\n" +
	"\x06UInt16\x10\x02\x12\n" +
	"\n" +
	"\x06UInt32\x10\x03\x12\b\n" +
	"\x04Int8\x10\x04\x12\t\n" +
	"\x05Int16\x10\x05\x12\t\n" +
	"\x05Int32\x10\x06\x12\v\n" +
	"\aFloat32\x10\a\x12\v\n" +
	"\aFloat64\x10\b\x12\r\n" +
	"\tComplex64\x10\tB\x0eZ\f./pb;geocubeb\x06proto3"

var (
	file_pb_dataformat_proto_rawDescOnce sync.Once
	file_pb_dataformat_proto_rawDescData []byte
)

func file_pb_dataformat_proto_rawDescGZIP() []byte {
	file_pb_dataformat_proto_rawDescOnce.Do(func() {
		file_pb_dataformat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_dataformat_proto_rawDesc), len(file_pb_dataformat_proto_rawDesc)))
	})
	return file_pb_dataformat_proto_rawDescData
}

var file_pb_dataformat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_dataformat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_dataformat_proto_goTypes = []any{
	(DataFormat_Dtype)(0), // 0: geocube.DataFormat.Dtype
	(*DataFormat)(nil),    // 1: geocube.DataFormat
}
var file_pb_dataformat_proto_depIdxs = []int32{
	0, // 0: geocube.DataFormat.dtype:type_name -> geocube.DataFormat.Dtype
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_dataformat_proto_init() }
func file_pb_dataformat_proto_init() {
	if File_pb_dataformat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_dataformat_proto_rawDesc), len(file_pb_dataformat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_dataformat_proto_goTypes,
		DependencyIndexes: file_pb_dataformat_proto_depIdxs,
		EnumInfos:         file_pb_dataformat_proto_enumTypes,
		MessageInfos:      file_pb_dataformat_proto_msgTypes,
	}.Build()
	File_pb_dataformat_proto = out.File
	file_pb_dataformat_proto_goTypes = nil
	file_pb_dataformat_proto_depIdxs = nil
}
