// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: pb/geocubeDownloader.proto

package geocube

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeocubeDownloader_DownloadCube_FullMethodName = "/geocube.GeocubeDownloader/DownloadCube"
	GeocubeDownloader_Version_FullMethodName      = "/geocube.GeocubeDownloader/Version"
)

// GeocubeDownloaderClient is the client API for GeocubeDownloader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// API GeocubeDownloader to download a cube from metadata
type GeocubeDownloaderClient interface {
	// Request cube using metadatas returned by a call to Geocube.GetCube()
	DownloadCube(ctx context.Context, in *GetCubeMetadataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetCubeMetadataResponse], error)
	// Version of the GeocubeDownloader
	Version(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
}

type geocubeDownloaderClient struct {
	cc grpc.ClientConnInterface
}

func NewGeocubeDownloaderClient(cc grpc.ClientConnInterface) GeocubeDownloaderClient {
	return &geocubeDownloaderClient{cc}
}

func (c *geocubeDownloaderClient) DownloadCube(ctx context.Context, in *GetCubeMetadataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetCubeMetadataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GeocubeDownloader_ServiceDesc.Streams[0], GeocubeDownloader_DownloadCube_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCubeMetadataRequest, GetCubeMetadataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeocubeDownloader_DownloadCubeClient = grpc.ServerStreamingClient[GetCubeMetadataResponse]

func (c *geocubeDownloaderClient) Version(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, GeocubeDownloader_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeocubeDownloaderServer is the server API for GeocubeDownloader service.
// All implementations must embed UnimplementedGeocubeDownloaderServer
// for forward compatibility.
//
// *
// API GeocubeDownloader to download a cube from metadata
type GeocubeDownloaderServer interface {
	// Request cube using metadatas returned by a call to Geocube.GetCube()
	DownloadCube(*GetCubeMetadataRequest, grpc.ServerStreamingServer[GetCubeMetadataResponse]) error
	// Version of the GeocubeDownloader
	Version(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	mustEmbedUnimplementedGeocubeDownloaderServer()
}

// UnimplementedGeocubeDownloaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeocubeDownloaderServer struct{}

func (UnimplementedGeocubeDownloaderServer) DownloadCube(*GetCubeMetadataRequest, grpc.ServerStreamingServer[GetCubeMetadataResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadCube not implemented")
}
func (UnimplementedGeocubeDownloaderServer) Version(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedGeocubeDownloaderServer) mustEmbedUnimplementedGeocubeDownloaderServer() {}
func (UnimplementedGeocubeDownloaderServer) testEmbeddedByValue()                           {}

// UnsafeGeocubeDownloaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeocubeDownloaderServer will
// result in compilation errors.
type UnsafeGeocubeDownloaderServer interface {
	mustEmbedUnimplementedGeocubeDownloaderServer()
}

func RegisterGeocubeDownloaderServer(s grpc.ServiceRegistrar, srv GeocubeDownloaderServer) {
	// If the following call panics, it indicates UnimplementedGeocubeDownloaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeocubeDownloader_ServiceDesc, srv)
}

func _GeocubeDownloader_DownloadCube_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCubeMetadataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeocubeDownloaderServer).DownloadCube(m, &grpc.GenericServerStream[GetCubeMetadataRequest, GetCubeMetadataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeocubeDownloader_DownloadCubeServer = grpc.ServerStreamingServer[GetCubeMetadataResponse]

func _GeocubeDownloader_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeDownloaderServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeocubeDownloader_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeDownloaderServer).Version(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeocubeDownloader_ServiceDesc is the grpc.ServiceDesc for GeocubeDownloader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeocubeDownloader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geocube.GeocubeDownloader",
	HandlerType: (*GeocubeDownloaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _GeocubeDownloader_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadCube",
			Handler:       _GeocubeDownloader_DownloadCube_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/geocubeDownloader.proto",
}
