// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: pb/geocube.proto

package geocube

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Geocube_CreateRecords_FullMethodName          = "/geocube.Geocube/CreateRecords"
	Geocube_GetRecords_FullMethodName             = "/geocube.Geocube/GetRecords"
	Geocube_ListRecords_FullMethodName            = "/geocube.Geocube/ListRecords"
	Geocube_AddRecordsTags_FullMethodName         = "/geocube.Geocube/AddRecordsTags"
	Geocube_RemoveRecordsTags_FullMethodName      = "/geocube.Geocube/RemoveRecordsTags"
	Geocube_DeleteRecords_FullMethodName          = "/geocube.Geocube/DeleteRecords"
	Geocube_CreateAOI_FullMethodName              = "/geocube.Geocube/CreateAOI"
	Geocube_GetAOI_FullMethodName                 = "/geocube.Geocube/GetAOI"
	Geocube_CreateVariable_FullMethodName         = "/geocube.Geocube/CreateVariable"
	Geocube_GetVariable_FullMethodName            = "/geocube.Geocube/GetVariable"
	Geocube_UpdateVariable_FullMethodName         = "/geocube.Geocube/UpdateVariable"
	Geocube_DeleteVariable_FullMethodName         = "/geocube.Geocube/DeleteVariable"
	Geocube_ListVariables_FullMethodName          = "/geocube.Geocube/ListVariables"
	Geocube_InstantiateVariable_FullMethodName    = "/geocube.Geocube/InstantiateVariable"
	Geocube_UpdateInstance_FullMethodName         = "/geocube.Geocube/UpdateInstance"
	Geocube_DeleteInstance_FullMethodName         = "/geocube.Geocube/DeleteInstance"
	Geocube_CreatePalette_FullMethodName          = "/geocube.Geocube/CreatePalette"
	Geocube_GetContainers_FullMethodName          = "/geocube.Geocube/GetContainers"
	Geocube_IndexDatasets_FullMethodName          = "/geocube.Geocube/IndexDatasets"
	Geocube_ListDatasets_FullMethodName           = "/geocube.Geocube/ListDatasets"
	Geocube_DeleteDatasets_FullMethodName         = "/geocube.Geocube/DeleteDatasets"
	Geocube_ConfigConsolidation_FullMethodName    = "/geocube.Geocube/ConfigConsolidation"
	Geocube_GetConsolidationParams_FullMethodName = "/geocube.Geocube/GetConsolidationParams"
	Geocube_Consolidate_FullMethodName            = "/geocube.Geocube/Consolidate"
	Geocube_ListJobs_FullMethodName               = "/geocube.Geocube/ListJobs"
	Geocube_GetJob_FullMethodName                 = "/geocube.Geocube/GetJob"
	Geocube_CleanJobs_FullMethodName              = "/geocube.Geocube/CleanJobs"
	Geocube_RetryJob_FullMethodName               = "/geocube.Geocube/RetryJob"
	Geocube_CancelJob_FullMethodName              = "/geocube.Geocube/CancelJob"
	Geocube_ContinueJob_FullMethodName            = "/geocube.Geocube/ContinueJob"
	Geocube_GetCube_FullMethodName                = "/geocube.Geocube/GetCube"
	Geocube_GetXYZTile_FullMethodName             = "/geocube.Geocube/GetXYZTile"
	Geocube_CreateLayout_FullMethodName           = "/geocube.Geocube/CreateLayout"
	Geocube_DeleteLayout_FullMethodName           = "/geocube.Geocube/DeleteLayout"
	Geocube_ListLayouts_FullMethodName            = "/geocube.Geocube/ListLayouts"
	Geocube_FindContainerLayouts_FullMethodName   = "/geocube.Geocube/FindContainerLayouts"
	Geocube_TileAOI_FullMethodName                = "/geocube.Geocube/TileAOI"
	Geocube_CreateGrid_FullMethodName             = "/geocube.Geocube/CreateGrid"
	Geocube_DeleteGrid_FullMethodName             = "/geocube.Geocube/DeleteGrid"
	Geocube_ListGrids_FullMethodName              = "/geocube.Geocube/ListGrids"
	Geocube_Version_FullMethodName                = "/geocube.Geocube/Version"
	Geocube_GetPalette_FullMethodName             = "/geocube.Geocube/GetPalette"
)

// GeocubeClient is the client API for Geocube service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// API
// Documentation may be detailed in Request/Response sections.
type GeocubeClient interface {
	// Create one or a list of records
	CreateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*CreateRecordsResponse, error)
	// Get records from their ID
	GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetRecordsResponseItem], error)
	// List records given criterias
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListRecordsResponseItem], error)
	// Update records, adding or updating tags
	AddRecordsTags(ctx context.Context, in *AddRecordsTagsRequest, opts ...grpc.CallOption) (*AddRecordsTagsResponse, error)
	// Update records, removing tags
	RemoveRecordsTags(ctx context.Context, in *RemoveRecordsTagsRequest, opts ...grpc.CallOption) (*RemoveRecordsTagsResponse, error)
	// Delete records
	DeleteRecords(ctx context.Context, in *DeleteRecordsRequest, opts ...grpc.CallOption) (*DeleteRecordsResponse, error)
	// Create an AOI if not exists or returns the aoi id of the aoi.
	CreateAOI(ctx context.Context, in *CreateAOIRequest, opts ...grpc.CallOption) (*CreateAOIResponse, error)
	// Get an AOI from its ID
	GetAOI(ctx context.Context, in *GetAOIRequest, opts ...grpc.CallOption) (*GetAOIResponse, error)
	// Create a variable
	CreateVariable(ctx context.Context, in *CreateVariableRequest, opts ...grpc.CallOption) (*CreateVariableResponse, error)
	// Get a variable given its id, name or one of its instance id
	GetVariable(ctx context.Context, in *GetVariableRequest, opts ...grpc.CallOption) (*GetVariableResponse, error)
	// Update some fields of a variable
	UpdateVariable(ctx context.Context, in *UpdateVariableRequest, opts ...grpc.CallOption) (*UpdateVariableResponse, error)
	// Delete a variable iif no dataset has a reference on
	DeleteVariable(ctx context.Context, in *DeleteVariableRequest, opts ...grpc.CallOption) (*DeleteVariableResponse, error)
	// List variables given a name pattern
	ListVariables(ctx context.Context, in *ListVariablesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListVariablesResponseItem], error)
	// Instantiate a variable
	InstantiateVariable(ctx context.Context, in *InstantiateVariableRequest, opts ...grpc.CallOption) (*InstantiateVariableResponse, error)
	// Update metadata of an instance
	UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (*UpdateInstanceResponse, error)
	// Delete an instance iif no dataset has a reference on
	DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*DeleteInstanceResponse, error)
	// Create or update a palette that can be used to create a display of a dataset
	CreatePalette(ctx context.Context, in *CreatePaletteRequest, opts ...grpc.CallOption) (*CreatePaletteResponse, error)
	// GetInfo on containers
	GetContainers(ctx context.Context, in *GetContainersRequest, opts ...grpc.CallOption) (*GetContainersResponse, error)
	// Index new datasets in the Geocube
	IndexDatasets(ctx context.Context, in *IndexDatasetsRequest, opts ...grpc.CallOption) (*IndexDatasetsResponse, error)
	// List datasets from the Geocube
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	// Delete datasets using records, instances and/or filepath
	DeleteDatasets(ctx context.Context, in *DeleteDatasetsRequest, opts ...grpc.CallOption) (*DeleteDatasetsResponse, error)
	// Configurate a consolidation process
	ConfigConsolidation(ctx context.Context, in *ConfigConsolidationRequest, opts ...grpc.CallOption) (*ConfigConsolidationResponse, error)
	// Get the configuration of a consolidation
	GetConsolidationParams(ctx context.Context, in *GetConsolidationParamsRequest, opts ...grpc.CallOption) (*GetConsolidationParamsResponse, error)
	// Start a consolidation job
	Consolidate(ctx context.Context, in *ConsolidateRequest, opts ...grpc.CallOption) (*ConsolidateResponse, error)
	// List the jobs given a name pattern
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// Get a job given its name
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// Delete jobs given their status
	CleanJobs(ctx context.Context, in *CleanJobsRequest, opts ...grpc.CallOption) (*CleanJobsResponse, error)
	// Retry a job
	RetryJob(ctx context.Context, in *RetryJobRequest, opts ...grpc.CallOption) (*RetryJobResponse, error)
	// Cancel a job
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// Continue a job that is in waiting state
	ContinueJob(ctx context.Context, in *ContinueJobRequest, opts ...grpc.CallOption) (*ContinueJobResponse, error)
	// Get a cube of data given a CubeParams
	GetCube(ctx context.Context, in *GetCubeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetCubeResponse], error)
	// Get a XYZTile (can be used with a TileServer, provided a GRPCGateway is up)
	GetXYZTile(ctx context.Context, in *GetTileRequest, opts ...grpc.CallOption) (*GetTileResponse, error)
	// Create a layout to be used for tiling or consolidation
	CreateLayout(ctx context.Context, in *CreateLayoutRequest, opts ...grpc.CallOption) (*CreateLayoutResponse, error)
	// Delete a layout given its name
	DeleteLayout(ctx context.Context, in *DeleteLayoutRequest, opts ...grpc.CallOption) (*DeleteLayoutResponse, error)
	// List layouts given a name pattern
	ListLayouts(ctx context.Context, in *ListLayoutsRequest, opts ...grpc.CallOption) (*ListLayoutsResponse, error)
	// Find all the layouts known for a set of containers
	FindContainerLayouts(ctx context.Context, in *FindContainerLayoutsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FindContainerLayoutsResponse], error)
	// Tile an AOI given a layout
	TileAOI(ctx context.Context, in *TileAOIRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TileAOIResponse], error)
	// Create a grid that can be used to tile an AOI
	CreateGrid(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateGridRequest, CreateGridResponse], error)
	// Delete a grid
	DeleteGrid(ctx context.Context, in *DeleteGridRequest, opts ...grpc.CallOption) (*DeleteGridResponse, error)
	// List grids given a name pattern
	ListGrids(ctx context.Context, in *ListGridsRequest, opts ...grpc.CallOption) (*ListGridsResponse, error)
	// Version of the GeocubeServer
	Version(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// GetPalette given a name
	GetPalette(ctx context.Context, in *GetPaletteRequest, opts ...grpc.CallOption) (*GetPaletteResponse, error)
}

type geocubeClient struct {
	cc grpc.ClientConnInterface
}

func NewGeocubeClient(cc grpc.ClientConnInterface) GeocubeClient {
	return &geocubeClient{cc}
}

func (c *geocubeClient) CreateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*CreateRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRecordsResponse)
	err := c.cc.Invoke(ctx, Geocube_CreateRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetRecordsResponseItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Geocube_ServiceDesc.Streams[0], Geocube_GetRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRecordsRequest, GetRecordsResponseItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_GetRecordsClient = grpc.ServerStreamingClient[GetRecordsResponseItem]

func (c *geocubeClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListRecordsResponseItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Geocube_ServiceDesc.Streams[1], Geocube_ListRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListRecordsRequest, ListRecordsResponseItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_ListRecordsClient = grpc.ServerStreamingClient[ListRecordsResponseItem]

func (c *geocubeClient) AddRecordsTags(ctx context.Context, in *AddRecordsTagsRequest, opts ...grpc.CallOption) (*AddRecordsTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRecordsTagsResponse)
	err := c.cc.Invoke(ctx, Geocube_AddRecordsTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) RemoveRecordsTags(ctx context.Context, in *RemoveRecordsTagsRequest, opts ...grpc.CallOption) (*RemoveRecordsTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRecordsTagsResponse)
	err := c.cc.Invoke(ctx, Geocube_RemoveRecordsTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) DeleteRecords(ctx context.Context, in *DeleteRecordsRequest, opts ...grpc.CallOption) (*DeleteRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRecordsResponse)
	err := c.cc.Invoke(ctx, Geocube_DeleteRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) CreateAOI(ctx context.Context, in *CreateAOIRequest, opts ...grpc.CallOption) (*CreateAOIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAOIResponse)
	err := c.cc.Invoke(ctx, Geocube_CreateAOI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) GetAOI(ctx context.Context, in *GetAOIRequest, opts ...grpc.CallOption) (*GetAOIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAOIResponse)
	err := c.cc.Invoke(ctx, Geocube_GetAOI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) CreateVariable(ctx context.Context, in *CreateVariableRequest, opts ...grpc.CallOption) (*CreateVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVariableResponse)
	err := c.cc.Invoke(ctx, Geocube_CreateVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) GetVariable(ctx context.Context, in *GetVariableRequest, opts ...grpc.CallOption) (*GetVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVariableResponse)
	err := c.cc.Invoke(ctx, Geocube_GetVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) UpdateVariable(ctx context.Context, in *UpdateVariableRequest, opts ...grpc.CallOption) (*UpdateVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVariableResponse)
	err := c.cc.Invoke(ctx, Geocube_UpdateVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) DeleteVariable(ctx context.Context, in *DeleteVariableRequest, opts ...grpc.CallOption) (*DeleteVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVariableResponse)
	err := c.cc.Invoke(ctx, Geocube_DeleteVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) ListVariables(ctx context.Context, in *ListVariablesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListVariablesResponseItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Geocube_ServiceDesc.Streams[2], Geocube_ListVariables_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListVariablesRequest, ListVariablesResponseItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_ListVariablesClient = grpc.ServerStreamingClient[ListVariablesResponseItem]

func (c *geocubeClient) InstantiateVariable(ctx context.Context, in *InstantiateVariableRequest, opts ...grpc.CallOption) (*InstantiateVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstantiateVariableResponse)
	err := c.cc.Invoke(ctx, Geocube_InstantiateVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (*UpdateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInstanceResponse)
	err := c.cc.Invoke(ctx, Geocube_UpdateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*DeleteInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInstanceResponse)
	err := c.cc.Invoke(ctx, Geocube_DeleteInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) CreatePalette(ctx context.Context, in *CreatePaletteRequest, opts ...grpc.CallOption) (*CreatePaletteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaletteResponse)
	err := c.cc.Invoke(ctx, Geocube_CreatePalette_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) GetContainers(ctx context.Context, in *GetContainersRequest, opts ...grpc.CallOption) (*GetContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainersResponse)
	err := c.cc.Invoke(ctx, Geocube_GetContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) IndexDatasets(ctx context.Context, in *IndexDatasetsRequest, opts ...grpc.CallOption) (*IndexDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexDatasetsResponse)
	err := c.cc.Invoke(ctx, Geocube_IndexDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetsResponse)
	err := c.cc.Invoke(ctx, Geocube_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) DeleteDatasets(ctx context.Context, in *DeleteDatasetsRequest, opts ...grpc.CallOption) (*DeleteDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDatasetsResponse)
	err := c.cc.Invoke(ctx, Geocube_DeleteDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) ConfigConsolidation(ctx context.Context, in *ConfigConsolidationRequest, opts ...grpc.CallOption) (*ConfigConsolidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigConsolidationResponse)
	err := c.cc.Invoke(ctx, Geocube_ConfigConsolidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) GetConsolidationParams(ctx context.Context, in *GetConsolidationParamsRequest, opts ...grpc.CallOption) (*GetConsolidationParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConsolidationParamsResponse)
	err := c.cc.Invoke(ctx, Geocube_GetConsolidationParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) Consolidate(ctx context.Context, in *ConsolidateRequest, opts ...grpc.CallOption) (*ConsolidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsolidateResponse)
	err := c.cc.Invoke(ctx, Geocube_Consolidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, Geocube_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, Geocube_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) CleanJobs(ctx context.Context, in *CleanJobsRequest, opts ...grpc.CallOption) (*CleanJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanJobsResponse)
	err := c.cc.Invoke(ctx, Geocube_CleanJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) RetryJob(ctx context.Context, in *RetryJobRequest, opts ...grpc.CallOption) (*RetryJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryJobResponse)
	err := c.cc.Invoke(ctx, Geocube_RetryJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, Geocube_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) ContinueJob(ctx context.Context, in *ContinueJobRequest, opts ...grpc.CallOption) (*ContinueJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContinueJobResponse)
	err := c.cc.Invoke(ctx, Geocube_ContinueJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) GetCube(ctx context.Context, in *GetCubeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetCubeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Geocube_ServiceDesc.Streams[3], Geocube_GetCube_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCubeRequest, GetCubeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_GetCubeClient = grpc.ServerStreamingClient[GetCubeResponse]

func (c *geocubeClient) GetXYZTile(ctx context.Context, in *GetTileRequest, opts ...grpc.CallOption) (*GetTileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTileResponse)
	err := c.cc.Invoke(ctx, Geocube_GetXYZTile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) CreateLayout(ctx context.Context, in *CreateLayoutRequest, opts ...grpc.CallOption) (*CreateLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLayoutResponse)
	err := c.cc.Invoke(ctx, Geocube_CreateLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) DeleteLayout(ctx context.Context, in *DeleteLayoutRequest, opts ...grpc.CallOption) (*DeleteLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLayoutResponse)
	err := c.cc.Invoke(ctx, Geocube_DeleteLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) ListLayouts(ctx context.Context, in *ListLayoutsRequest, opts ...grpc.CallOption) (*ListLayoutsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLayoutsResponse)
	err := c.cc.Invoke(ctx, Geocube_ListLayouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) FindContainerLayouts(ctx context.Context, in *FindContainerLayoutsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FindContainerLayoutsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Geocube_ServiceDesc.Streams[4], Geocube_FindContainerLayouts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FindContainerLayoutsRequest, FindContainerLayoutsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_FindContainerLayoutsClient = grpc.ServerStreamingClient[FindContainerLayoutsResponse]

func (c *geocubeClient) TileAOI(ctx context.Context, in *TileAOIRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TileAOIResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Geocube_ServiceDesc.Streams[5], Geocube_TileAOI_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TileAOIRequest, TileAOIResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_TileAOIClient = grpc.ServerStreamingClient[TileAOIResponse]

func (c *geocubeClient) CreateGrid(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateGridRequest, CreateGridResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Geocube_ServiceDesc.Streams[6], Geocube_CreateGrid_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateGridRequest, CreateGridResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_CreateGridClient = grpc.ClientStreamingClient[CreateGridRequest, CreateGridResponse]

func (c *geocubeClient) DeleteGrid(ctx context.Context, in *DeleteGridRequest, opts ...grpc.CallOption) (*DeleteGridResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGridResponse)
	err := c.cc.Invoke(ctx, Geocube_DeleteGrid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) ListGrids(ctx context.Context, in *ListGridsRequest, opts ...grpc.CallOption) (*ListGridsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGridsResponse)
	err := c.cc.Invoke(ctx, Geocube_ListGrids_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) Version(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, Geocube_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocubeClient) GetPalette(ctx context.Context, in *GetPaletteRequest, opts ...grpc.CallOption) (*GetPaletteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaletteResponse)
	err := c.cc.Invoke(ctx, Geocube_GetPalette_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeocubeServer is the server API for Geocube service.
// All implementations must embed UnimplementedGeocubeServer
// for forward compatibility.
//
// *
// API
// Documentation may be detailed in Request/Response sections.
type GeocubeServer interface {
	// Create one or a list of records
	CreateRecords(context.Context, *CreateRecordsRequest) (*CreateRecordsResponse, error)
	// Get records from their ID
	GetRecords(*GetRecordsRequest, grpc.ServerStreamingServer[GetRecordsResponseItem]) error
	// List records given criterias
	ListRecords(*ListRecordsRequest, grpc.ServerStreamingServer[ListRecordsResponseItem]) error
	// Update records, adding or updating tags
	AddRecordsTags(context.Context, *AddRecordsTagsRequest) (*AddRecordsTagsResponse, error)
	// Update records, removing tags
	RemoveRecordsTags(context.Context, *RemoveRecordsTagsRequest) (*RemoveRecordsTagsResponse, error)
	// Delete records
	DeleteRecords(context.Context, *DeleteRecordsRequest) (*DeleteRecordsResponse, error)
	// Create an AOI if not exists or returns the aoi id of the aoi.
	CreateAOI(context.Context, *CreateAOIRequest) (*CreateAOIResponse, error)
	// Get an AOI from its ID
	GetAOI(context.Context, *GetAOIRequest) (*GetAOIResponse, error)
	// Create a variable
	CreateVariable(context.Context, *CreateVariableRequest) (*CreateVariableResponse, error)
	// Get a variable given its id, name or one of its instance id
	GetVariable(context.Context, *GetVariableRequest) (*GetVariableResponse, error)
	// Update some fields of a variable
	UpdateVariable(context.Context, *UpdateVariableRequest) (*UpdateVariableResponse, error)
	// Delete a variable iif no dataset has a reference on
	DeleteVariable(context.Context, *DeleteVariableRequest) (*DeleteVariableResponse, error)
	// List variables given a name pattern
	ListVariables(*ListVariablesRequest, grpc.ServerStreamingServer[ListVariablesResponseItem]) error
	// Instantiate a variable
	InstantiateVariable(context.Context, *InstantiateVariableRequest) (*InstantiateVariableResponse, error)
	// Update metadata of an instance
	UpdateInstance(context.Context, *UpdateInstanceRequest) (*UpdateInstanceResponse, error)
	// Delete an instance iif no dataset has a reference on
	DeleteInstance(context.Context, *DeleteInstanceRequest) (*DeleteInstanceResponse, error)
	// Create or update a palette that can be used to create a display of a dataset
	CreatePalette(context.Context, *CreatePaletteRequest) (*CreatePaletteResponse, error)
	// GetInfo on containers
	GetContainers(context.Context, *GetContainersRequest) (*GetContainersResponse, error)
	// Index new datasets in the Geocube
	IndexDatasets(context.Context, *IndexDatasetsRequest) (*IndexDatasetsResponse, error)
	// List datasets from the Geocube
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	// Delete datasets using records, instances and/or filepath
	DeleteDatasets(context.Context, *DeleteDatasetsRequest) (*DeleteDatasetsResponse, error)
	// Configurate a consolidation process
	ConfigConsolidation(context.Context, *ConfigConsolidationRequest) (*ConfigConsolidationResponse, error)
	// Get the configuration of a consolidation
	GetConsolidationParams(context.Context, *GetConsolidationParamsRequest) (*GetConsolidationParamsResponse, error)
	// Start a consolidation job
	Consolidate(context.Context, *ConsolidateRequest) (*ConsolidateResponse, error)
	// List the jobs given a name pattern
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// Get a job given its name
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// Delete jobs given their status
	CleanJobs(context.Context, *CleanJobsRequest) (*CleanJobsResponse, error)
	// Retry a job
	RetryJob(context.Context, *RetryJobRequest) (*RetryJobResponse, error)
	// Cancel a job
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// Continue a job that is in waiting state
	ContinueJob(context.Context, *ContinueJobRequest) (*ContinueJobResponse, error)
	// Get a cube of data given a CubeParams
	GetCube(*GetCubeRequest, grpc.ServerStreamingServer[GetCubeResponse]) error
	// Get a XYZTile (can be used with a TileServer, provided a GRPCGateway is up)
	GetXYZTile(context.Context, *GetTileRequest) (*GetTileResponse, error)
	// Create a layout to be used for tiling or consolidation
	CreateLayout(context.Context, *CreateLayoutRequest) (*CreateLayoutResponse, error)
	// Delete a layout given its name
	DeleteLayout(context.Context, *DeleteLayoutRequest) (*DeleteLayoutResponse, error)
	// List layouts given a name pattern
	ListLayouts(context.Context, *ListLayoutsRequest) (*ListLayoutsResponse, error)
	// Find all the layouts known for a set of containers
	FindContainerLayouts(*FindContainerLayoutsRequest, grpc.ServerStreamingServer[FindContainerLayoutsResponse]) error
	// Tile an AOI given a layout
	TileAOI(*TileAOIRequest, grpc.ServerStreamingServer[TileAOIResponse]) error
	// Create a grid that can be used to tile an AOI
	CreateGrid(grpc.ClientStreamingServer[CreateGridRequest, CreateGridResponse]) error
	// Delete a grid
	DeleteGrid(context.Context, *DeleteGridRequest) (*DeleteGridResponse, error)
	// List grids given a name pattern
	ListGrids(context.Context, *ListGridsRequest) (*ListGridsResponse, error)
	// Version of the GeocubeServer
	Version(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// GetPalette given a name
	GetPalette(context.Context, *GetPaletteRequest) (*GetPaletteResponse, error)
	mustEmbedUnimplementedGeocubeServer()
}

// UnimplementedGeocubeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeocubeServer struct{}

func (UnimplementedGeocubeServer) CreateRecords(context.Context, *CreateRecordsRequest) (*CreateRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecords not implemented")
}
func (UnimplementedGeocubeServer) GetRecords(*GetRecordsRequest, grpc.ServerStreamingServer[GetRecordsResponseItem]) error {
	return status.Error(codes.Unimplemented, "method GetRecords not implemented")
}
func (UnimplementedGeocubeServer) ListRecords(*ListRecordsRequest, grpc.ServerStreamingServer[ListRecordsResponseItem]) error {
	return status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedGeocubeServer) AddRecordsTags(context.Context, *AddRecordsTagsRequest) (*AddRecordsTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRecordsTags not implemented")
}
func (UnimplementedGeocubeServer) RemoveRecordsTags(context.Context, *RemoveRecordsTagsRequest) (*RemoveRecordsTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRecordsTags not implemented")
}
func (UnimplementedGeocubeServer) DeleteRecords(context.Context, *DeleteRecordsRequest) (*DeleteRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecords not implemented")
}
func (UnimplementedGeocubeServer) CreateAOI(context.Context, *CreateAOIRequest) (*CreateAOIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAOI not implemented")
}
func (UnimplementedGeocubeServer) GetAOI(context.Context, *GetAOIRequest) (*GetAOIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAOI not implemented")
}
func (UnimplementedGeocubeServer) CreateVariable(context.Context, *CreateVariableRequest) (*CreateVariableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVariable not implemented")
}
func (UnimplementedGeocubeServer) GetVariable(context.Context, *GetVariableRequest) (*GetVariableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVariable not implemented")
}
func (UnimplementedGeocubeServer) UpdateVariable(context.Context, *UpdateVariableRequest) (*UpdateVariableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVariable not implemented")
}
func (UnimplementedGeocubeServer) DeleteVariable(context.Context, *DeleteVariableRequest) (*DeleteVariableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVariable not implemented")
}
func (UnimplementedGeocubeServer) ListVariables(*ListVariablesRequest, grpc.ServerStreamingServer[ListVariablesResponseItem]) error {
	return status.Error(codes.Unimplemented, "method ListVariables not implemented")
}
func (UnimplementedGeocubeServer) InstantiateVariable(context.Context, *InstantiateVariableRequest) (*InstantiateVariableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstantiateVariable not implemented")
}
func (UnimplementedGeocubeServer) UpdateInstance(context.Context, *UpdateInstanceRequest) (*UpdateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInstance not implemented")
}
func (UnimplementedGeocubeServer) DeleteInstance(context.Context, *DeleteInstanceRequest) (*DeleteInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInstance not implemented")
}
func (UnimplementedGeocubeServer) CreatePalette(context.Context, *CreatePaletteRequest) (*CreatePaletteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePalette not implemented")
}
func (UnimplementedGeocubeServer) GetContainers(context.Context, *GetContainersRequest) (*GetContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainers not implemented")
}
func (UnimplementedGeocubeServer) IndexDatasets(context.Context, *IndexDatasetsRequest) (*IndexDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexDatasets not implemented")
}
func (UnimplementedGeocubeServer) ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedGeocubeServer) DeleteDatasets(context.Context, *DeleteDatasetsRequest) (*DeleteDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDatasets not implemented")
}
func (UnimplementedGeocubeServer) ConfigConsolidation(context.Context, *ConfigConsolidationRequest) (*ConfigConsolidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigConsolidation not implemented")
}
func (UnimplementedGeocubeServer) GetConsolidationParams(context.Context, *GetConsolidationParamsRequest) (*GetConsolidationParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsolidationParams not implemented")
}
func (UnimplementedGeocubeServer) Consolidate(context.Context, *ConsolidateRequest) (*ConsolidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Consolidate not implemented")
}
func (UnimplementedGeocubeServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedGeocubeServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedGeocubeServer) CleanJobs(context.Context, *CleanJobsRequest) (*CleanJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanJobs not implemented")
}
func (UnimplementedGeocubeServer) RetryJob(context.Context, *RetryJobRequest) (*RetryJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryJob not implemented")
}
func (UnimplementedGeocubeServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedGeocubeServer) ContinueJob(context.Context, *ContinueJobRequest) (*ContinueJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContinueJob not implemented")
}
func (UnimplementedGeocubeServer) GetCube(*GetCubeRequest, grpc.ServerStreamingServer[GetCubeResponse]) error {
	return status.Error(codes.Unimplemented, "method GetCube not implemented")
}
func (UnimplementedGeocubeServer) GetXYZTile(context.Context, *GetTileRequest) (*GetTileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetXYZTile not implemented")
}
func (UnimplementedGeocubeServer) CreateLayout(context.Context, *CreateLayoutRequest) (*CreateLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLayout not implemented")
}
func (UnimplementedGeocubeServer) DeleteLayout(context.Context, *DeleteLayoutRequest) (*DeleteLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLayout not implemented")
}
func (UnimplementedGeocubeServer) ListLayouts(context.Context, *ListLayoutsRequest) (*ListLayoutsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLayouts not implemented")
}
func (UnimplementedGeocubeServer) FindContainerLayouts(*FindContainerLayoutsRequest, grpc.ServerStreamingServer[FindContainerLayoutsResponse]) error {
	return status.Error(codes.Unimplemented, "method FindContainerLayouts not implemented")
}
func (UnimplementedGeocubeServer) TileAOI(*TileAOIRequest, grpc.ServerStreamingServer[TileAOIResponse]) error {
	return status.Error(codes.Unimplemented, "method TileAOI not implemented")
}
func (UnimplementedGeocubeServer) CreateGrid(grpc.ClientStreamingServer[CreateGridRequest, CreateGridResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateGrid not implemented")
}
func (UnimplementedGeocubeServer) DeleteGrid(context.Context, *DeleteGridRequest) (*DeleteGridResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGrid not implemented")
}
func (UnimplementedGeocubeServer) ListGrids(context.Context, *ListGridsRequest) (*ListGridsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGrids not implemented")
}
func (UnimplementedGeocubeServer) Version(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedGeocubeServer) GetPalette(context.Context, *GetPaletteRequest) (*GetPaletteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPalette not implemented")
}
func (UnimplementedGeocubeServer) mustEmbedUnimplementedGeocubeServer() {}
func (UnimplementedGeocubeServer) testEmbeddedByValue()                 {}

// UnsafeGeocubeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeocubeServer will
// result in compilation errors.
type UnsafeGeocubeServer interface {
	mustEmbedUnimplementedGeocubeServer()
}

func RegisterGeocubeServer(s grpc.ServiceRegistrar, srv GeocubeServer) {
	// If the following call panics, it indicates UnimplementedGeocubeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Geocube_ServiceDesc, srv)
}

func _Geocube_CreateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).CreateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_CreateRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).CreateRecords(ctx, req.(*CreateRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_GetRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeocubeServer).GetRecords(m, &grpc.GenericServerStream[GetRecordsRequest, GetRecordsResponseItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_GetRecordsServer = grpc.ServerStreamingServer[GetRecordsResponseItem]

func _Geocube_ListRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeocubeServer).ListRecords(m, &grpc.GenericServerStream[ListRecordsRequest, ListRecordsResponseItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_ListRecordsServer = grpc.ServerStreamingServer[ListRecordsResponseItem]

func _Geocube_AddRecordsTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordsTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).AddRecordsTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_AddRecordsTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).AddRecordsTags(ctx, req.(*AddRecordsTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_RemoveRecordsTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRecordsTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).RemoveRecordsTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_RemoveRecordsTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).RemoveRecordsTags(ctx, req.(*RemoveRecordsTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_DeleteRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).DeleteRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_DeleteRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).DeleteRecords(ctx, req.(*DeleteRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_CreateAOI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAOIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).CreateAOI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_CreateAOI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).CreateAOI(ctx, req.(*CreateAOIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_GetAOI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAOIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).GetAOI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_GetAOI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).GetAOI(ctx, req.(*GetAOIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_CreateVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).CreateVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_CreateVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).CreateVariable(ctx, req.(*CreateVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_GetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).GetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_GetVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).GetVariable(ctx, req.(*GetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_UpdateVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).UpdateVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_UpdateVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).UpdateVariable(ctx, req.(*UpdateVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_DeleteVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).DeleteVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_DeleteVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).DeleteVariable(ctx, req.(*DeleteVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_ListVariables_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListVariablesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeocubeServer).ListVariables(m, &grpc.GenericServerStream[ListVariablesRequest, ListVariablesResponseItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_ListVariablesServer = grpc.ServerStreamingServer[ListVariablesResponseItem]

func _Geocube_InstantiateVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstantiateVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).InstantiateVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_InstantiateVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).InstantiateVariable(ctx, req.(*InstantiateVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_UpdateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).UpdateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_UpdateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).UpdateInstance(ctx, req.(*UpdateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_DeleteInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).DeleteInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_DeleteInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).DeleteInstance(ctx, req.(*DeleteInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_CreatePalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).CreatePalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_CreatePalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).CreatePalette(ctx, req.(*CreatePaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_GetContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).GetContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_GetContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).GetContainers(ctx, req.(*GetContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_IndexDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).IndexDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_IndexDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).IndexDatasets(ctx, req.(*IndexDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_DeleteDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).DeleteDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_DeleteDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).DeleteDatasets(ctx, req.(*DeleteDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_ConfigConsolidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigConsolidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).ConfigConsolidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_ConfigConsolidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).ConfigConsolidation(ctx, req.(*ConfigConsolidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_GetConsolidationParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsolidationParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).GetConsolidationParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_GetConsolidationParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).GetConsolidationParams(ctx, req.(*GetConsolidationParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_Consolidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsolidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).Consolidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_Consolidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).Consolidate(ctx, req.(*ConsolidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_CleanJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).CleanJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_CleanJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).CleanJobs(ctx, req.(*CleanJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_RetryJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).RetryJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_RetryJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).RetryJob(ctx, req.(*RetryJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_ContinueJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).ContinueJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_ContinueJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).ContinueJob(ctx, req.(*ContinueJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_GetCube_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCubeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeocubeServer).GetCube(m, &grpc.GenericServerStream[GetCubeRequest, GetCubeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_GetCubeServer = grpc.ServerStreamingServer[GetCubeResponse]

func _Geocube_GetXYZTile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).GetXYZTile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_GetXYZTile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).GetXYZTile(ctx, req.(*GetTileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_CreateLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).CreateLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_CreateLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).CreateLayout(ctx, req.(*CreateLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_DeleteLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).DeleteLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_DeleteLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).DeleteLayout(ctx, req.(*DeleteLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_ListLayouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLayoutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).ListLayouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_ListLayouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).ListLayouts(ctx, req.(*ListLayoutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_FindContainerLayouts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FindContainerLayoutsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeocubeServer).FindContainerLayouts(m, &grpc.GenericServerStream[FindContainerLayoutsRequest, FindContainerLayoutsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_FindContainerLayoutsServer = grpc.ServerStreamingServer[FindContainerLayoutsResponse]

func _Geocube_TileAOI_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TileAOIRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeocubeServer).TileAOI(m, &grpc.GenericServerStream[TileAOIRequest, TileAOIResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_TileAOIServer = grpc.ServerStreamingServer[TileAOIResponse]

func _Geocube_CreateGrid_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GeocubeServer).CreateGrid(&grpc.GenericServerStream[CreateGridRequest, CreateGridResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Geocube_CreateGridServer = grpc.ClientStreamingServer[CreateGridRequest, CreateGridResponse]

func _Geocube_DeleteGrid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).DeleteGrid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_DeleteGrid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).DeleteGrid(ctx, req.(*DeleteGridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_ListGrids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGridsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).ListGrids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_ListGrids_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).ListGrids(ctx, req.(*ListGridsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).Version(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocube_GetPalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocubeServer).GetPalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocube_GetPalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocubeServer).GetPalette(ctx, req.(*GetPaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Geocube_ServiceDesc is the grpc.ServiceDesc for Geocube service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Geocube_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geocube.Geocube",
	HandlerType: (*GeocubeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRecords",
			Handler:    _Geocube_CreateRecords_Handler,
		},
		{
			MethodName: "AddRecordsTags",
			Handler:    _Geocube_AddRecordsTags_Handler,
		},
		{
			MethodName: "RemoveRecordsTags",
			Handler:    _Geocube_RemoveRecordsTags_Handler,
		},
		{
			MethodName: "DeleteRecords",
			Handler:    _Geocube_DeleteRecords_Handler,
		},
		{
			MethodName: "CreateAOI",
			Handler:    _Geocube_CreateAOI_Handler,
		},
		{
			MethodName: "GetAOI",
			Handler:    _Geocube_GetAOI_Handler,
		},
		{
			MethodName: "CreateVariable",
			Handler:    _Geocube_CreateVariable_Handler,
		},
		{
			MethodName: "GetVariable",
			Handler:    _Geocube_GetVariable_Handler,
		},
		{
			MethodName: "UpdateVariable",
			Handler:    _Geocube_UpdateVariable_Handler,
		},
		{
			MethodName: "DeleteVariable",
			Handler:    _Geocube_DeleteVariable_Handler,
		},
		{
			MethodName: "InstantiateVariable",
			Handler:    _Geocube_InstantiateVariable_Handler,
		},
		{
			MethodName: "UpdateInstance",
			Handler:    _Geocube_UpdateInstance_Handler,
		},
		{
			MethodName: "DeleteInstance",
			Handler:    _Geocube_DeleteInstance_Handler,
		},
		{
			MethodName: "CreatePalette",
			Handler:    _Geocube_CreatePalette_Handler,
		},
		{
			MethodName: "GetContainers",
			Handler:    _Geocube_GetContainers_Handler,
		},
		{
			MethodName: "IndexDatasets",
			Handler:    _Geocube_IndexDatasets_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _Geocube_ListDatasets_Handler,
		},
		{
			MethodName: "DeleteDatasets",
			Handler:    _Geocube_DeleteDatasets_Handler,
		},
		{
			MethodName: "ConfigConsolidation",
			Handler:    _Geocube_ConfigConsolidation_Handler,
		},
		{
			MethodName: "GetConsolidationParams",
			Handler:    _Geocube_GetConsolidationParams_Handler,
		},
		{
			MethodName: "Consolidate",
			Handler:    _Geocube_Consolidate_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _Geocube_ListJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _Geocube_GetJob_Handler,
		},
		{
			MethodName: "CleanJobs",
			Handler:    _Geocube_CleanJobs_Handler,
		},
		{
			MethodName: "RetryJob",
			Handler:    _Geocube_RetryJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _Geocube_CancelJob_Handler,
		},
		{
			MethodName: "ContinueJob",
			Handler:    _Geocube_ContinueJob_Handler,
		},
		{
			MethodName: "GetXYZTile",
			Handler:    _Geocube_GetXYZTile_Handler,
		},
		{
			MethodName: "CreateLayout",
			Handler:    _Geocube_CreateLayout_Handler,
		},
		{
			MethodName: "DeleteLayout",
			Handler:    _Geocube_DeleteLayout_Handler,
		},
		{
			MethodName: "ListLayouts",
			Handler:    _Geocube_ListLayouts_Handler,
		},
		{
			MethodName: "DeleteGrid",
			Handler:    _Geocube_DeleteGrid_Handler,
		},
		{
			MethodName: "ListGrids",
			Handler:    _Geocube_ListGrids_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Geocube_Version_Handler,
		},
		{
			MethodName: "GetPalette",
			Handler:    _Geocube_GetPalette_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRecords",
			Handler:       _Geocube_GetRecords_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListRecords",
			Handler:       _Geocube_ListRecords_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListVariables",
			Handler:       _Geocube_ListVariables_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCube",
			Handler:       _Geocube_GetCube_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FindContainerLayouts",
			Handler:       _Geocube_FindContainerLayouts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TileAOI",
			Handler:       _Geocube_TileAOI_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateGrid",
			Handler:       _Geocube_CreateGrid_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pb/geocube.proto",
}
