// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/geocubeDownloader.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pb_geocubeDownloader_proto protoreflect.FileDescriptor

const file_pb_geocubeDownloader_proto_rawDesc = "" +
	"\n" +
	"\x1apb/geocubeDownloader.proto\x12\ageocube\x1a\x10pb/version.proto\x1a\x10pb/catalog.proto2\xb0\x01\n" +
	"\x11GeocubeDownloader\x12U\n" +
	"\fDownloadCube\x12\x1f.geocube.GetCubeMetadataRequest\x1a .geocube.GetCubeMetadataResponse\"\x000\x01\x12D\n" +
	"\aVersion\x12\x1a.geocube.GetVersionRequest\x1a\x1b.geocube.GetVersionResponse\"\x00B\x0eZ\f./pb;geocubeb\x06proto3"

var file_pb_geocubeDownloader_proto_goTypes = []any{
	(*GetCubeMetadataRequest)(nil),  // 0: geocube.GetCubeMetadataRequest
	(*GetVersionRequest)(nil),       // 1: geocube.GetVersionRequest
	(*GetCubeMetadataResponse)(nil), // 2: geocube.GetCubeMetadataResponse
	(*GetVersionResponse)(nil),      // 3: geocube.GetVersionResponse
}
var file_pb_geocubeDownloader_proto_depIdxs = []int32{
	0, // 0: geocube.GeocubeDownloader.DownloadCube:input_type -> geocube.GetCubeMetadataRequest
	1, // 1: geocube.GeocubeDownloader.Version:input_type -> geocube.GetVersionRequest
	2, // 2: geocube.GeocubeDownloader.DownloadCube:output_type -> geocube.GetCubeMetadataResponse
	3, // 3: geocube.GeocubeDownloader.Version:output_type -> geocube.GetVersionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_geocubeDownloader_proto_init() }
func file_pb_geocubeDownloader_proto_init() {
	if File_pb_geocubeDownloader_proto != nil {
		return
	}
	file_pb_version_proto_init()
	file_pb_catalog_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_geocubeDownloader_proto_rawDesc), len(file_pb_geocubeDownloader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_geocubeDownloader_proto_goTypes,
		DependencyIndexes: file_pb_geocubeDownloader_proto_depIdxs,
	}.Build()
	File_pb_geocubeDownloader_proto = out.File
	file_pb_geocubeDownloader_proto_goTypes = nil
	file_pb_geocubeDownloader_proto_depIdxs = nil
}
