// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/geocube.proto

package geocube

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pb_geocube_proto protoreflect.FileDescriptor

const file_pb_geocube_proto_rawDesc = "" +
	"\n" +
	"\x10pb/geocube.proto\x12\ageocube\x1a\x1cgoogle/api/annotations.proto\x1a\x10pb/version.proto\x1a\x10pb/catalog.proto\x1a\x10pb/records.proto\x1a\x12pb/variables.proto\x1a\x10pb/layouts.proto\x1a\x13pb/operations.proto\x1a\x11pb/palettes.proto2\xcf\x1a\n" +
	"\aGeocube\x12P\n" +
	"\rCreateRecords\x12\x1d.geocube.CreateRecordsRequest\x1a\x1e.geocube.CreateRecordsResponse\"\x00\x12M\n" +
	"\n" +
	"GetRecords\x12\x1a.geocube.GetRecordsRequest\x1a\x1f.geocube.GetRecordsResponseItem\"\x000\x01\x12P\n" +
	"\vListRecords\x12\x1b.geocube.ListRecordsRequest\x1a .geocube.ListRecordsResponseItem\"\x000\x01\x12S\n" +
	"\x0eAddRecordsTags\x12\x1e.geocube.AddRecordsTagsRequest\x1a\x1f.geocube.AddRecordsTagsResponse\"\x00\x12\\\n" +
	"\x11RemoveRecordsTags\x12!.geocube.RemoveRecordsTagsRequest\x1a\".geocube.RemoveRecordsTagsResponse\"\x00\x12P\n" +
	"\rDeleteRecords\x12\x1d.geocube.DeleteRecordsRequest\x1a\x1e.geocube.DeleteRecordsResponse\"\x00\x12D\n" +
	"\tCreateAOI\x12\x19.geocube.CreateAOIRequest\x1a\x1a.geocube.CreateAOIResponse\"\x00\x12;\n" +
	"\x06GetAOI\x12\x16.geocube.GetAOIRequest\x1a\x17.geocube.GetAOIResponse\"\x00\x12S\n" +
	"\x0eCreateVariable\x12\x1e.geocube.CreateVariableRequest\x1a\x1f.geocube.CreateVariableResponse\"\x00\x12J\n" +
	"\vGetVariable\x12\x1b.geocube.GetVariableRequest\x1a\x1c.geocube.GetVariableResponse\"\x00\x12S\n" +
	"\x0eUpdateVariable\x12\x1e.geocube.UpdateVariableRequest\x1a\x1f.geocube.UpdateVariableResponse\"\x00\x12S\n" +
	"\x0eDeleteVariable\x12\x1e.geocube.DeleteVariableRequest\x1a\x1f.geocube.DeleteVariableResponse\"\x00\x12V\n" +
	"\rListVariables\x12\x1d.geocube.ListVariablesRequest\x1a\".geocube.ListVariablesResponseItem\"\x000\x01\x12b\n" +
	"\x13InstantiateVariable\x12#.geocube.InstantiateVariableRequest\x1a$.geocube.InstantiateVariableResponse\"\x00\x12S\n" +
	"\x0eUpdateInstance\x12\x1e.geocube.UpdateInstanceRequest\x1a\x1f.geocube.UpdateInstanceResponse\"\x00\x12S\n" +
	"\x0eDeleteInstance\x12\x1e.geocube.DeleteInstanceRequest\x1a\x1f.geocube.DeleteInstanceResponse\"\x00\x12P\n" +
	"\rCreatePalette\x12\x1d.geocube.CreatePaletteRequest\x1a\x1e.geocube.CreatePaletteResponse\"\x00\x12P\n" +
	"\rGetContainers\x12\x1d.geocube.GetContainersRequest\x1a\x1e.geocube.GetContainersResponse\"\x00\x12P\n" +
	"\rIndexDatasets\x12\x1d.geocube.IndexDatasetsRequest\x1a\x1e.geocube.IndexDatasetsResponse\"\x00\x12M\n" +
	"\fListDatasets\x12\x1c.geocube.ListDatasetsRequest\x1a\x1d.geocube.ListDatasetsResponse\"\x00\x12S\n" +
	"\x0eDeleteDatasets\x12\x1e.geocube.DeleteDatasetsRequest\x1a\x1f.geocube.DeleteDatasetsResponse\"\x00\x12b\n" +
	"\x13ConfigConsolidation\x12#.geocube.ConfigConsolidationRequest\x1a$.geocube.ConfigConsolidationResponse\"\x00\x12k\n" +
	"\x16GetConsolidationParams\x12&.geocube.GetConsolidationParamsRequest\x1a'.geocube.GetConsolidationParamsResponse\"\x00\x12J\n" +
	"\vConsolidate\x12\x1b.geocube.ConsolidateRequest\x1a\x1c.geocube.ConsolidateResponse\"\x00\x12A\n" +
	"\bListJobs\x12\x18.geocube.ListJobsRequest\x1a\x19.geocube.ListJobsResponse\"\x00\x12;\n" +
	"\x06GetJob\x12\x16.geocube.GetJobRequest\x1a\x17.geocube.GetJobResponse\"\x00\x12D\n" +
	"\tCleanJobs\x12\x19.geocube.CleanJobsRequest\x1a\x1a.geocube.CleanJobsResponse\"\x00\x12A\n" +
	"\bRetryJob\x12\x18.geocube.RetryJobRequest\x1a\x19.geocube.RetryJobResponse\"\x00\x12D\n" +
	"\tCancelJob\x12\x19.geocube.CancelJobRequest\x1a\x1a.geocube.CancelJobResponse\"\x00\x12J\n" +
	"\vContinueJob\x12\x1b.geocube.ContinueJobRequest\x1a\x1c.geocube.ContinueJobResponse\"\x00\x12@\n" +
	"\aGetCube\x12\x17.geocube.GetCubeRequest\x1a\x18.geocube.GetCubeResponse\"\x000\x01\x12\x85\x01\n" +
	"\n" +
	"GetXYZTile\x12\x17.geocube.GetTileRequest\x1a\x18.geocube.GetTileResponse\"D\x82\xd3\xe4\x93\x02>b\n" +
	"image.data\x120/v1/catalog/mosaic/{instance_id}/{x}/{y}/{z}/png\x12M\n" +
	"\fCreateLayout\x12\x1c.geocube.CreateLayoutRequest\x1a\x1d.geocube.CreateLayoutResponse\"\x00\x12M\n" +
	"\fDeleteLayout\x12\x1c.geocube.DeleteLayoutRequest\x1a\x1d.geocube.DeleteLayoutResponse\"\x00\x12J\n" +
	"\vListLayouts\x12\x1b.geocube.ListLayoutsRequest\x1a\x1c.geocube.ListLayoutsResponse\"\x00\x12g\n" +
	"\x14FindContainerLayouts\x12$.geocube.FindContainerLayoutsRequest\x1a%.geocube.FindContainerLayoutsResponse\"\x000\x01\x12@\n" +
	"\aTileAOI\x12\x17.geocube.TileAOIRequest\x1a\x18.geocube.TileAOIResponse\"\x000\x01\x12I\n" +
	"\n" +
	"CreateGrid\x12\x1a.geocube.CreateGridRequest\x1a\x1b.geocube.CreateGridResponse\"\x00(\x01\x12G\n" +
	"\n" +
	"DeleteGrid\x12\x1a.geocube.DeleteGridRequest\x1a\x1b.geocube.DeleteGridResponse\"\x00\x12D\n" +
	"\tListGrids\x12\x19.geocube.ListGridsRequest\x1a\x1a.geocube.ListGridsResponse\"\x00\x12D\n" +
	"\aVersion\x12\x1a.geocube.GetVersionRequest\x1a\x1b.geocube.GetVersionResponse\"\x00\x12G\n" +
	"\n" +
	"GetPalette\x12\x1a.geocube.GetPaletteRequest\x1a\x1b.geocube.GetPaletteResponse\"\x00B\x0eZ\f./pb;geocubeb\x06proto3"

var file_pb_geocube_proto_goTypes = []any{
	(*CreateRecordsRequest)(nil),           // 0: geocube.CreateRecordsRequest
	(*GetRecordsRequest)(nil),              // 1: geocube.GetRecordsRequest
	(*ListRecordsRequest)(nil),             // 2: geocube.ListRecordsRequest
	(*AddRecordsTagsRequest)(nil),          // 3: geocube.AddRecordsTagsRequest
	(*RemoveRecordsTagsRequest)(nil),       // 4: geocube.RemoveRecordsTagsRequest
	(*DeleteRecordsRequest)(nil),           // 5: geocube.DeleteRecordsRequest
	(*CreateAOIRequest)(nil),               // 6: geocube.CreateAOIRequest
	(*GetAOIRequest)(nil),                  // 7: geocube.GetAOIRequest
	(*CreateVariableRequest)(nil),          // 8: geocube.CreateVariableRequest
	(*GetVariableRequest)(nil),             // 9: geocube.GetVariableRequest
	(*UpdateVariableRequest)(nil),          // 10: geocube.UpdateVariableRequest
	(*DeleteVariableRequest)(nil),          // 11: geocube.DeleteVariableRequest
	(*ListVariablesRequest)(nil),           // 12: geocube.ListVariablesRequest
	(*InstantiateVariableRequest)(nil),     // 13: geocube.InstantiateVariableRequest
	(*UpdateInstanceRequest)(nil),          // 14: geocube.UpdateInstanceRequest
	(*DeleteInstanceRequest)(nil),          // 15: geocube.DeleteInstanceRequest
	(*CreatePaletteRequest)(nil),           // 16: geocube.CreatePaletteRequest
	(*GetContainersRequest)(nil),           // 17: geocube.GetContainersRequest
	(*IndexDatasetsRequest)(nil),           // 18: geocube.IndexDatasetsRequest
	(*ListDatasetsRequest)(nil),            // 19: geocube.ListDatasetsRequest
	(*DeleteDatasetsRequest)(nil),          // 20: geocube.DeleteDatasetsRequest
	(*ConfigConsolidationRequest)(nil),     // 21: geocube.ConfigConsolidationRequest
	(*GetConsolidationParamsRequest)(nil),  // 22: geocube.GetConsolidationParamsRequest
	(*ConsolidateRequest)(nil),             // 23: geocube.ConsolidateRequest
	(*ListJobsRequest)(nil),                // 24: geocube.ListJobsRequest
	(*GetJobRequest)(nil),                  // 25: geocube.GetJobRequest
	(*CleanJobsRequest)(nil),               // 26: geocube.CleanJobsRequest
	(*RetryJobRequest)(nil),                // 27: geocube.RetryJobRequest
	(*CancelJobRequest)(nil),               // 28: geocube.CancelJobRequest
	(*ContinueJobRequest)(nil),             // 29: geocube.ContinueJobRequest
	(*GetCubeRequest)(nil),                 // 30: geocube.GetCubeRequest
	(*GetTileRequest)(nil),                 // 31: geocube.GetTileRequest
	(*CreateLayoutRequest)(nil),            // 32: geocube.CreateLayoutRequest
	(*DeleteLayoutRequest)(nil),            // 33: geocube.DeleteLayoutRequest
	(*ListLayoutsRequest)(nil),             // 34: geocube.ListLayoutsRequest
	(*FindContainerLayoutsRequest)(nil),    // 35: geocube.FindContainerLayoutsRequest
	(*TileAOIRequest)(nil),                 // 36: geocube.TileAOIRequest
	(*CreateGridRequest)(nil),              // 37: geocube.CreateGridRequest
	(*DeleteGridRequest)(nil),              // 38: geocube.DeleteGridRequest
	(*ListGridsRequest)(nil),               // 39: geocube.ListGridsRequest
	(*GetVersionRequest)(nil),              // 40: geocube.GetVersionRequest
	(*GetPaletteRequest)(nil),              // 41: geocube.GetPaletteRequest
	(*CreateRecordsResponse)(nil),          // 42: geocube.CreateRecordsResponse
	(*GetRecordsResponseItem)(nil),         // 43: geocube.GetRecordsResponseItem
	(*ListRecordsResponseItem)(nil),        // 44: geocube.ListRecordsResponseItem
	(*AddRecordsTagsResponse)(nil),         // 45: geocube.AddRecordsTagsResponse
	(*RemoveRecordsTagsResponse)(nil),      // 46: geocube.RemoveRecordsTagsResponse
	(*DeleteRecordsResponse)(nil),          // 47: geocube.DeleteRecordsResponse
	(*CreateAOIResponse)(nil),              // 48: geocube.CreateAOIResponse
	(*GetAOIResponse)(nil),                 // 49: geocube.GetAOIResponse
	(*CreateVariableResponse)(nil),         // 50: geocube.CreateVariableResponse
	(*GetVariableResponse)(nil),            // 51: geocube.GetVariableResponse
	(*UpdateVariableResponse)(nil),         // 52: geocube.UpdateVariableResponse
	(*DeleteVariableResponse)(nil),         // 53: geocube.DeleteVariableResponse
	(*ListVariablesResponseItem)(nil),      // 54: geocube.ListVariablesResponseItem
	(*InstantiateVariableResponse)(nil),    // 55: geocube.InstantiateVariableResponse
	(*UpdateInstanceResponse)(nil),         // 56: geocube.UpdateInstanceResponse
	(*DeleteInstanceResponse)(nil),         // 57: geocube.DeleteInstanceResponse
	(*CreatePaletteResponse)(nil),          // 58: geocube.CreatePaletteResponse
	(*GetContainersResponse)(nil),          // 59: geocube.GetContainersResponse
	(*IndexDatasetsResponse)(nil),          // 60: geocube.IndexDatasetsResponse
	(*ListDatasetsResponse)(nil),           // 61: geocube.ListDatasetsResponse
	(*DeleteDatasetsResponse)(nil),         // 62: geocube.DeleteDatasetsResponse
	(*ConfigConsolidationResponse)(nil),    // 63: geocube.ConfigConsolidationResponse
	(*GetConsolidationParamsResponse)(nil), // 64: geocube.GetConsolidationParamsResponse
	(*ConsolidateResponse)(nil),            // 65: geocube.ConsolidateResponse
	(*ListJobsResponse)(nil),               // 66: geocube.ListJobsResponse
	(*GetJobResponse)(nil),                 // 67: geocube.GetJobResponse
	(*CleanJobsResponse)(nil),              // 68: geocube.CleanJobsResponse
	(*RetryJobResponse)(nil),               // 69: geocube.RetryJobResponse
	(*CancelJobResponse)(nil),              // 70: geocube.CancelJobResponse
	(*ContinueJobResponse)(nil),            // 71: geocube.ContinueJobResponse
	(*GetCubeResponse)(nil),                // 72: geocube.GetCubeResponse
	(*GetTileResponse)(nil),                // 73: geocube.GetTileResponse
	(*CreateLayoutResponse)(nil),           // 74: geocube.CreateLayoutResponse
	(*DeleteLayoutResponse)(nil),           // 75: geocube.DeleteLayoutResponse
	(*ListLayoutsResponse)(nil),            // 76: geocube.ListLayoutsResponse
	(*FindContainerLayoutsResponse)(nil),   // 77: geocube.FindContainerLayoutsResponse
	(*TileAOIResponse)(nil),                // 78: geocube.TileAOIResponse
	(*CreateGridResponse)(nil),             // 79: geocube.CreateGridResponse
	(*DeleteGridResponse)(nil),             // 80: geocube.DeleteGridResponse
	(*ListGridsResponse)(nil),              // 81: geocube.ListGridsResponse
	(*GetVersionResponse)(nil),             // 82: geocube.GetVersionResponse
	(*GetPaletteResponse)(nil),             // 83: geocube.GetPaletteResponse
}
var file_pb_geocube_proto_depIdxs = []int32{
	0,  // 0: geocube.Geocube.CreateRecords:input_type -> geocube.CreateRecordsRequest
	1,  // 1: geocube.Geocube.GetRecords:input_type -> geocube.GetRecordsRequest
	2,  // 2: geocube.Geocube.ListRecords:input_type -> geocube.ListRecordsRequest
	3,  // 3: geocube.Geocube.AddRecordsTags:input_type -> geocube.AddRecordsTagsRequest
	4,  // 4: geocube.Geocube.RemoveRecordsTags:input_type -> geocube.RemoveRecordsTagsRequest
	5,  // 5: geocube.Geocube.DeleteRecords:input_type -> geocube.DeleteRecordsRequest
	6,  // 6: geocube.Geocube.CreateAOI:input_type -> geocube.CreateAOIRequest
	7,  // 7: geocube.Geocube.GetAOI:input_type -> geocube.GetAOIRequest
	8,  // 8: geocube.Geocube.CreateVariable:input_type -> geocube.CreateVariableRequest
	9,  // 9: geocube.Geocube.GetVariable:input_type -> geocube.GetVariableRequest
	10, // 10: geocube.Geocube.UpdateVariable:input_type -> geocube.UpdateVariableRequest
	11, // 11: geocube.Geocube.DeleteVariable:input_type -> geocube.DeleteVariableRequest
	12, // 12: geocube.Geocube.ListVariables:input_type -> geocube.ListVariablesRequest
	13, // 13: geocube.Geocube.InstantiateVariable:input_type -> geocube.InstantiateVariableRequest
	14, // 14: geocube.Geocube.UpdateInstance:input_type -> geocube.UpdateInstanceRequest
	15, // 15: geocube.Geocube.DeleteInstance:input_type -> geocube.DeleteInstanceRequest
	16, // 16: geocube.Geocube.CreatePalette:input_type -> geocube.CreatePaletteRequest
	17, // 17: geocube.Geocube.GetContainers:input_type -> geocube.GetContainersRequest
	18, // 18: geocube.Geocube.IndexDatasets:input_type -> geocube.IndexDatasetsRequest
	19, // 19: geocube.Geocube.ListDatasets:input_type -> geocube.ListDatasetsRequest
	20, // 20: geocube.Geocube.DeleteDatasets:input_type -> geocube.DeleteDatasetsRequest
	21, // 21: geocube.Geocube.ConfigConsolidation:input_type -> geocube.ConfigConsolidationRequest
	22, // 22: geocube.Geocube.GetConsolidationParams:input_type -> geocube.GetConsolidationParamsRequest
	23, // 23: geocube.Geocube.Consolidate:input_type -> geocube.ConsolidateRequest
	24, // 24: geocube.Geocube.ListJobs:input_type -> geocube.ListJobsRequest
	25, // 25: geocube.Geocube.GetJob:input_type -> geocube.GetJobRequest
	26, // 26: geocube.Geocube.CleanJobs:input_type -> geocube.CleanJobsRequest
	27, // 27: geocube.Geocube.RetryJob:input_type -> geocube.RetryJobRequest
	28, // 28: geocube.Geocube.CancelJob:input_type -> geocube.CancelJobRequest
	29, // 29: geocube.Geocube.ContinueJob:input_type -> geocube.ContinueJobRequest
	30, // 30: geocube.Geocube.GetCube:input_type -> geocube.GetCubeRequest
	31, // 31: geocube.Geocube.GetXYZTile:input_type -> geocube.GetTileRequest
	32, // 32: geocube.Geocube.CreateLayout:input_type -> geocube.CreateLayoutRequest
	33, // 33: geocube.Geocube.DeleteLayout:input_type -> geocube.DeleteLayoutRequest
	34, // 34: geocube.Geocube.ListLayouts:input_type -> geocube.ListLayoutsRequest
	35, // 35: geocube.Geocube.FindContainerLayouts:input_type -> geocube.FindContainerLayoutsRequest
	36, // 36: geocube.Geocube.TileAOI:input_type -> geocube.TileAOIRequest
	37, // 37: geocube.Geocube.CreateGrid:input_type -> geocube.CreateGridRequest
	38, // 38: geocube.Geocube.DeleteGrid:input_type -> geocube.DeleteGridRequest
	39, // 39: geocube.Geocube.ListGrids:input_type -> geocube.ListGridsRequest
	40, // 40: geocube.Geocube.Version:input_type -> geocube.GetVersionRequest
	41, // 41: geocube.Geocube.GetPalette:input_type -> geocube.GetPaletteRequest
	42, // 42: geocube.Geocube.CreateRecords:output_type -> geocube.CreateRecordsResponse
	43, // 43: geocube.Geocube.GetRecords:output_type -> geocube.GetRecordsResponseItem
	44, // 44: geocube.Geocube.ListRecords:output_type -> geocube.ListRecordsResponseItem
	45, // 45: geocube.Geocube.AddRecordsTags:output_type -> geocube.AddRecordsTagsResponse
	46, // 46: geocube.Geocube.RemoveRecordsTags:output_type -> geocube.RemoveRecordsTagsResponse
	47, // 47: geocube.Geocube.DeleteRecords:output_type -> geocube.DeleteRecordsResponse
	48, // 48: geocube.Geocube.CreateAOI:output_type -> geocube.CreateAOIResponse
	49, // 49: geocube.Geocube.GetAOI:output_type -> geocube.GetAOIResponse
	50, // 50: geocube.Geocube.CreateVariable:output_type -> geocube.CreateVariableResponse
	51, // 51: geocube.Geocube.GetVariable:output_type -> geocube.GetVariableResponse
	52, // 52: geocube.Geocube.UpdateVariable:output_type -> geocube.UpdateVariableResponse
	53, // 53: geocube.Geocube.DeleteVariable:output_type -> geocube.DeleteVariableResponse
	54, // 54: geocube.Geocube.ListVariables:output_type -> geocube.ListVariablesResponseItem
	55, // 55: geocube.Geocube.InstantiateVariable:output_type -> geocube.InstantiateVariableResponse
	56, // 56: geocube.Geocube.UpdateInstance:output_type -> geocube.UpdateInstanceResponse
	57, // 57: geocube.Geocube.DeleteInstance:output_type -> geocube.DeleteInstanceResponse
	58, // 58: geocube.Geocube.CreatePalette:output_type -> geocube.CreatePaletteResponse
	59, // 59: geocube.Geocube.GetContainers:output_type -> geocube.GetContainersResponse
	60, // 60: geocube.Geocube.IndexDatasets:output_type -> geocube.IndexDatasetsResponse
	61, // 61: geocube.Geocube.ListDatasets:output_type -> geocube.ListDatasetsResponse
	62, // 62: geocube.Geocube.DeleteDatasets:output_type -> geocube.DeleteDatasetsResponse
	63, // 63: geocube.Geocube.ConfigConsolidation:output_type -> geocube.ConfigConsolidationResponse
	64, // 64: geocube.Geocube.GetConsolidationParams:output_type -> geocube.GetConsolidationParamsResponse
	65, // 65: geocube.Geocube.Consolidate:output_type -> geocube.ConsolidateResponse
	66, // 66: geocube.Geocube.ListJobs:output_type -> geocube.ListJobsResponse
	67, // 67: geocube.Geocube.GetJob:output_type -> geocube.GetJobResponse
	68, // 68: geocube.Geocube.CleanJobs:output_type -> geocube.CleanJobsResponse
	69, // 69: geocube.Geocube.RetryJob:output_type -> geocube.RetryJobResponse
	70, // 70: geocube.Geocube.CancelJob:output_type -> geocube.CancelJobResponse
	71, // 71: geocube.Geocube.ContinueJob:output_type -> geocube.ContinueJobResponse
	72, // 72: geocube.Geocube.GetCube:output_type -> geocube.GetCubeResponse
	73, // 73: geocube.Geocube.GetXYZTile:output_type -> geocube.GetTileResponse
	74, // 74: geocube.Geocube.CreateLayout:output_type -> geocube.CreateLayoutResponse
	75, // 75: geocube.Geocube.DeleteLayout:output_type -> geocube.DeleteLayoutResponse
	76, // 76: geocube.Geocube.ListLayouts:output_type -> geocube.ListLayoutsResponse
	77, // 77: geocube.Geocube.FindContainerLayouts:output_type -> geocube.FindContainerLayoutsResponse
	78, // 78: geocube.Geocube.TileAOI:output_type -> geocube.TileAOIResponse
	79, // 79: geocube.Geocube.CreateGrid:output_type -> geocube.CreateGridResponse
	80, // 80: geocube.Geocube.DeleteGrid:output_type -> geocube.DeleteGridResponse
	81, // 81: geocube.Geocube.ListGrids:output_type -> geocube.ListGridsResponse
	82, // 82: geocube.Geocube.Version:output_type -> geocube.GetVersionResponse
	83, // 83: geocube.Geocube.GetPalette:output_type -> geocube.GetPaletteResponse
	42, // [42:84] is the sub-list for method output_type
	0,  // [0:42] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pb_geocube_proto_init() }
func file_pb_geocube_proto_init() {
	if File_pb_geocube_proto != nil {
		return
	}
	file_pb_version_proto_init()
	file_pb_catalog_proto_init()
	file_pb_records_proto_init()
	file_pb_variables_proto_init()
	file_pb_layouts_proto_init()
	file_pb_operations_proto_init()
	file_pb_palettes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_geocube_proto_rawDesc), len(file_pb_geocube_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_geocube_proto_goTypes,
		DependencyIndexes: file_pb_geocube_proto_depIdxs,
	}.Build()
	File_pb_geocube_proto = out.File
	file_pb_geocube_proto_goTypes = nil
	file_pb_geocube_proto_depIdxs = nil
}
