// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/layouts.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Define a size
type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_pb_layouts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{0}
}

func (x *Size) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Size) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// *
// GDAL GeoTransform
type GeoTransform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"` // x offset
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"` // x resolution
	C             float64                `protobuf:"fixed64,3,opt,name=c,proto3" json:"c,omitempty"`
	D             float64                `protobuf:"fixed64,4,opt,name=d,proto3" json:"d,omitempty"` // y offset
	E             float64                `protobuf:"fixed64,5,opt,name=e,proto3" json:"e,omitempty"`
	F             float64                `protobuf:"fixed64,6,opt,name=f,proto3" json:"f,omitempty"` // y resolution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoTransform) Reset() {
	*x = GeoTransform{}
	mi := &file_pb_layouts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoTransform) ProtoMessage() {}

func (x *GeoTransform) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoTransform.ProtoReflect.Descriptor instead.
func (*GeoTransform) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{1}
}

func (x *GeoTransform) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *GeoTransform) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *GeoTransform) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *GeoTransform) GetD() float64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *GeoTransform) GetE() float64 {
	if x != nil {
		return x.E
	}
	return 0
}

func (x *GeoTransform) GetF() float64 {
	if x != nil {
		return x.F
	}
	return 0
}

// *
// Define a rectangular tile in a given coordinate system (CRS).
type Tile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transform     *GeoTransform          `protobuf:"bytes,1,opt,name=transform,proto3" json:"transform,omitempty"`         // Transform to map from pixel coordinates to CRS
	SizePx        *Size                  `protobuf:"bytes,2,opt,name=size_px,json=sizePx,proto3" json:"size_px,omitempty"` // Size of the tile in pixel
	Crs           string                 `protobuf:"bytes,3,opt,name=crs,proto3" json:"crs,omitempty"`                     // Coordinate reference system
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_pb_layouts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{2}
}

func (x *Tile) GetTransform() *GeoTransform {
	if x != nil {
		return x.Transform
	}
	return nil
}

func (x *Tile) GetSizePx() *Size {
	if x != nil {
		return x.SizePx
	}
	return nil
}

func (x *Tile) GetCrs() string {
	if x != nil {
		return x.Crs
	}
	return ""
}

// *
// Define a layout for consolidation. A layout is composed of an external and an internal layout.
// External layout is a grid that is used to cover any area with tiles.
// TODO Internal layout defines the internal structure of a dataset
//
// Interlacing_pattern defines how to interlace the [R]ecords, the [B]ands, the [Z]ooms level/overview and the [T]iles (geotiff blocks).
// The four levels of interlacing must be prioritized in the following way L1>L2>L3>L4 where each L is in [R, B, Z, T]. This order should be understood as:
// for each L1:
//
//	for each L2:
//	  for each L3:
//	    for each L4:
//	      addBlock(L1, L2, L3, L4)
//
// In other words, all L4 for a given (L1, L2, L3) will be contiguous in memory.
// For example:
// - To optimize the access to geographical information of all the bands (such as in COG) : R>Z>T>B  => For a given record, zoom level and block, all the bands will be contiguous.
// - To optimize the access to geographical information of one band at a time : B>R>Z>T => For a given band, record and zoom, all the blocks will be contiguous.
// - To optimize the access to timeseries of all the bands (such as in MUCOG): Z>T>R>B => For a given zoom level and block, all the records will be contiguous.
//
// Interlacing pattern can be specialized to only select a list or a range for each level (except Tile level).
// - By values: L=0,2,3 will only select the value 0, 2 and 3 of the level L. For example B=0,2,3 to select the corresponding band level.
// - By range: L=0:3 will only select the values from 0 to 3 (not included) of the level L. For example B=0:3 to select the three firsts bands.
// First and last values of the range can be omitted to define 0 or last element of the level. e.g B=2: means all the bands from the second.
// Z=0 is the full resolution, Z=1 is the overview with zoom factor 2, Z=2 is the zoom factor 4, and so on.
//
// To chain interlacing patterns, use ";" separator.
//
// For example:
// - MUCOG optimizes access to timeseries for full resolution (Z=0), but geographic for overviews (Z=1:). Z=0>T>R>B;Z=1:>R>T>B
// - Same example, but the bands are separated: B>Z=0>T>R;B>Z=1:>R>T
// - To optimize access to geographic information of the three first bands together, but timeseries of the others: Z>T>R>B=0:3;B=3:>Z>R>T
type Layout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// External layout: Grid:Cell (CRS)
	GridFlags      []string          `protobuf:"bytes,3,rep,name=grid_flags,json=gridFlags,proto3" json:"grid_flags,omitempty"`
	GridParameters map[string]string `protobuf:"bytes,4,rep,name=grid_parameters,json=gridParameters,proto3" json:"grid_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Internal layout: Cell, Tile
	BlockXSize         int64  `protobuf:"varint,5,opt,name=block_x_size,json=blockXSize,proto3" json:"block_x_size,omitempty"`
	BlockYSize         int64  `protobuf:"varint,6,opt,name=block_y_size,json=blockYSize,proto3" json:"block_y_size,omitempty"`
	MaxRecords         int64  `protobuf:"varint,7,opt,name=max_records,json=maxRecords,proto3" json:"max_records,omitempty"`
	OverviewsMinSize   int64  `protobuf:"varint,8,opt,name=overviews_min_size,json=overviewsMinSize,proto3" json:"overviews_min_size,omitempty"`    // Maximum width or height of the smallest overview level. 0: No overview, -1: default=256.
	InterlacingPattern string `protobuf:"bytes,9,opt,name=interlacing_pattern,json=interlacingPattern,proto3" json:"interlacing_pattern,omitempty"` // Define how to interlace the [R]ecords, the [B]ands, the [Z]ooms level/overview and the [T]iles (geotiff blocks).
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Layout) Reset() {
	*x = Layout{}
	mi := &file_pb_layouts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layout) ProtoMessage() {}

func (x *Layout) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layout.ProtoReflect.Descriptor instead.
func (*Layout) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{3}
}

func (x *Layout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Layout) GetGridFlags() []string {
	if x != nil {
		return x.GridFlags
	}
	return nil
}

func (x *Layout) GetGridParameters() map[string]string {
	if x != nil {
		return x.GridParameters
	}
	return nil
}

func (x *Layout) GetBlockXSize() int64 {
	if x != nil {
		return x.BlockXSize
	}
	return 0
}

func (x *Layout) GetBlockYSize() int64 {
	if x != nil {
		return x.BlockYSize
	}
	return 0
}

func (x *Layout) GetMaxRecords() int64 {
	if x != nil {
		return x.MaxRecords
	}
	return 0
}

func (x *Layout) GetOverviewsMinSize() int64 {
	if x != nil {
		return x.OverviewsMinSize
	}
	return 0
}

func (x *Layout) GetInterlacingPattern() string {
	if x != nil {
		return x.InterlacingPattern
	}
	return ""
}

// *
// Create a new layout
// Return an error if the name already exists
type CreateLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layout        *Layout                `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLayoutRequest) Reset() {
	*x = CreateLayoutRequest{}
	mi := &file_pb_layouts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLayoutRequest) ProtoMessage() {}

func (x *CreateLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLayoutRequest.ProtoReflect.Descriptor instead.
func (*CreateLayoutRequest) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLayoutRequest) GetLayout() *Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

// *
type CreateLayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLayoutResponse) Reset() {
	*x = CreateLayoutResponse{}
	mi := &file_pb_layouts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLayoutResponse) ProtoMessage() {}

func (x *CreateLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLayoutResponse.ProtoReflect.Descriptor instead.
func (*CreateLayoutResponse) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{5}
}

// *
// Delete a layout by name
type DeleteLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLayoutRequest) Reset() {
	*x = DeleteLayoutRequest{}
	mi := &file_pb_layouts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLayoutRequest) ProtoMessage() {}

func (x *DeleteLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLayoutRequest.ProtoReflect.Descriptor instead.
func (*DeleteLayoutRequest) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLayoutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// *
type DeleteLayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLayoutResponse) Reset() {
	*x = DeleteLayoutResponse{}
	mi := &file_pb_layouts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLayoutResponse) ProtoMessage() {}

func (x *DeleteLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLayoutResponse.ProtoReflect.Descriptor instead.
func (*DeleteLayoutResponse) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{7}
}

// *
// List all the layouts given a name pattern
type ListLayoutsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameLike      string                 `protobuf:"bytes,1,opt,name=name_like,json=nameLike,proto3" json:"name_like,omitempty"` // Name pattern (support * and ? for all or any characters and trailing (?i) for case-insensitiveness)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLayoutsRequest) Reset() {
	*x = ListLayoutsRequest{}
	mi := &file_pb_layouts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLayoutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayoutsRequest) ProtoMessage() {}

func (x *ListLayoutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayoutsRequest.ProtoReflect.Descriptor instead.
func (*ListLayoutsRequest) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{8}
}

func (x *ListLayoutsRequest) GetNameLike() string {
	if x != nil {
		return x.NameLike
	}
	return ""
}

// *
// Return a list of layouts
type ListLayoutsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layouts       []*Layout              `protobuf:"bytes,1,rep,name=layouts,proto3" json:"layouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLayoutsResponse) Reset() {
	*x = ListLayoutsResponse{}
	mi := &file_pb_layouts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLayoutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayoutsResponse) ProtoMessage() {}

func (x *ListLayoutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayoutsResponse.ProtoReflect.Descriptor instead.
func (*ListLayoutsResponse) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{9}
}

func (x *ListLayoutsResponse) GetLayouts() []*Layout {
	if x != nil {
		return x.Layouts
	}
	return nil
}

// *
// Find all the layouts used by the datasets on an AOI or a set of records
// It can be used to tile the AOI with an optimal layout.
type FindContainerLayoutsRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*FindContainerLayoutsRequest_Records
	//	*FindContainerLayoutsRequest_Filters
	Identifier    isFindContainerLayoutsRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindContainerLayoutsRequest) Reset() {
	*x = FindContainerLayoutsRequest{}
	mi := &file_pb_layouts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindContainerLayoutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindContainerLayoutsRequest) ProtoMessage() {}

func (x *FindContainerLayoutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindContainerLayoutsRequest.ProtoReflect.Descriptor instead.
func (*FindContainerLayoutsRequest) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{10}
}

func (x *FindContainerLayoutsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *FindContainerLayoutsRequest) GetIdentifier() isFindContainerLayoutsRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *FindContainerLayoutsRequest) GetRecords() *RecordIdList {
	if x != nil {
		if x, ok := x.Identifier.(*FindContainerLayoutsRequest_Records); ok {
			return x.Records
		}
	}
	return nil
}

func (x *FindContainerLayoutsRequest) GetFilters() *RecordFiltersWithAOI {
	if x != nil {
		if x, ok := x.Identifier.(*FindContainerLayoutsRequest_Filters); ok {
			return x.Filters
		}
	}
	return nil
}

type isFindContainerLayoutsRequest_Identifier interface {
	isFindContainerLayoutsRequest_Identifier()
}

type FindContainerLayoutsRequest_Records struct {
	Records *RecordIdList `protobuf:"bytes,2,opt,name=records,proto3,oneof"` // List of record ids
}

type FindContainerLayoutsRequest_Filters struct {
	Filters *RecordFiltersWithAOI `protobuf:"bytes,3,opt,name=filters,proto3,oneof"` // Filters to select records
}

func (*FindContainerLayoutsRequest_Records) isFindContainerLayoutsRequest_Identifier() {}

func (*FindContainerLayoutsRequest_Filters) isFindContainerLayoutsRequest_Identifier() {}

// *
// Stream the name of the layout and the associated containers
type FindContainerLayoutsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LayoutName    string                 `protobuf:"bytes,1,opt,name=layout_name,json=layoutName,proto3" json:"layout_name,omitempty"`          // Name of the layout
	ContainerUris []string               `protobuf:"bytes,2,rep,name=container_uris,json=containerUris,proto3" json:"container_uris,omitempty"` // List of containers having the layout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindContainerLayoutsResponse) Reset() {
	*x = FindContainerLayoutsResponse{}
	mi := &file_pb_layouts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindContainerLayoutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindContainerLayoutsResponse) ProtoMessage() {}

func (x *FindContainerLayoutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindContainerLayoutsResponse.ProtoReflect.Descriptor instead.
func (*FindContainerLayoutsResponse) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{11}
}

func (x *FindContainerLayoutsResponse) GetLayoutName() string {
	if x != nil {
		return x.LayoutName
	}
	return ""
}

func (x *FindContainerLayoutsResponse) GetContainerUris() []string {
	if x != nil {
		return x.ContainerUris
	}
	return nil
}

// *
// Tile an AOI, covering it with cells defined by a grid.
// In the future, it will be able to find the best tiling given the internal layout of datasets.
type TileAOIRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Aoi   *AOI                   `protobuf:"bytes,1,opt,name=aoi,proto3" json:"aoi,omitempty"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*TileAOIRequest_LayoutName
	//	*TileAOIRequest_Layout
	Identifier    isTileAOIRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TileAOIRequest) Reset() {
	*x = TileAOIRequest{}
	mi := &file_pb_layouts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileAOIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileAOIRequest) ProtoMessage() {}

func (x *TileAOIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileAOIRequest.ProtoReflect.Descriptor instead.
func (*TileAOIRequest) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{12}
}

func (x *TileAOIRequest) GetAoi() *AOI {
	if x != nil {
		return x.Aoi
	}
	return nil
}

func (x *TileAOIRequest) GetIdentifier() isTileAOIRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *TileAOIRequest) GetLayoutName() string {
	if x != nil {
		if x, ok := x.Identifier.(*TileAOIRequest_LayoutName); ok {
			return x.LayoutName
		}
	}
	return ""
}

func (x *TileAOIRequest) GetLayout() *Layout {
	if x != nil {
		if x, ok := x.Identifier.(*TileAOIRequest_Layout); ok {
			return x.Layout
		}
	}
	return nil
}

type isTileAOIRequest_Identifier interface {
	isTileAOIRequest_Identifier()
}

type TileAOIRequest_LayoutName struct {
	LayoutName string `protobuf:"bytes,5,opt,name=layout_name,json=layoutName,proto3,oneof"` // Name of an existing layout
}

type TileAOIRequest_Layout struct {
	Layout *Layout `protobuf:"bytes,6,opt,name=layout,proto3,oneof"` // User-defined layout
}

func (*TileAOIRequest_LayoutName) isTileAOIRequest_Identifier() {}

func (*TileAOIRequest_Layout) isTileAOIRequest_Identifier() {}

// *
// Return tiles, thousand by thousand.
type TileAOIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tiles         []*Tile                `protobuf:"bytes,1,rep,name=tiles,proto3" json:"tiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TileAOIResponse) Reset() {
	*x = TileAOIResponse{}
	mi := &file_pb_layouts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileAOIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileAOIResponse) ProtoMessage() {}

func (x *TileAOIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileAOIResponse.ProtoReflect.Descriptor instead.
func (*TileAOIResponse) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{13}
}

func (x *TileAOIResponse) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

// *
// Define a grid
type Grid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Unique name of the grid
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Description of the grid
	Cells         []*Cell                `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`             // Cells of the grid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid) Reset() {
	*x = Grid{}
	mi := &file_pb_layouts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid) ProtoMessage() {}

func (x *Grid) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid.ProtoReflect.Descriptor instead.
func (*Grid) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{14}
}

func (x *Grid) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Grid) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Grid) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

// *
// Define a cell of a grid
type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // Cell identifier
	Crs           string                 `protobuf:"bytes,2,opt,name=crs,proto3" json:"crs,omitempty"`                 // Coordinate reference system used in the cell
	Coordinates   *LinearRing            `protobuf:"bytes,3,opt,name=coordinates,proto3" json:"coordinates,omitempty"` // Geographic coordinates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_pb_layouts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{15}
}

func (x *Cell) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cell) GetCrs() string {
	if x != nil {
		return x.Crs
	}
	return ""
}

func (x *Cell) GetCoordinates() *LinearRing {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

// *
// Create a new grid.
type CreateGridRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grid          *Grid                  `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGridRequest) Reset() {
	*x = CreateGridRequest{}
	mi := &file_pb_layouts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGridRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGridRequest) ProtoMessage() {}

func (x *CreateGridRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGridRequest.ProtoReflect.Descriptor instead.
func (*CreateGridRequest) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{16}
}

func (x *CreateGridRequest) GetGrid() *Grid {
	if x != nil {
		return x.Grid
	}
	return nil
}

// *
type CreateGridResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGridResponse) Reset() {
	*x = CreateGridResponse{}
	mi := &file_pb_layouts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGridResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGridResponse) ProtoMessage() {}

func (x *CreateGridResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGridResponse.ProtoReflect.Descriptor instead.
func (*CreateGridResponse) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{17}
}

// *
// Delete a grid
type DeleteGridRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGridRequest) Reset() {
	*x = DeleteGridRequest{}
	mi := &file_pb_layouts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGridRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGridRequest) ProtoMessage() {}

func (x *DeleteGridRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGridRequest.ProtoReflect.Descriptor instead.
func (*DeleteGridRequest) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteGridRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// *
type DeleteGridResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGridResponse) Reset() {
	*x = DeleteGridResponse{}
	mi := &file_pb_layouts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGridResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGridResponse) ProtoMessage() {}

func (x *DeleteGridResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGridResponse.ProtoReflect.Descriptor instead.
func (*DeleteGridResponse) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{19}
}

// *
// List all the grids given a name pattern (does not retrieve the cells)
type ListGridsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameLike      string                 `protobuf:"bytes,1,opt,name=name_like,json=nameLike,proto3" json:"name_like,omitempty"` // Name pattern (support * and ? for all or any characters and trailing (?i) for case-insensitiveness)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGridsRequest) Reset() {
	*x = ListGridsRequest{}
	mi := &file_pb_layouts_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGridsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGridsRequest) ProtoMessage() {}

func (x *ListGridsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGridsRequest.ProtoReflect.Descriptor instead.
func (*ListGridsRequest) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{20}
}

func (x *ListGridsRequest) GetNameLike() string {
	if x != nil {
		return x.NameLike
	}
	return ""
}

// *
// Return a list of grids
type ListGridsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grids         []*Grid                `protobuf:"bytes,1,rep,name=grids,proto3" json:"grids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGridsResponse) Reset() {
	*x = ListGridsResponse{}
	mi := &file_pb_layouts_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGridsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGridsResponse) ProtoMessage() {}

func (x *ListGridsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_layouts_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGridsResponse.ProtoReflect.Descriptor instead.
func (*ListGridsResponse) Descriptor() ([]byte, []int) {
	return file_pb_layouts_proto_rawDescGZIP(), []int{21}
}

func (x *ListGridsResponse) GetGrids() []*Grid {
	if x != nil {
		return x.Grids
	}
	return nil
}

var File_pb_layouts_proto protoreflect.FileDescriptor

const file_pb_layouts_proto_rawDesc = "" +
	"\n" +
	"\x10pb/layouts.proto\x12\ageocube\x1a\x10pb/records.proto\"4\n" +
	"\x04Size\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"b\n" +
	"\fGeoTransform\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\x12\f\n" +
	"\x01c\x18\x03 \x01(\x01R\x01c\x12\f\n" +
	"\x01d\x18\x04 \x01(\x01R\x01d\x12\f\n" +
	"\x01e\x18\x05 \x01(\x01R\x01e\x12\f\n" +
	"\x01f\x18\x06 \x01(\x01R\x01f\"u\n" +
	"\x04Tile\x123\n" +
	"\ttransform\x18\x01 \x01(\v2\x15.geocube.GeoTransformR\ttransform\x12&\n" +
	"\asize_px\x18\x02 \x01(\v2\r.geocube.SizeR\x06sizePx\x12\x10\n" +
	"\x03crs\x18\x03 \x01(\tR\x03crs\"\x90\x03\n" +
	"\x06Layout\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"grid_flags\x18\x03 \x03(\tR\tgridFlags\x12L\n" +
	"\x0fgrid_parameters\x18\x04 \x03(\v2#.geocube.Layout.GridParametersEntryR\x0egridParameters\x12 \n" +
	"\fblock_x_size\x18\x05 \x01(\x03R\n" +
	"blockXSize\x12 \n" +
	"\fblock_y_size\x18\x06 \x01(\x03R\n" +
	"blockYSize\x12\x1f\n" +
	"\vmax_records\x18\a \x01(\x03R\n" +
	"maxRecords\x12,\n" +
	"\x12overviews_min_size\x18\b \x01(\x03R\x10overviewsMinSize\x12/\n" +
	"\x13interlacing_pattern\x18\t \x01(\tR\x12interlacingPattern\x1aA\n" +
	"\x13GridParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x13CreateLayoutRequest\x12'\n" +
	"\x06layout\x18\x01 \x01(\v2\x0f.geocube.LayoutR\x06layout\"\x16\n" +
	"\x14CreateLayoutResponse\")\n" +
	"\x13DeleteLayoutRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteLayoutResponse\"1\n" +
	"\x12ListLayoutsRequest\x12\x1b\n" +
	"\tname_like\x18\x01 \x01(\tR\bnameLike\"@\n" +
	"\x13ListLayoutsResponse\x12)\n" +
	"\alayouts\x18\x01 \x03(\v2\x0f.geocube.LayoutR\alayouts\"\xba\x01\n" +
	"\x1bFindContainerLayoutsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x121\n" +
	"\arecords\x18\x02 \x01(\v2\x15.geocube.RecordIdListH\x00R\arecords\x129\n" +
	"\afilters\x18\x03 \x01(\v2\x1d.geocube.RecordFiltersWithAOIH\x00R\afiltersB\f\n" +
	"\n" +
	"identifier\"f\n" +
	"\x1cFindContainerLayoutsResponse\x12\x1f\n" +
	"\vlayout_name\x18\x01 \x01(\tR\n" +
	"layoutName\x12%\n" +
	"\x0econtainer_uris\x18\x02 \x03(\tR\rcontainerUris\"\x8c\x01\n" +
	"\x0eTileAOIRequest\x12\x1e\n" +
	"\x03aoi\x18\x01 \x01(\v2\f.geocube.AOIR\x03aoi\x12!\n" +
	"\vlayout_name\x18\x05 \x01(\tH\x00R\n" +
	"layoutName\x12)\n" +
	"\x06layout\x18\x06 \x01(\v2\x0f.geocube.LayoutH\x00R\x06layoutB\f\n" +
	"\n" +
	"identifier\"6\n" +
	"\x0fTileAOIResponse\x12#\n" +
	"\x05tiles\x18\x01 \x03(\v2\r.geocube.TileR\x05tiles\"a\n" +
	"\x04Grid\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\x05cells\x18\x03 \x03(\v2\r.geocube.CellR\x05cells\"_\n" +
	"\x04Cell\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03crs\x18\x02 \x01(\tR\x03crs\x125\n" +
	"\vcoordinates\x18\x03 \x01(\v2\x13.geocube.LinearRingR\vcoordinates\"6\n" +
	"\x11CreateGridRequest\x12!\n" +
	"\x04grid\x18\x01 \x01(\v2\r.geocube.GridR\x04grid\"\x14\n" +
	"\x12CreateGridResponse\"'\n" +
	"\x11DeleteGridRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12DeleteGridResponse\"/\n" +
	"\x10ListGridsRequest\x12\x1b\n" +
	"\tname_like\x18\x01 \x01(\tR\bnameLike\"8\n" +
	"\x11ListGridsResponse\x12#\n" +
	"\x05grids\x18\x01 \x03(\v2\r.geocube.GridR\x05gridsB\x0eZ\f./pb;geocubeb\x06proto3"

var (
	file_pb_layouts_proto_rawDescOnce sync.Once
	file_pb_layouts_proto_rawDescData []byte
)

func file_pb_layouts_proto_rawDescGZIP() []byte {
	file_pb_layouts_proto_rawDescOnce.Do(func() {
		file_pb_layouts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_layouts_proto_rawDesc), len(file_pb_layouts_proto_rawDesc)))
	})
	return file_pb_layouts_proto_rawDescData
}

var file_pb_layouts_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pb_layouts_proto_goTypes = []any{
	(*Size)(nil),                         // 0: geocube.Size
	(*GeoTransform)(nil),                 // 1: geocube.GeoTransform
	(*Tile)(nil),                         // 2: geocube.Tile
	(*Layout)(nil),                       // 3: geocube.Layout
	(*CreateLayoutRequest)(nil),          // 4: geocube.CreateLayoutRequest
	(*CreateLayoutResponse)(nil),         // 5: geocube.CreateLayoutResponse
	(*DeleteLayoutRequest)(nil),          // 6: geocube.DeleteLayoutRequest
	(*DeleteLayoutResponse)(nil),         // 7: geocube.DeleteLayoutResponse
	(*ListLayoutsRequest)(nil),           // 8: geocube.ListLayoutsRequest
	(*ListLayoutsResponse)(nil),          // 9: geocube.ListLayoutsResponse
	(*FindContainerLayoutsRequest)(nil),  // 10: geocube.FindContainerLayoutsRequest
	(*FindContainerLayoutsResponse)(nil), // 11: geocube.FindContainerLayoutsResponse
	(*TileAOIRequest)(nil),               // 12: geocube.TileAOIRequest
	(*TileAOIResponse)(nil),              // 13: geocube.TileAOIResponse
	(*Grid)(nil),                         // 14: geocube.Grid
	(*Cell)(nil),                         // 15: geocube.Cell
	(*CreateGridRequest)(nil),            // 16: geocube.CreateGridRequest
	(*CreateGridResponse)(nil),           // 17: geocube.CreateGridResponse
	(*DeleteGridRequest)(nil),            // 18: geocube.DeleteGridRequest
	(*DeleteGridResponse)(nil),           // 19: geocube.DeleteGridResponse
	(*ListGridsRequest)(nil),             // 20: geocube.ListGridsRequest
	(*ListGridsResponse)(nil),            // 21: geocube.ListGridsResponse
	nil,                                  // 22: geocube.Layout.GridParametersEntry
	(*RecordIdList)(nil),                 // 23: geocube.RecordIdList
	(*RecordFiltersWithAOI)(nil),         // 24: geocube.RecordFiltersWithAOI
	(*AOI)(nil),                          // 25: geocube.AOI
	(*LinearRing)(nil),                   // 26: geocube.LinearRing
}
var file_pb_layouts_proto_depIdxs = []int32{
	1,  // 0: geocube.Tile.transform:type_name -> geocube.GeoTransform
	0,  // 1: geocube.Tile.size_px:type_name -> geocube.Size
	22, // 2: geocube.Layout.grid_parameters:type_name -> geocube.Layout.GridParametersEntry
	3,  // 3: geocube.CreateLayoutRequest.layout:type_name -> geocube.Layout
	3,  // 4: geocube.ListLayoutsResponse.layouts:type_name -> geocube.Layout
	23, // 5: geocube.FindContainerLayoutsRequest.records:type_name -> geocube.RecordIdList
	24, // 6: geocube.FindContainerLayoutsRequest.filters:type_name -> geocube.RecordFiltersWithAOI
	25, // 7: geocube.TileAOIRequest.aoi:type_name -> geocube.AOI
	3,  // 8: geocube.TileAOIRequest.layout:type_name -> geocube.Layout
	2,  // 9: geocube.TileAOIResponse.tiles:type_name -> geocube.Tile
	15, // 10: geocube.Grid.cells:type_name -> geocube.Cell
	26, // 11: geocube.Cell.coordinates:type_name -> geocube.LinearRing
	14, // 12: geocube.CreateGridRequest.grid:type_name -> geocube.Grid
	14, // 13: geocube.ListGridsResponse.grids:type_name -> geocube.Grid
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pb_layouts_proto_init() }
func file_pb_layouts_proto_init() {
	if File_pb_layouts_proto != nil {
		return
	}
	file_pb_records_proto_init()
	file_pb_layouts_proto_msgTypes[10].OneofWrappers = []any{
		(*FindContainerLayoutsRequest_Records)(nil),
		(*FindContainerLayoutsRequest_Filters)(nil),
	}
	file_pb_layouts_proto_msgTypes[12].OneofWrappers = []any{
		(*TileAOIRequest_LayoutName)(nil),
		(*TileAOIRequest_Layout)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_layouts_proto_rawDesc), len(file_pb_layouts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_layouts_proto_goTypes,
		DependencyIndexes: file_pb_layouts_proto_depIdxs,
		MessageInfos:      file_pb_layouts_proto_msgTypes,
	}.Build()
	File_pb_layouts_proto = out.File
	file_pb_layouts_proto_goTypes = nil
	file_pb_layouts_proto_depIdxs = nil
}
