// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/operations.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Storage class of a container. Depends on the storage
type StorageClass int32

const (
	StorageClass_STANDARD    StorageClass = 0
	StorageClass_INFREQUENT  StorageClass = 1
	StorageClass_ARCHIVE     StorageClass = 2
	StorageClass_DEEPARCHIVE StorageClass = 3
)

// Enum value maps for StorageClass.
var (
	StorageClass_name = map[int32]string{
		0: "STANDARD",
		1: "INFREQUENT",
		2: "ARCHIVE",
		3: "DEEPARCHIVE",
	}
	StorageClass_value = map[string]int32{
		"STANDARD":    0,
		"INFREQUENT":  1,
		"ARCHIVE":     2,
		"DEEPARCHIVE": 3,
	}
)

func (x StorageClass) Enum() *StorageClass {
	p := new(StorageClass)
	*p = x
	return p
}

func (x StorageClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageClass) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_operations_proto_enumTypes[0].Descriptor()
}

func (StorageClass) Type() protoreflect.EnumType {
	return &file_pb_operations_proto_enumTypes[0]
}

func (x StorageClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageClass.Descriptor instead.
func (StorageClass) EnumDescriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{0}
}

// *
// Execution level of a job
type ExecutionLevel int32

const (
	ExecutionLevel_ExecutionSynchronous  ExecutionLevel = 0 // Job is done synchronously
	ExecutionLevel_ExecutionAsynchronous ExecutionLevel = 1 // Job is done asynchronously, but without any pause
	ExecutionLevel_StepByStepCritical    ExecutionLevel = 2 // Job is done asynchronously, step-by-step, pausing at every critical steps
	ExecutionLevel_StepByStepMajor       ExecutionLevel = 3 // Job is done asynchronously, step-by-step, pausing at every major steps
	ExecutionLevel_StepByStepAll         ExecutionLevel = 4 // Job is done asynchronously, step-by-step, pausing at every steps
)

// Enum value maps for ExecutionLevel.
var (
	ExecutionLevel_name = map[int32]string{
		0: "ExecutionSynchronous",
		1: "ExecutionAsynchronous",
		2: "StepByStepCritical",
		3: "StepByStepMajor",
		4: "StepByStepAll",
	}
	ExecutionLevel_value = map[string]int32{
		"ExecutionSynchronous":  0,
		"ExecutionAsynchronous": 1,
		"StepByStepCritical":    2,
		"StepByStepMajor":       3,
		"StepByStepAll":         4,
	}
)

func (x ExecutionLevel) Enum() *ExecutionLevel {
	p := new(ExecutionLevel)
	*p = x
	return p
}

func (x ExecutionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_operations_proto_enumTypes[1].Descriptor()
}

func (ExecutionLevel) Type() protoreflect.EnumType {
	return &file_pb_operations_proto_enumTypes[1]
}

func (x ExecutionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionLevel.Descriptor instead.
func (ExecutionLevel) EnumDescriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{1}
}

type ConsolidationParams_Compression int32

const (
	ConsolidationParams_NO       ConsolidationParams_Compression = 0
	ConsolidationParams_LOSSLESS ConsolidationParams_Compression = 1
	ConsolidationParams_LOSSY    ConsolidationParams_Compression = 2
	ConsolidationParams_CUSTOM   ConsolidationParams_Compression = 3 // configured by creation_params
)

// Enum value maps for ConsolidationParams_Compression.
var (
	ConsolidationParams_Compression_name = map[int32]string{
		0: "NO",
		1: "LOSSLESS",
		2: "LOSSY",
		3: "CUSTOM",
	}
	ConsolidationParams_Compression_value = map[string]int32{
		"NO":       0,
		"LOSSLESS": 1,
		"LOSSY":    2,
		"CUSTOM":   3,
	}
)

func (x ConsolidationParams_Compression) Enum() *ConsolidationParams_Compression {
	p := new(ConsolidationParams_Compression)
	*p = x
	return p
}

func (x ConsolidationParams_Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsolidationParams_Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_operations_proto_enumTypes[2].Descriptor()
}

func (ConsolidationParams_Compression) Type() protoreflect.EnumType {
	return &file_pb_operations_proto_enumTypes[2]
}

func (x ConsolidationParams_Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsolidationParams_Compression.Descriptor instead.
func (ConsolidationParams_Compression) EnumDescriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{7, 0}
}

// *
// Define a dataset. A dataset is the metadata to retrieve an image from a file.
// It is defined by a record and the instance of a variable.
//
// A dataset defines:
//   - Which band(s) are indexed (usually all the bands, but it can be a subset)
//   - How to map the value of its pixels to the dataformat of the variable. In more details:
//     . the dataformat of the dataset (dformat.[no_data, min, max]) that describes the pixel of the image
//     . the mapping from each pixel to the data format of the variable (variable.dformat). This mapping is defined as [MinOut, MaxOut, Exponent].
type Dataset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecordId        string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	InstanceId      string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ContainerSubdir string                 `protobuf:"bytes,6,opt,name=container_subdir,json=containerSubdir,proto3" json:"container_subdir,omitempty"`
	Bands           []int64                `protobuf:"varint,7,rep,packed,name=bands,proto3" json:"bands,omitempty"`
	Dformat         *DataFormat            `protobuf:"bytes,8,opt,name=dformat,proto3" json:"dformat,omitempty"`                                    // Internal data format (DType can be Undefined)
	RealMinValue    float64                `protobuf:"fixed64,9,opt,name=real_min_value,json=realMinValue,proto3" json:"real_min_value,omitempty"`  // Real min value (dformat.min_value maps to real_min_value)
	RealMaxValue    float64                `protobuf:"fixed64,10,opt,name=real_max_value,json=realMaxValue,proto3" json:"real_max_value,omitempty"` // Real max value (dformat.max_value maps to real_max_value)
	Exponent        float64                `protobuf:"fixed64,11,opt,name=exponent,proto3" json:"exponent,omitempty"`                               // 1: linear scaling (RealMax - RealMin) * pow( (Value - Min) / (Max - Min), Exponent) + RealMin
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_pb_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{0}
}

func (x *Dataset) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Dataset) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Dataset) GetContainerSubdir() string {
	if x != nil {
		return x.ContainerSubdir
	}
	return ""
}

func (x *Dataset) GetBands() []int64 {
	if x != nil {
		return x.Bands
	}
	return nil
}

func (x *Dataset) GetDformat() *DataFormat {
	if x != nil {
		return x.Dformat
	}
	return nil
}

func (x *Dataset) GetRealMinValue() float64 {
	if x != nil {
		return x.RealMinValue
	}
	return 0
}

func (x *Dataset) GetRealMaxValue() float64 {
	if x != nil {
		return x.RealMaxValue
	}
	return 0
}

func (x *Dataset) GetExponent() float64 {
	if x != nil {
		return x.Exponent
	}
	return 0
}

// *
// Define a container of datasets.
// Usually a container is a file containing one dataset.
// But after a consolidation or if the container has several bands, it can contain several datasets.
type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`           // URI of the file
	Managed       bool                   `protobuf:"varint,2,opt,name=managed,proto3" json:"managed,omitempty"`  // True if the Geocube is responsible for the lifecycle of this file
	Datasets      []*Dataset             `protobuf:"bytes,3,rep,name=datasets,proto3" json:"datasets,omitempty"` // List of datasets of the container
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_pb_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{1}
}

func (x *Container) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Container) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *Container) GetDatasets() []*Dataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

// *
// Job to modify datasets (consolidation, deletion, ingestion...)
// Some lifecycle operations are required to be done cautiously, in order to garantee the integrity of the database.
// Such operations are defined by a job and are done asynchronously.
// A job is a state-machine that can be rollbacked anytime during the operation until it ends.
type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                             // Id of the job
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                         // Name of the job (must be unique)
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                                                         // Type of the job (consolidation, deletion...)
	State          string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                                                       // Current state of the state machine
	CreationTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`                                     // Time of creation of the job
	LastUpdateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`                             // Time of the last update
	Logs           []string               `protobuf:"bytes,7,rep,name=logs,proto3" json:"logs,omitempty"`                                                                         // Job logs: if logs are too big to fit in a grpc response, logs will only be a subset (by default, the latest)
	ActiveTasks    int32                  `protobuf:"varint,8,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`                                       // If the job is divided into sub tasks, number of pending tasks
	FailedTasks    int32                  `protobuf:"varint,9,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`                                       // If the job is divided into sub tasks, number of failed tasks
	ExecutionLevel ExecutionLevel         `protobuf:"varint,10,opt,name=execution_level,json=executionLevel,proto3,enum=geocube.ExecutionLevel" json:"execution_level,omitempty"` // Execution level of a job (see ExecutionLevel)
	Waiting        bool                   `protobuf:"varint,11,opt,name=waiting,proto3" json:"waiting,omitempty"`                                                                 // If true, the job is waiting for user to continue
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_pb_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Job) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Job) GetLastUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdateTime
	}
	return nil
}

func (x *Job) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Job) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *Job) GetFailedTasks() int32 {
	if x != nil {
		return x.FailedTasks
	}
	return 0
}

func (x *Job) GetExecutionLevel() ExecutionLevel {
	if x != nil {
		return x.ExecutionLevel
	}
	return ExecutionLevel_ExecutionSynchronous
}

func (x *Job) GetWaiting() bool {
	if x != nil {
		return x.Waiting
	}
	return false
}

// *
// Request info on containers
type GetContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uris          []string               `protobuf:"bytes,1,rep,name=uris,proto3" json:"uris,omitempty"` // List of container uris
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainersRequest) Reset() {
	*x = GetContainersRequest{}
	mi := &file_pb_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainersRequest) ProtoMessage() {}

func (x *GetContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainersRequest.ProtoReflect.Descriptor instead.
func (*GetContainersRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{3}
}

func (x *GetContainersRequest) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

// *
type GetContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainersResponse) Reset() {
	*x = GetContainersResponse{}
	mi := &file_pb_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainersResponse) ProtoMessage() {}

func (x *GetContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainersResponse.ProtoReflect.Descriptor instead.
func (*GetContainersResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{4}
}

func (x *GetContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

// *
// Request to index all the datasets of a container
type IndexDatasetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO Index several containers: repeated ?
	Container     *Container `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDatasetsRequest) Reset() {
	*x = IndexDatasetsRequest{}
	mi := &file_pb_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDatasetsRequest) ProtoMessage() {}

func (x *IndexDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDatasetsRequest.ProtoReflect.Descriptor instead.
func (*IndexDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{5}
}

func (x *IndexDatasetsRequest) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

// *
type IndexDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDatasetsResponse) Reset() {
	*x = IndexDatasetsResponse{}
	mi := &file_pb_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDatasetsResponse) ProtoMessage() {}

func (x *IndexDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDatasetsResponse.ProtoReflect.Descriptor instead.
func (*IndexDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{6}
}

// *
// Parameters of consolidation that are linked to a variable, to define:
// - how to resample the data during consolidation
// - how to store the data:
//   - Compression
//   - CreationParams (supported: see GDAL drivers: PHOTOMETRIC, COMPRESS, PREDICTOR, ZLEVEL, ZSTDLEVEL, MAX_Z_ERROR, JPEGTABLESMODE and with _OVERVIEW suffix if exists)
type ConsolidationParams struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Dformat  *DataFormat            `protobuf:"bytes,1,opt,name=dformat,proto3" json:"dformat,omitempty"`     // dataformat of the data. See exponent for the mapping formula.
	Exponent float64                `protobuf:"fixed64,2,opt,name=exponent,proto3" json:"exponent,omitempty"` // 1: linear scaling (RealMax - RealMin) * pow( (Value - Min) / (Max - Min), Exponent) + RealMin
	// Deprecated: Marked as deprecated in pb/operations.proto.
	CreateOverviews bool                            `protobuf:"varint,3,opt,name=create_overviews,json=createOverviews,proto3" json:"create_overviews,omitempty"`                                                                       // Use Layout.overviews_min_size instead
	ResamplingAlg   Resampling                      `protobuf:"varint,4,opt,name=resampling_alg,json=resamplingAlg,proto3,enum=geocube.Resampling" json:"resampling_alg,omitempty"`                                                     // Define how to resample the data during the consolidation (if a reprojection is needed or if the overviews are created)
	Compression     ConsolidationParams_Compression `protobuf:"varint,5,opt,name=compression,proto3,enum=geocube.ConsolidationParams_Compression" json:"compression,omitempty"`                                                         // Define how the data is compressed at block level
	CreationParams  map[string]string               `protobuf:"bytes,8,rep,name=creation_params,json=creationParams,proto3" json:"creation_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map of params:value to configure the creation of the file. See Compression to list the supported params
	// Deprecated: Marked as deprecated in pb/operations.proto.
	BandsInterleave bool         `protobuf:"varint,6,opt,name=bands_interleave,json=bandsInterleave,proto3" json:"bands_interleave,omitempty"`                  // If the variable is multibands, define whether the bands are interleaved. Use Layout.interlacing_pattern instead
	StorageClass    StorageClass `protobuf:"varint,7,opt,name=storage_class,json=storageClass,proto3,enum=geocube.StorageClass" json:"storage_class,omitempty"` // Define the storage class of the created file (support only GCS)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsolidationParams) Reset() {
	*x = ConsolidationParams{}
	mi := &file_pb_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidationParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidationParams) ProtoMessage() {}

func (x *ConsolidationParams) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidationParams.ProtoReflect.Descriptor instead.
func (*ConsolidationParams) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{7}
}

func (x *ConsolidationParams) GetDformat() *DataFormat {
	if x != nil {
		return x.Dformat
	}
	return nil
}

func (x *ConsolidationParams) GetExponent() float64 {
	if x != nil {
		return x.Exponent
	}
	return 0
}

// Deprecated: Marked as deprecated in pb/operations.proto.
func (x *ConsolidationParams) GetCreateOverviews() bool {
	if x != nil {
		return x.CreateOverviews
	}
	return false
}

func (x *ConsolidationParams) GetResamplingAlg() Resampling {
	if x != nil {
		return x.ResamplingAlg
	}
	return Resampling_UNDEFINED
}

func (x *ConsolidationParams) GetCompression() ConsolidationParams_Compression {
	if x != nil {
		return x.Compression
	}
	return ConsolidationParams_NO
}

func (x *ConsolidationParams) GetCreationParams() map[string]string {
	if x != nil {
		return x.CreationParams
	}
	return nil
}

// Deprecated: Marked as deprecated in pb/operations.proto.
func (x *ConsolidationParams) GetBandsInterleave() bool {
	if x != nil {
		return x.BandsInterleave
	}
	return false
}

func (x *ConsolidationParams) GetStorageClass() StorageClass {
	if x != nil {
		return x.StorageClass
	}
	return StorageClass_STANDARD
}

// *
// Configure the parameters of the consolidation attached to the variable
type ConfigConsolidationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	VariableId          string                 `protobuf:"bytes,1,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
	ConsolidationParams *ConsolidationParams   `protobuf:"bytes,2,opt,name=consolidation_params,json=consolidationParams,proto3" json:"consolidation_params,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigConsolidationRequest) Reset() {
	*x = ConfigConsolidationRequest{}
	mi := &file_pb_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigConsolidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigConsolidationRequest) ProtoMessage() {}

func (x *ConfigConsolidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigConsolidationRequest.ProtoReflect.Descriptor instead.
func (*ConfigConsolidationRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigConsolidationRequest) GetVariableId() string {
	if x != nil {
		return x.VariableId
	}
	return ""
}

func (x *ConfigConsolidationRequest) GetConsolidationParams() *ConsolidationParams {
	if x != nil {
		return x.ConsolidationParams
	}
	return nil
}

// *
type ConfigConsolidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigConsolidationResponse) Reset() {
	*x = ConfigConsolidationResponse{}
	mi := &file_pb_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigConsolidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigConsolidationResponse) ProtoMessage() {}

func (x *ConfigConsolidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigConsolidationResponse.ProtoReflect.Descriptor instead.
func (*ConfigConsolidationResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{9}
}

// *
// Retrieve the consolidation parameters attached to the given variable
type GetConsolidationParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariableId    string                 `protobuf:"bytes,1,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsolidationParamsRequest) Reset() {
	*x = GetConsolidationParamsRequest{}
	mi := &file_pb_operations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidationParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidationParamsRequest) ProtoMessage() {}

func (x *GetConsolidationParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidationParamsRequest.ProtoReflect.Descriptor instead.
func (*GetConsolidationParamsRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{10}
}

func (x *GetConsolidationParamsRequest) GetVariableId() string {
	if x != nil {
		return x.VariableId
	}
	return ""
}

// *
// Return consolidation parameters
type GetConsolidationParamsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConsolidationParams *ConsolidationParams   `protobuf:"bytes,2,opt,name=consolidation_params,json=consolidationParams,proto3" json:"consolidation_params,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetConsolidationParamsResponse) Reset() {
	*x = GetConsolidationParamsResponse{}
	mi := &file_pb_operations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidationParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidationParamsResponse) ProtoMessage() {}

func (x *GetConsolidationParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidationParamsResponse.ProtoReflect.Descriptor instead.
func (*GetConsolidationParamsResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{11}
}

func (x *GetConsolidationParamsResponse) GetConsolidationParams() *ConsolidationParams {
	if x != nil {
		return x.ConsolidationParams
	}
	return nil
}

// *
// Create and start a consolidation job given a list of records and an instance_id to be consolidated on a layout
// Optionnaly, the job can be done step by step, pausing and waiting for user action, with three levels:
// - 1: after each critical steps
// - 2: after each major steps
// - 3: after all steps
type ConsolidateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobName            string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	InstanceId         string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	LayoutName         string                 `protobuf:"bytes,7,opt,name=layout_name,json=layoutName,proto3" json:"layout_name,omitempty"`
	ExecutionLevel     ExecutionLevel         `protobuf:"varint,6,opt,name=execution_level,json=executionLevel,proto3,enum=geocube.ExecutionLevel" json:"execution_level,omitempty"` // Execution level of a job. A consolidation job cannot be executed synchronously
	CollapseOnRecordId string                 `protobuf:"bytes,9,opt,name=collapse_on_record_id,json=collapseOnRecordId,proto3" json:"collapse_on_record_id,omitempty"`              // [Optional] Collapse all records on this record (in this case only, original datasets are kept, data is duplicated)
	// Types that are valid to be assigned to RecordsLister:
	//
	//	*ConsolidateRequest_Records
	//	*ConsolidateRequest_Filters
	RecordsLister isConsolidateRequest_RecordsLister `protobuf_oneof:"records_lister"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidateRequest) Reset() {
	*x = ConsolidateRequest{}
	mi := &file_pb_operations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidateRequest) ProtoMessage() {}

func (x *ConsolidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidateRequest.ProtoReflect.Descriptor instead.
func (*ConsolidateRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{12}
}

func (x *ConsolidateRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ConsolidateRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ConsolidateRequest) GetLayoutName() string {
	if x != nil {
		return x.LayoutName
	}
	return ""
}

func (x *ConsolidateRequest) GetExecutionLevel() ExecutionLevel {
	if x != nil {
		return x.ExecutionLevel
	}
	return ExecutionLevel_ExecutionSynchronous
}

func (x *ConsolidateRequest) GetCollapseOnRecordId() string {
	if x != nil {
		return x.CollapseOnRecordId
	}
	return ""
}

func (x *ConsolidateRequest) GetRecordsLister() isConsolidateRequest_RecordsLister {
	if x != nil {
		return x.RecordsLister
	}
	return nil
}

func (x *ConsolidateRequest) GetRecords() *RecordIdList {
	if x != nil {
		if x, ok := x.RecordsLister.(*ConsolidateRequest_Records); ok {
			return x.Records
		}
	}
	return nil
}

func (x *ConsolidateRequest) GetFilters() *RecordFilters {
	if x != nil {
		if x, ok := x.RecordsLister.(*ConsolidateRequest_Filters); ok {
			return x.Filters
		}
	}
	return nil
}

type isConsolidateRequest_RecordsLister interface {
	isConsolidateRequest_RecordsLister()
}

type ConsolidateRequest_Records struct {
	Records *RecordIdList `protobuf:"bytes,8,opt,name=records,proto3,oneof"` // At least one
}

type ConsolidateRequest_Filters struct {
	Filters *RecordFilters `protobuf:"bytes,5,opt,name=filters,proto3,oneof"`
}

func (*ConsolidateRequest_Records) isConsolidateRequest_RecordsLister() {}

func (*ConsolidateRequest_Filters) isConsolidateRequest_RecordsLister() {}

// *
// Return the id of the job created
type ConsolidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidateResponse) Reset() {
	*x = ConsolidateResponse{}
	mi := &file_pb_operations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidateResponse) ProtoMessage() {}

func (x *ConsolidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidateResponse.ProtoReflect.Descriptor instead.
func (*ConsolidateResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{13}
}

func (x *ConsolidateResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// *
// List jobs given a name pattern
type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameLike      string                 `protobuf:"bytes,1,opt,name=name_like,json=nameLike,proto3" json:"name_like,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_pb_operations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{14}
}

func (x *ListJobsRequest) GetNameLike() string {
	if x != nil {
		return x.NameLike
	}
	return ""
}

func (x *ListJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// *
// Return a list of the job whose name matchs the pattern
type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_pb_operations_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{15}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// *
// Retrieve a job given its id
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LogPage       int32                  `protobuf:"varint,2,opt,name=log_page,json=logPage,proto3" json:"log_page,omitempty"`
	LogLimit      int32                  `protobuf:"varint,3,opt,name=log_limit,json=logLimit,proto3" json:"log_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_pb_operations_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{16}
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetJobRequest) GetLogPage() int32 {
	if x != nil {
		return x.LogPage
	}
	return 0
}

func (x *GetJobRequest) GetLogLimit() int32 {
	if x != nil {
		return x.LogLimit
	}
	return 0
}

// *
// Return a job with the requested id
type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_pb_operations_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{17}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// Clean terminated jobs
type CleanJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameLike      string                 `protobuf:"bytes,1,opt,name=name_like,json=nameLike,proto3" json:"name_like,omitempty"` // Filter by name (support *, ? and (?i)-suffix for case-insensitivity)
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                       // Filter by terminated state (DONE, FAILED)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanJobsRequest) Reset() {
	*x = CleanJobsRequest{}
	mi := &file_pb_operations_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanJobsRequest) ProtoMessage() {}

func (x *CleanJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanJobsRequest.ProtoReflect.Descriptor instead.
func (*CleanJobsRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{18}
}

func (x *CleanJobsRequest) GetNameLike() string {
	if x != nil {
		return x.NameLike
	}
	return ""
}

func (x *CleanJobsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// *
// Return the number of jobs that have been deleted
type CleanJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanJobsResponse) Reset() {
	*x = CleanJobsResponse{}
	mi := &file_pb_operations_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanJobsResponse) ProtoMessage() {}

func (x *CleanJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanJobsResponse.ProtoReflect.Descriptor instead.
func (*CleanJobsResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{19}
}

func (x *CleanJobsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// *
// Cancel a job (e.g. during consolidation)
type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ForceAnyState bool                   `protobuf:"varint,2,opt,name=force_any_state,json=forceAnyState,proto3" json:"force_any_state,omitempty"` // Force cancel even when the job is not in a failed state or consolidation step (could corrupt the data)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_pb_operations_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{20}
}

func (x *CancelJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelJobRequest) GetForceAnyState() bool {
	if x != nil {
		return x.ForceAnyState
	}
	return false
}

// *
type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_pb_operations_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{21}
}

// *
// Retry a job that failed or is stuck (e.g. during consolidation)
type RetryJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ForceAnyState bool                   `protobuf:"varint,2,opt,name=force_any_state,json=forceAnyState,proto3" json:"force_any_state,omitempty"` // Force retry even when the job is not in a failed state (could corrupt the data)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryJobRequest) Reset() {
	*x = RetryJobRequest{}
	mi := &file_pb_operations_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryJobRequest) ProtoMessage() {}

func (x *RetryJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryJobRequest.ProtoReflect.Descriptor instead.
func (*RetryJobRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{22}
}

func (x *RetryJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RetryJobRequest) GetForceAnyState() bool {
	if x != nil {
		return x.ForceAnyState
	}
	return false
}

// *
type RetryJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryJobResponse) Reset() {
	*x = RetryJobResponse{}
	mi := &file_pb_operations_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryJobResponse) ProtoMessage() {}

func (x *RetryJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryJobResponse.ProtoReflect.Descriptor instead.
func (*RetryJobResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{23}
}

// *
// Proceed the next step of a step-by-step job
type ContinueJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueJobRequest) Reset() {
	*x = ContinueJobRequest{}
	mi := &file_pb_operations_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueJobRequest) ProtoMessage() {}

func (x *ContinueJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueJobRequest.ProtoReflect.Descriptor instead.
func (*ContinueJobRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{24}
}

func (x *ContinueJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// *
type ContinueJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueJobResponse) Reset() {
	*x = ContinueJobResponse{}
	mi := &file_pb_operations_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueJobResponse) ProtoMessage() {}

func (x *ContinueJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueJobResponse.ProtoReflect.Descriptor instead.
func (*ContinueJobResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{25}
}

// *
// Remove the datasets referenced by instances and records without any control
// The containers (if empty) are not deleted
type DeleteDatasetsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecordIds       []string               `protobuf:"bytes,2,rep,name=record_ids,json=recordIds,proto3" json:"record_ids,omitempty"`                                             // Instance id that references the datasets to be deleted
	InstanceIds     []string               `protobuf:"bytes,3,rep,name=instance_ids,json=instanceIds,proto3" json:"instance_ids,omitempty"`                                       // Record ids that reference the datasets to be deleted
	DatasetPatterns []string               `protobuf:"bytes,6,rep,name=dataset_patterns,json=datasetPatterns,proto3" json:"dataset_patterns,omitempty"`                           // Dataset file patterns (support * and ? for all or any characters and trailing (?i) for case-insensitiveness) (or empty to ignore)
	ExecutionLevel  ExecutionLevel         `protobuf:"varint,4,opt,name=execution_level,json=executionLevel,proto3,enum=geocube.ExecutionLevel" json:"execution_level,omitempty"` // Execution level (see enum)
	JobName         string                 `protobuf:"bytes,5,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`                                                   // Name of the job (if empty, a name will be generated)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteDatasetsRequest) Reset() {
	*x = DeleteDatasetsRequest{}
	mi := &file_pb_operations_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasetsRequest) ProtoMessage() {}

func (x *DeleteDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasetsRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteDatasetsRequest) GetRecordIds() []string {
	if x != nil {
		return x.RecordIds
	}
	return nil
}

func (x *DeleteDatasetsRequest) GetInstanceIds() []string {
	if x != nil {
		return x.InstanceIds
	}
	return nil
}

func (x *DeleteDatasetsRequest) GetDatasetPatterns() []string {
	if x != nil {
		return x.DatasetPatterns
	}
	return nil
}

func (x *DeleteDatasetsRequest) GetExecutionLevel() ExecutionLevel {
	if x != nil {
		return x.ExecutionLevel
	}
	return ExecutionLevel_ExecutionSynchronous
}

func (x *DeleteDatasetsRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

// *
// Return the number of deleted datasets
type DeleteDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatasetsResponse) Reset() {
	*x = DeleteDatasetsResponse{}
	mi := &file_pb_operations_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasetsResponse) ProtoMessage() {}

func (x *DeleteDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_operations_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasetsResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_pb_operations_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteDatasetsResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_pb_operations_proto protoreflect.FileDescriptor

const file_pb_operations_proto_rawDesc = "" +
	"\n" +
	"\x13pb/operations.proto\x12\ageocube\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13pb/dataformat.proto\x1a\x12pb/variables.proto\x1a\x10pb/records.proto\"\x9f\x02\n" +
	"\aDataset\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12)\n" +
	"\x10container_subdir\x18\x06 \x01(\tR\x0fcontainerSubdir\x12\x14\n" +
	"\x05bands\x18\a \x03(\x03R\x05bands\x12-\n" +
	"\adformat\x18\b \x01(\v2\x13.geocube.DataFormatR\adformat\x12$\n" +
	"\x0ereal_min_value\x18\t \x01(\x01R\frealMinValue\x12$\n" +
	"\x0ereal_max_value\x18\n" +
	" \x01(\x01R\frealMaxValue\x12\x1a\n" +
	"\bexponent\x18\v \x01(\x01R\bexponent\"e\n" +
	"\tContainer\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x18\n" +
	"\amanaged\x18\x02 \x01(\bR\amanaged\x12,\n" +
	"\bdatasets\x18\x03 \x03(\v2\x10.geocube.DatasetR\bdatasets\"\x90\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12?\n" +
	"\rcreation_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\x12D\n" +
	"\x10last_update_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastUpdateTime\x12\x12\n" +
	"\x04logs\x18\a \x03(\tR\x04logs\x12!\n" +
	"\factive_tasks\x18\b \x01(\x05R\vactiveTasks\x12!\n" +
	"\ffailed_tasks\x18\t \x01(\x05R\vfailedTasks\x12@\n" +
	"\x0fexecution_level\x18\n" +
	" \x01(\x0e2\x17.geocube.ExecutionLevelR\x0eexecutionLevel\x12\x18\n" +
	"\awaiting\x18\v \x01(\bR\awaiting\"*\n" +
	"\x14GetContainersRequest\x12\x12\n" +
	"\x04uris\x18\x01 \x03(\tR\x04uris\"K\n" +
	"\x15GetContainersResponse\x122\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x12.geocube.ContainerR\n" +
	"containers\"H\n" +
	"\x14IndexDatasetsRequest\x120\n" +
	"\tcontainer\x18\x01 \x01(\v2\x12.geocube.ContainerR\tcontainer\"\x17\n" +
	"\x15IndexDatasetsResponse\"\xdc\x04\n" +
	"\x13ConsolidationParams\x12-\n" +
	"\adformat\x18\x01 \x01(\v2\x13.geocube.DataFormatR\adformat\x12\x1a\n" +
	"\bexponent\x18\x02 \x01(\x01R\bexponent\x12-\n" +
	"\x10create_overviews\x18\x03 \x01(\bB\x02\x18\x01R\x0fcreateOverviews\x12:\n" +
	"\x0eresampling_alg\x18\x04 \x01(\x0e2\x13.geocube.ResamplingR\rresamplingAlg\x12J\n" +
	"\vcompression\x18\x05 \x01(\x0e2(.geocube.ConsolidationParams.CompressionR\vcompression\x12Y\n" +
	"\x0fcreation_params\x18\b \x03(\v20.geocube.ConsolidationParams.CreationParamsEntryR\x0ecreationParams\x12-\n" +
	"\x10bands_interleave\x18\x06 \x01(\bB\x02\x18\x01R\x0fbandsInterleave\x12:\n" +
	"\rstorage_class\x18\a \x01(\x0e2\x15.geocube.StorageClassR\fstorageClass\x1aA\n" +
	"\x13CreationParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\vCompression\x12\x06\n" +
	"\x02NO\x10\x00\x12\f\n" +
	"\bLOSSLESS\x10\x01\x12\t\n" +
	"\x05LOSSY\x10\x02\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x03\"\x8e\x01\n" +
	"\x1aConfigConsolidationRequest\x12\x1f\n" +
	"\vvariable_id\x18\x01 \x01(\tR\n" +
	"variableId\x12O\n" +
	"\x14consolidation_params\x18\x02 \x01(\v2\x1c.geocube.ConsolidationParamsR\x13consolidationParams\"\x1d\n" +
	"\x1bConfigConsolidationResponse\"@\n" +
	"\x1dGetConsolidationParamsRequest\x12\x1f\n" +
	"\vvariable_id\x18\x01 \x01(\tR\n" +
	"variableId\"q\n" +
	"\x1eGetConsolidationParamsResponse\x12O\n" +
	"\x14consolidation_params\x18\x02 \x01(\v2\x1c.geocube.ConsolidationParamsR\x13consolidationParams\"\xdf\x02\n" +
	"\x12ConsolidateRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vlayout_name\x18\a \x01(\tR\n" +
	"layoutName\x12@\n" +
	"\x0fexecution_level\x18\x06 \x01(\x0e2\x17.geocube.ExecutionLevelR\x0eexecutionLevel\x121\n" +
	"\x15collapse_on_record_id\x18\t \x01(\tR\x12collapseOnRecordId\x121\n" +
	"\arecords\x18\b \x01(\v2\x15.geocube.RecordIdListH\x00R\arecords\x122\n" +
	"\afilters\x18\x05 \x01(\v2\x16.geocube.RecordFiltersH\x00R\afiltersB\x10\n" +
	"\x0erecords_lister\",\n" +
	"\x13ConsolidateResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"X\n" +
	"\x0fListJobsRequest\x12\x1b\n" +
	"\tname_like\x18\x01 \x01(\tR\bnameLike\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"4\n" +
	"\x10ListJobsResponse\x12 \n" +
	"\x04jobs\x18\x01 \x03(\v2\f.geocube.JobR\x04jobs\"W\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\blog_page\x18\x02 \x01(\x05R\alogPage\x12\x1b\n" +
	"\tlog_limit\x18\x03 \x01(\x05R\blogLimit\"0\n" +
	"\x0eGetJobResponse\x12\x1e\n" +
	"\x03job\x18\x01 \x01(\v2\f.geocube.JobR\x03job\"E\n" +
	"\x10CleanJobsRequest\x12\x1b\n" +
	"\tname_like\x18\x01 \x01(\tR\bnameLike\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\")\n" +
	"\x11CleanJobsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"J\n" +
	"\x10CancelJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fforce_any_state\x18\x02 \x01(\bR\rforceAnyState\"\x13\n" +
	"\x11CancelJobResponse\"I\n" +
	"\x0fRetryJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fforce_any_state\x18\x02 \x01(\bR\rforceAnyState\"\x12\n" +
	"\x10RetryJobResponse\"$\n" +
	"\x12ContinueJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ContinueJobResponse\"\xe1\x01\n" +
	"\x15DeleteDatasetsRequest\x12\x1d\n" +
	"\n" +
	"record_ids\x18\x02 \x03(\tR\trecordIds\x12!\n" +
	"\finstance_ids\x18\x03 \x03(\tR\vinstanceIds\x12)\n" +
	"\x10dataset_patterns\x18\x06 \x03(\tR\x0fdatasetPatterns\x12@\n" +
	"\x0fexecution_level\x18\x04 \x01(\x0e2\x17.geocube.ExecutionLevelR\x0eexecutionLevel\x12\x19\n" +
	"\bjob_name\x18\x05 \x01(\tR\ajobName\"8\n" +
	"\x16DeleteDatasetsResponse\x12\x1e\n" +
	"\x03job\x18\x02 \x01(\v2\f.geocube.JobR\x03job*J\n" +
	"\fStorageClass\x12\f\n" +
	"\bSTANDARD\x10\x00\x12\x0e\n" +
	"\n" +
	"INFREQUENT\x10\x01\x12\v\n" +
	"\aARCHIVE\x10\x02\x12\x0f\n" +
	"\vDEEPARCHIVE\x10\x03*\x85\x01\n" +
	"\x0eExecutionLevel\x12\x18\n" +
	"\x14ExecutionSynchronous\x10\x00\x12\x19\n" +
	"\x15ExecutionAsynchronous\x10\x01\x12\x16\n" +
	"\x12StepByStepCritical\x10\x02\x12\x13\n" +
	"\x0fStepByStepMajor\x10\x03\x12\x11\n" +
	"\rStepByStepAll\x10\x04B\x0eZ\f./pb;geocubeb\x06proto3"

var (
	file_pb_operations_proto_rawDescOnce sync.Once
	file_pb_operations_proto_rawDescData []byte
)

func file_pb_operations_proto_rawDescGZIP() []byte {
	file_pb_operations_proto_rawDescOnce.Do(func() {
		file_pb_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_operations_proto_rawDesc), len(file_pb_operations_proto_rawDesc)))
	})
	return file_pb_operations_proto_rawDescData
}

var file_pb_operations_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_pb_operations_proto_goTypes = []any{
	(StorageClass)(0),                      // 0: geocube.StorageClass
	(ExecutionLevel)(0),                    // 1: geocube.ExecutionLevel
	(ConsolidationParams_Compression)(0),   // 2: geocube.ConsolidationParams.Compression
	(*Dataset)(nil),                        // 3: geocube.Dataset
	(*Container)(nil),                      // 4: geocube.Container
	(*Job)(nil),                            // 5: geocube.Job
	(*GetContainersRequest)(nil),           // 6: geocube.GetContainersRequest
	(*GetContainersResponse)(nil),          // 7: geocube.GetContainersResponse
	(*IndexDatasetsRequest)(nil),           // 8: geocube.IndexDatasetsRequest
	(*IndexDatasetsResponse)(nil),          // 9: geocube.IndexDatasetsResponse
	(*ConsolidationParams)(nil),            // 10: geocube.ConsolidationParams
	(*ConfigConsolidationRequest)(nil),     // 11: geocube.ConfigConsolidationRequest
	(*ConfigConsolidationResponse)(nil),    // 12: geocube.ConfigConsolidationResponse
	(*GetConsolidationParamsRequest)(nil),  // 13: geocube.GetConsolidationParamsRequest
	(*GetConsolidationParamsResponse)(nil), // 14: geocube.GetConsolidationParamsResponse
	(*ConsolidateRequest)(nil),             // 15: geocube.ConsolidateRequest
	(*ConsolidateResponse)(nil),            // 16: geocube.ConsolidateResponse
	(*ListJobsRequest)(nil),                // 17: geocube.ListJobsRequest
	(*ListJobsResponse)(nil),               // 18: geocube.ListJobsResponse
	(*GetJobRequest)(nil),                  // 19: geocube.GetJobRequest
	(*GetJobResponse)(nil),                 // 20: geocube.GetJobResponse
	(*CleanJobsRequest)(nil),               // 21: geocube.CleanJobsRequest
	(*CleanJobsResponse)(nil),              // 22: geocube.CleanJobsResponse
	(*CancelJobRequest)(nil),               // 23: geocube.CancelJobRequest
	(*CancelJobResponse)(nil),              // 24: geocube.CancelJobResponse
	(*RetryJobRequest)(nil),                // 25: geocube.RetryJobRequest
	(*RetryJobResponse)(nil),               // 26: geocube.RetryJobResponse
	(*ContinueJobRequest)(nil),             // 27: geocube.ContinueJobRequest
	(*ContinueJobResponse)(nil),            // 28: geocube.ContinueJobResponse
	(*DeleteDatasetsRequest)(nil),          // 29: geocube.DeleteDatasetsRequest
	(*DeleteDatasetsResponse)(nil),         // 30: geocube.DeleteDatasetsResponse
	nil,                                    // 31: geocube.ConsolidationParams.CreationParamsEntry
	(*DataFormat)(nil),                     // 32: geocube.DataFormat
	(*timestamppb.Timestamp)(nil),          // 33: google.protobuf.Timestamp
	(Resampling)(0),                        // 34: geocube.Resampling
	(*RecordIdList)(nil),                   // 35: geocube.RecordIdList
	(*RecordFilters)(nil),                  // 36: geocube.RecordFilters
}
var file_pb_operations_proto_depIdxs = []int32{
	32, // 0: geocube.Dataset.dformat:type_name -> geocube.DataFormat
	3,  // 1: geocube.Container.datasets:type_name -> geocube.Dataset
	33, // 2: geocube.Job.creation_time:type_name -> google.protobuf.Timestamp
	33, // 3: geocube.Job.last_update_time:type_name -> google.protobuf.Timestamp
	1,  // 4: geocube.Job.execution_level:type_name -> geocube.ExecutionLevel
	4,  // 5: geocube.GetContainersResponse.containers:type_name -> geocube.Container
	4,  // 6: geocube.IndexDatasetsRequest.container:type_name -> geocube.Container
	32, // 7: geocube.ConsolidationParams.dformat:type_name -> geocube.DataFormat
	34, // 8: geocube.ConsolidationParams.resampling_alg:type_name -> geocube.Resampling
	2,  // 9: geocube.ConsolidationParams.compression:type_name -> geocube.ConsolidationParams.Compression
	31, // 10: geocube.ConsolidationParams.creation_params:type_name -> geocube.ConsolidationParams.CreationParamsEntry
	0,  // 11: geocube.ConsolidationParams.storage_class:type_name -> geocube.StorageClass
	10, // 12: geocube.ConfigConsolidationRequest.consolidation_params:type_name -> geocube.ConsolidationParams
	10, // 13: geocube.GetConsolidationParamsResponse.consolidation_params:type_name -> geocube.ConsolidationParams
	1,  // 14: geocube.ConsolidateRequest.execution_level:type_name -> geocube.ExecutionLevel
	35, // 15: geocube.ConsolidateRequest.records:type_name -> geocube.RecordIdList
	36, // 16: geocube.ConsolidateRequest.filters:type_name -> geocube.RecordFilters
	5,  // 17: geocube.ListJobsResponse.jobs:type_name -> geocube.Job
	5,  // 18: geocube.GetJobResponse.job:type_name -> geocube.Job
	1,  // 19: geocube.DeleteDatasetsRequest.execution_level:type_name -> geocube.ExecutionLevel
	5,  // 20: geocube.DeleteDatasetsResponse.job:type_name -> geocube.Job
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pb_operations_proto_init() }
func file_pb_operations_proto_init() {
	if File_pb_operations_proto != nil {
		return
	}
	file_pb_dataformat_proto_init()
	file_pb_variables_proto_init()
	file_pb_records_proto_init()
	file_pb_operations_proto_msgTypes[12].OneofWrappers = []any{
		(*ConsolidateRequest_Records)(nil),
		(*ConsolidateRequest_Filters)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_operations_proto_rawDesc), len(file_pb_operations_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_operations_proto_goTypes,
		DependencyIndexes: file_pb_operations_proto_depIdxs,
		EnumInfos:         file_pb_operations_proto_enumTypes,
		MessageInfos:      file_pb_operations_proto_msgTypes,
	}.Build()
	File_pb_operations_proto = out.File
	file_pb_operations_proto_goTypes = nil
	file_pb_operations_proto_depIdxs = nil
}
