// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/palettes.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPaletteRequest define a Getter request
type GetPaletteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaletteRequest) Reset() {
	*x = GetPaletteRequest{}
	mi := &file_pb_palettes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaletteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaletteRequest) ProtoMessage() {}

func (x *GetPaletteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_palettes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaletteRequest.ProtoReflect.Descriptor instead.
func (*GetPaletteRequest) Descriptor() ([]byte, []int) {
	return file_pb_palettes_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaletteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetPaletteResponse define Palette response request
type GetPaletteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Palette       *Palette               `protobuf:"bytes,1,opt,name=palette,proto3" json:"palette,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaletteResponse) Reset() {
	*x = GetPaletteResponse{}
	mi := &file_pb_palettes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaletteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaletteResponse) ProtoMessage() {}

func (x *GetPaletteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_palettes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaletteResponse.ProtoReflect.Descriptor instead.
func (*GetPaletteResponse) Descriptor() ([]byte, []int) {
	return file_pb_palettes_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaletteResponse) GetPalette() *Palette {
	if x != nil {
		return x.Palette
	}
	return nil
}

var File_pb_palettes_proto protoreflect.FileDescriptor

const file_pb_palettes_proto_rawDesc = "" +
	"\n" +
	"\x11pb/palettes.proto\x12\ageocube\x1a\x12pb/variables.proto\"'\n" +
	"\x11GetPaletteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x12GetPaletteResponse\x12*\n" +
	"\apalette\x18\x01 \x01(\v2\x10.geocube.PaletteR\apaletteB\x0eZ\f./pb;geocubeb\x06proto3"

var (
	file_pb_palettes_proto_rawDescOnce sync.Once
	file_pb_palettes_proto_rawDescData []byte
)

func file_pb_palettes_proto_rawDescGZIP() []byte {
	file_pb_palettes_proto_rawDescOnce.Do(func() {
		file_pb_palettes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_palettes_proto_rawDesc), len(file_pb_palettes_proto_rawDesc)))
	})
	return file_pb_palettes_proto_rawDescData
}

var file_pb_palettes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_palettes_proto_goTypes = []any{
	(*GetPaletteRequest)(nil),  // 0: geocube.GetPaletteRequest
	(*GetPaletteResponse)(nil), // 1: geocube.GetPaletteResponse
	(*Palette)(nil),            // 2: geocube.Palette
}
var file_pb_palettes_proto_depIdxs = []int32{
	2, // 0: geocube.GetPaletteResponse.palette:type_name -> geocube.Palette
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_palettes_proto_init() }
func file_pb_palettes_proto_init() {
	if File_pb_palettes_proto != nil {
		return
	}
	file_pb_variables_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_palettes_proto_rawDesc), len(file_pb_palettes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_palettes_proto_goTypes,
		DependencyIndexes: file_pb_palettes_proto_depIdxs,
		MessageInfos:      file_pb_palettes_proto_msgTypes,
	}.Build()
	File_pb_palettes_proto = out.File
	file_pb_palettes_proto_goTypes = nil
	file_pb_palettes_proto_depIdxs = nil
}
