// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/records.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Geographic coordinates (4326)
type Coord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lon           float32                `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat           float32                `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coord) Reset() {
	*x = Coord{}
	mi := &file_pb_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coord) ProtoMessage() {}

func (x *Coord) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coord.ProtoReflect.Descriptor instead.
func (*Coord) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{0}
}

func (x *Coord) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Coord) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

// *
// Geographic linear ring
type LinearRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Coord               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinearRing) Reset() {
	*x = LinearRing{}
	mi := &file_pb_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinearRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearRing) ProtoMessage() {}

func (x *LinearRing) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearRing.ProtoReflect.Descriptor instead.
func (*LinearRing) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{1}
}

func (x *LinearRing) GetPoints() []*Coord {
	if x != nil {
		return x.Points
	}
	return nil
}

// *
// Geographic polygon
type Polygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linearrings   []*LinearRing          `protobuf:"bytes,1,rep,name=linearrings,proto3" json:"linearrings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_pb_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{2}
}

func (x *Polygon) GetLinearrings() []*LinearRing {
	if x != nil {
		return x.Linearrings
	}
	return nil
}

// *
// Geographic AOI
type AOI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polygons      []*Polygon             `protobuf:"bytes,1,rep,name=polygons,proto3" json:"polygons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AOI) Reset() {
	*x = AOI{}
	mi := &file_pb_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AOI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AOI) ProtoMessage() {}

func (x *AOI) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AOI.ProtoReflect.Descriptor instead.
func (*AOI) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{3}
}

func (x *AOI) GetPolygons() []*Polygon {
	if x != nil {
		return x.Polygons
	}
	return nil
}

// *
// Record
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AoiId         string                 `protobuf:"bytes,5,opt,name=aoi_id,json=aoiId,proto3" json:"aoi_id,omitempty"`
	Aoi           *AOI                   `protobuf:"bytes,6,opt,name=aoi,proto3" json:"aoi,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pb_records_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Record) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Record) GetAoiId() string {
	if x != nil {
		return x.AoiId
	}
	return ""
}

func (x *Record) GetAoi() *AOI {
	if x != nil {
		return x.Aoi
	}
	return nil
}

// *
// Structure to create a new record
type NewRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AoiId         string                 `protobuf:"bytes,4,opt,name=aoi_id,json=aoiId,proto3" json:"aoi_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRecord) Reset() {
	*x = NewRecord{}
	mi := &file_pb_records_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRecord) ProtoMessage() {}

func (x *NewRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRecord.ProtoReflect.Descriptor instead.
func (*NewRecord) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{5}
}

func (x *NewRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewRecord) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *NewRecord) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NewRecord) GetAoiId() string {
	if x != nil {
		return x.AoiId
	}
	return ""
}

// *
// List of record ids that are considered separately
type RecordIdList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordIdList) Reset() {
	*x = RecordIdList{}
	mi := &file_pb_records_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordIdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordIdList) ProtoMessage() {}

func (x *RecordIdList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordIdList.ProtoReflect.Descriptor instead.
func (*RecordIdList) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{6}
}

func (x *RecordIdList) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// *
// Records that are considered as a unique, merged record (e.g. all records of a given date, whatever the time of the day)
type GroupedRecords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupedRecords) Reset() {
	*x = GroupedRecords{}
	mi := &file_pb_records_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupedRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedRecords) ProtoMessage() {}

func (x *GroupedRecords) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedRecords.ProtoReflect.Descriptor instead.
func (*GroupedRecords) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{7}
}

func (x *GroupedRecords) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// *
// Record ids that are considered as a unique, merged record (e.g. all records of a given date, whatever the time of the day)
type GroupedRecordIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupedRecordIds) Reset() {
	*x = GroupedRecordIds{}
	mi := &file_pb_records_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupedRecordIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedRecordIds) ProtoMessage() {}

func (x *GroupedRecordIds) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedRecordIds.ProtoReflect.Descriptor instead.
func (*GroupedRecordIds) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{8}
}

func (x *GroupedRecordIds) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// *
// List of groupedRecordIds
type GroupedRecordIdsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*GroupedRecordIds    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupedRecordIdsList) Reset() {
	*x = GroupedRecordIdsList{}
	mi := &file_pb_records_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupedRecordIdsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedRecordIdsList) ProtoMessage() {}

func (x *GroupedRecordIdsList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedRecordIdsList.ProtoReflect.Descriptor instead.
func (*GroupedRecordIdsList) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{9}
}

func (x *GroupedRecordIdsList) GetRecords() []*GroupedRecordIds {
	if x != nil {
		return x.Records
	}
	return nil
}

// *
// Create new records
type CreateRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*NewRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordsRequest) Reset() {
	*x = CreateRecordsRequest{}
	mi := &file_pb_records_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordsRequest) ProtoMessage() {}

func (x *CreateRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordsRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordsRequest) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRecordsRequest) GetRecords() []*NewRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// *
// Returns the ID of the created records
type CreateRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordsResponse) Reset() {
	*x = CreateRecordsResponse{}
	mi := &file_pb_records_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordsResponse) ProtoMessage() {}

func (x *CreateRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordsResponse.ProtoReflect.Descriptor instead.
func (*CreateRecordsResponse) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRecordsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// *
// Get record from its id
type GetRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsRequest) Reset() {
	*x = GetRecordsRequest{}
	mi := &file_pb_records_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsRequest) ProtoMessage() {}

func (x *GetRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecordsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// *
// Return a record
type GetRecordsResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsResponseItem) Reset() {
	*x = GetRecordsResponseItem{}
	mi := &file_pb_records_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsResponseItem) ProtoMessage() {}

func (x *GetRecordsResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsResponseItem.ProtoReflect.Descriptor instead.
func (*GetRecordsResponseItem) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{13}
}

func (x *GetRecordsResponseItem) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// *
// Delete records by ID
type DeleteRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	NoFail        bool                   `protobuf:"varint,2,opt,name=no_fail,json=noFail,proto3" json:"no_fail,omitempty"` // If true, do not fail if some records still have datasets that refer to them and delete the others.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordsRequest) Reset() {
	*x = DeleteRecordsRequest{}
	mi := &file_pb_records_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordsRequest) ProtoMessage() {}

func (x *DeleteRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordsRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordsRequest) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRecordsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeleteRecordsRequest) GetNoFail() bool {
	if x != nil {
		return x.NoFail
	}
	return false
}

// *
// Return the number of deleted records
type DeleteRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nb            int64                  `protobuf:"varint,1,opt,name=nb,proto3" json:"nb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordsResponse) Reset() {
	*x = DeleteRecordsResponse{}
	mi := &file_pb_records_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordsResponse) ProtoMessage() {}

func (x *DeleteRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordsResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordsResponse) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRecordsResponse) GetNb() int64 {
	if x != nil {
		return x.Nb
	}
	return 0
}

// *
// Add the given tags to a set of records
type AddRecordsTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordsTagsRequest) Reset() {
	*x = AddRecordsTagsRequest{}
	mi := &file_pb_records_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordsTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordsTagsRequest) ProtoMessage() {}

func (x *AddRecordsTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordsTagsRequest.ProtoReflect.Descriptor instead.
func (*AddRecordsTagsRequest) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{16}
}

func (x *AddRecordsTagsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *AddRecordsTagsRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// *
// Returns the number of records impacted by the addition
type AddRecordsTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nb            int64                  `protobuf:"varint,1,opt,name=nb,proto3" json:"nb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordsTagsResponse) Reset() {
	*x = AddRecordsTagsResponse{}
	mi := &file_pb_records_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordsTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordsTagsResponse) ProtoMessage() {}

func (x *AddRecordsTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordsTagsResponse.ProtoReflect.Descriptor instead.
func (*AddRecordsTagsResponse) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{17}
}

func (x *AddRecordsTagsResponse) GetNb() int64 {
	if x != nil {
		return x.Nb
	}
	return 0
}

// *
// Remove the given tags for a set of records
type RemoveRecordsTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	TagsKey       []string               `protobuf:"bytes,2,rep,name=tagsKey,proto3" json:"tagsKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRecordsTagsRequest) Reset() {
	*x = RemoveRecordsTagsRequest{}
	mi := &file_pb_records_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRecordsTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRecordsTagsRequest) ProtoMessage() {}

func (x *RemoveRecordsTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRecordsTagsRequest.ProtoReflect.Descriptor instead.
func (*RemoveRecordsTagsRequest) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveRecordsTagsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *RemoveRecordsTagsRequest) GetTagsKey() []string {
	if x != nil {
		return x.TagsKey
	}
	return nil
}

// *
// Returns the number of records impacted by the removal
type RemoveRecordsTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nb            int64                  `protobuf:"varint,1,opt,name=nb,proto3" json:"nb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRecordsTagsResponse) Reset() {
	*x = RemoveRecordsTagsResponse{}
	mi := &file_pb_records_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRecordsTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRecordsTagsResponse) ProtoMessage() {}

func (x *RemoveRecordsTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRecordsTagsResponse.ProtoReflect.Descriptor instead.
func (*RemoveRecordsTagsResponse) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveRecordsTagsResponse) GetNb() int64 {
	if x != nil {
		return x.Nb
	}
	return 0
}

// *
// Create a new AOI
type CreateAOIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aoi           *AOI                   `protobuf:"bytes,1,opt,name=aoi,proto3" json:"aoi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAOIRequest) Reset() {
	*x = CreateAOIRequest{}
	mi := &file_pb_records_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAOIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAOIRequest) ProtoMessage() {}

func (x *CreateAOIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAOIRequest.ProtoReflect.Descriptor instead.
func (*CreateAOIRequest) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{20}
}

func (x *CreateAOIRequest) GetAoi() *AOI {
	if x != nil {
		return x.Aoi
	}
	return nil
}

// *
// Returns the ID of the AOI
type CreateAOIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAOIResponse) Reset() {
	*x = CreateAOIResponse{}
	mi := &file_pb_records_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAOIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAOIResponse) ProtoMessage() {}

func (x *CreateAOIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAOIResponse.ProtoReflect.Descriptor instead.
func (*CreateAOIResponse) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{21}
}

func (x *CreateAOIResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// *
// Request the AOI given its ID
type GetAOIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAOIRequest) Reset() {
	*x = GetAOIRequest{}
	mi := &file_pb_records_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAOIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAOIRequest) ProtoMessage() {}

func (x *GetAOIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAOIRequest.ProtoReflect.Descriptor instead.
func (*GetAOIRequest) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{22}
}

func (x *GetAOIRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// *
// Returns a geometric AOI
type GetAOIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aoi           *AOI                   `protobuf:"bytes,1,opt,name=aoi,proto3" json:"aoi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAOIResponse) Reset() {
	*x = GetAOIResponse{}
	mi := &file_pb_records_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAOIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAOIResponse) ProtoMessage() {}

func (x *GetAOIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAOIResponse.ProtoReflect.Descriptor instead.
func (*GetAOIResponse) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{23}
}

func (x *GetAOIResponse) GetAoi() *AOI {
	if x != nil {
		return x.Aoi
	}
	return nil
}

// *
// Request to find the list of records corresponding to multiple filters (inclusive)
type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                           // Name pattern (support * and ? for all or any characters and trailing (?i) for case-insensitiveness)
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // cf RecordFilters
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`                                                   // cf RecordFilters
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`                                                         // cf RecordFilters
	Aoi           *AOI                   `protobuf:"bytes,8,opt,name=aoi,proto3" json:"aoi,omitempty"`                                                                             // cf RecordFiltersWithAOI
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	WithAoi       bool                   `protobuf:"varint,9,opt,name=with_aoi,json=withAoi,proto3" json:"with_aoi,omitempty"` // Also returns the AOI (may be big)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_pb_records_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{24}
}

func (x *ListRecordsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRecordsRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListRecordsRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *ListRecordsRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

func (x *ListRecordsRequest) GetAoi() *AOI {
	if x != nil {
		return x.Aoi
	}
	return nil
}

func (x *ListRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsRequest) GetWithAoi() bool {
	if x != nil {
		return x.WithAoi
	}
	return false
}

// *
type ListRecordsResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponseItem) Reset() {
	*x = ListRecordsResponseItem{}
	mi := &file_pb_records_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponseItem) ProtoMessage() {}

func (x *ListRecordsResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponseItem.ProtoReflect.Descriptor instead.
func (*ListRecordsResponseItem) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{25}
}

func (x *ListRecordsResponseItem) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// *
// RecordFilters defines some filters to identify records
type RecordFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          map[string]string      `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Tags of the records
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`                                                   // Minimum date of the records
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`                                                         // Maximum date of the records
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFilters) Reset() {
	*x = RecordFilters{}
	mi := &file_pb_records_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFilters) ProtoMessage() {}

func (x *RecordFilters) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFilters.ProtoReflect.Descriptor instead.
func (*RecordFilters) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{26}
}

func (x *RecordFilters) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RecordFilters) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *RecordFilters) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

// *
// RecordFiltersWithAOI defines some filters to identify records, including an AOI in geometric coordinates
type RecordFiltersWithAOI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *RecordFilters         `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	Aoi           *AOI                   `protobuf:"bytes,2,opt,name=aoi,proto3" json:"aoi,omitempty"` // Geometric coordinates of an AOI that intersects the AOI of the records
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFiltersWithAOI) Reset() {
	*x = RecordFiltersWithAOI{}
	mi := &file_pb_records_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFiltersWithAOI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFiltersWithAOI) ProtoMessage() {}

func (x *RecordFiltersWithAOI) ProtoReflect() protoreflect.Message {
	mi := &file_pb_records_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFiltersWithAOI.ProtoReflect.Descriptor instead.
func (*RecordFiltersWithAOI) Descriptor() ([]byte, []int) {
	return file_pb_records_proto_rawDescGZIP(), []int{27}
}

func (x *RecordFiltersWithAOI) GetFilters() *RecordFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *RecordFiltersWithAOI) GetAoi() *AOI {
	if x != nil {
		return x.Aoi
	}
	return nil
}

var File_pb_records_proto protoreflect.FileDescriptor

const file_pb_records_proto_rawDesc = "" +
	"\n" +
	"\x10pb/records.proto\x12\ageocube\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x05Coord\x12\x10\n" +
	"\x03lon\x18\x01 \x01(\x02R\x03lon\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x02R\x03lat\"4\n" +
	"\n" +
	"LinearRing\x12&\n" +
	"\x06points\x18\x01 \x03(\v2\x0e.geocube.CoordR\x06points\"@\n" +
	"\aPolygon\x125\n" +
	"\vlinearrings\x18\x01 \x03(\v2\x13.geocube.LinearRingR\vlinearrings\"3\n" +
	"\x03AOI\x12,\n" +
	"\bpolygons\x18\x01 \x03(\v2\x10.geocube.PolygonR\bpolygons\"\xfb\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12-\n" +
	"\x04tags\x18\x04 \x03(\v2\x19.geocube.Record.TagsEntryR\x04tags\x12\x15\n" +
	"\x06aoi_id\x18\x05 \x01(\tR\x05aoiId\x12\x1e\n" +
	"\x03aoi\x18\x06 \x01(\v2\f.geocube.AOIR\x03aoi\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\tNewRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x120\n" +
	"\x04tags\x18\x03 \x03(\v2\x1c.geocube.NewRecord.TagsEntryR\x04tags\x12\x15\n" +
	"\x06aoi_id\x18\x04 \x01(\tR\x05aoiId\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\fRecordIdList\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\";\n" +
	"\x0eGroupedRecords\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.geocube.RecordR\arecords\"$\n" +
	"\x10GroupedRecordIds\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"K\n" +
	"\x14GroupedRecordIdsList\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.geocube.GroupedRecordIdsR\arecords\"D\n" +
	"\x14CreateRecordsRequest\x12,\n" +
	"\arecords\x18\x01 \x03(\v2\x12.geocube.NewRecordR\arecords\")\n" +
	"\x15CreateRecordsResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"%\n" +
	"\x11GetRecordsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"A\n" +
	"\x16GetRecordsResponseItem\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.geocube.RecordR\x06record\"A\n" +
	"\x14DeleteRecordsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x17\n" +
	"\ano_fail\x18\x02 \x01(\bR\x06noFail\"'\n" +
	"\x15DeleteRecordsResponse\x12\x0e\n" +
	"\x02nb\x18\x01 \x01(\x03R\x02nb\"\xa0\x01\n" +
	"\x15AddRecordsTagsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12<\n" +
	"\x04tags\x18\x02 \x03(\v2(.geocube.AddRecordsTagsRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x16AddRecordsTagsResponse\x12\x0e\n" +
	"\x02nb\x18\x01 \x01(\x03R\x02nb\"F\n" +
	"\x18RemoveRecordsTagsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x18\n" +
	"\atagsKey\x18\x02 \x03(\tR\atagsKey\"+\n" +
	"\x19RemoveRecordsTagsResponse\x12\x0e\n" +
	"\x02nb\x18\x01 \x01(\x03R\x02nb\"2\n" +
	"\x10CreateAOIRequest\x12\x1e\n" +
	"\x03aoi\x18\x01 \x01(\v2\f.geocube.AOIR\x03aoi\"#\n" +
	"\x11CreateAOIResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rGetAOIRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x0eGetAOIResponse\x12\x1e\n" +
	"\x03aoi\x18\x01 \x01(\v2\f.geocube.AOIR\x03aoi\"\xef\x02\n" +
	"\x12ListRecordsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\x04tags\x18\x03 \x03(\v2%.geocube.ListRecordsRequest.TagsEntryR\x04tags\x127\n" +
	"\tfrom_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bfromTime\x123\n" +
	"\ato_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06toTime\x12\x1e\n" +
	"\x03aoi\x18\b \x01(\v2\f.geocube.AOIR\x03aoi\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x19\n" +
	"\bwith_aoi\x18\t \x01(\bR\awithAoi\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x17ListRecordsResponseItem\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.geocube.RecordR\x06record\"\xec\x01\n" +
	"\rRecordFilters\x124\n" +
	"\x04tags\x18\x01 \x03(\v2 .geocube.RecordFilters.TagsEntryR\x04tags\x127\n" +
	"\tfrom_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromTime\x123\n" +
	"\ato_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toTime\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x14RecordFiltersWithAOI\x120\n" +
	"\afilters\x18\x01 \x01(\v2\x16.geocube.RecordFiltersR\afilters\x12\x1e\n" +
	"\x03aoi\x18\x02 \x01(\v2\f.geocube.AOIR\x03aoiB\x0eZ\f./pb;geocubeb\x06proto3"

var (
	file_pb_records_proto_rawDescOnce sync.Once
	file_pb_records_proto_rawDescData []byte
)

func file_pb_records_proto_rawDescGZIP() []byte {
	file_pb_records_proto_rawDescOnce.Do(func() {
		file_pb_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_records_proto_rawDesc), len(file_pb_records_proto_rawDesc)))
	})
	return file_pb_records_proto_rawDescData
}

var file_pb_records_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_pb_records_proto_goTypes = []any{
	(*Coord)(nil),                     // 0: geocube.Coord
	(*LinearRing)(nil),                // 1: geocube.LinearRing
	(*Polygon)(nil),                   // 2: geocube.Polygon
	(*AOI)(nil),                       // 3: geocube.AOI
	(*Record)(nil),                    // 4: geocube.Record
	(*NewRecord)(nil),                 // 5: geocube.NewRecord
	(*RecordIdList)(nil),              // 6: geocube.RecordIdList
	(*GroupedRecords)(nil),            // 7: geocube.GroupedRecords
	(*GroupedRecordIds)(nil),          // 8: geocube.GroupedRecordIds
	(*GroupedRecordIdsList)(nil),      // 9: geocube.GroupedRecordIdsList
	(*CreateRecordsRequest)(nil),      // 10: geocube.CreateRecordsRequest
	(*CreateRecordsResponse)(nil),     // 11: geocube.CreateRecordsResponse
	(*GetRecordsRequest)(nil),         // 12: geocube.GetRecordsRequest
	(*GetRecordsResponseItem)(nil),    // 13: geocube.GetRecordsResponseItem
	(*DeleteRecordsRequest)(nil),      // 14: geocube.DeleteRecordsRequest
	(*DeleteRecordsResponse)(nil),     // 15: geocube.DeleteRecordsResponse
	(*AddRecordsTagsRequest)(nil),     // 16: geocube.AddRecordsTagsRequest
	(*AddRecordsTagsResponse)(nil),    // 17: geocube.AddRecordsTagsResponse
	(*RemoveRecordsTagsRequest)(nil),  // 18: geocube.RemoveRecordsTagsRequest
	(*RemoveRecordsTagsResponse)(nil), // 19: geocube.RemoveRecordsTagsResponse
	(*CreateAOIRequest)(nil),          // 20: geocube.CreateAOIRequest
	(*CreateAOIResponse)(nil),         // 21: geocube.CreateAOIResponse
	(*GetAOIRequest)(nil),             // 22: geocube.GetAOIRequest
	(*GetAOIResponse)(nil),            // 23: geocube.GetAOIResponse
	(*ListRecordsRequest)(nil),        // 24: geocube.ListRecordsRequest
	(*ListRecordsResponseItem)(nil),   // 25: geocube.ListRecordsResponseItem
	(*RecordFilters)(nil),             // 26: geocube.RecordFilters
	(*RecordFiltersWithAOI)(nil),      // 27: geocube.RecordFiltersWithAOI
	nil,                               // 28: geocube.Record.TagsEntry
	nil,                               // 29: geocube.NewRecord.TagsEntry
	nil,                               // 30: geocube.AddRecordsTagsRequest.TagsEntry
	nil,                               // 31: geocube.ListRecordsRequest.TagsEntry
	nil,                               // 32: geocube.RecordFilters.TagsEntry
	(*timestamppb.Timestamp)(nil),     // 33: google.protobuf.Timestamp
}
var file_pb_records_proto_depIdxs = []int32{
	0,  // 0: geocube.LinearRing.points:type_name -> geocube.Coord
	1,  // 1: geocube.Polygon.linearrings:type_name -> geocube.LinearRing
	2,  // 2: geocube.AOI.polygons:type_name -> geocube.Polygon
	33, // 3: geocube.Record.time:type_name -> google.protobuf.Timestamp
	28, // 4: geocube.Record.tags:type_name -> geocube.Record.TagsEntry
	3,  // 5: geocube.Record.aoi:type_name -> geocube.AOI
	33, // 6: geocube.NewRecord.time:type_name -> google.protobuf.Timestamp
	29, // 7: geocube.NewRecord.tags:type_name -> geocube.NewRecord.TagsEntry
	4,  // 8: geocube.GroupedRecords.records:type_name -> geocube.Record
	8,  // 9: geocube.GroupedRecordIdsList.records:type_name -> geocube.GroupedRecordIds
	5,  // 10: geocube.CreateRecordsRequest.records:type_name -> geocube.NewRecord
	4,  // 11: geocube.GetRecordsResponseItem.record:type_name -> geocube.Record
	30, // 12: geocube.AddRecordsTagsRequest.tags:type_name -> geocube.AddRecordsTagsRequest.TagsEntry
	3,  // 13: geocube.CreateAOIRequest.aoi:type_name -> geocube.AOI
	3,  // 14: geocube.GetAOIResponse.aoi:type_name -> geocube.AOI
	31, // 15: geocube.ListRecordsRequest.tags:type_name -> geocube.ListRecordsRequest.TagsEntry
	33, // 16: geocube.ListRecordsRequest.from_time:type_name -> google.protobuf.Timestamp
	33, // 17: geocube.ListRecordsRequest.to_time:type_name -> google.protobuf.Timestamp
	3,  // 18: geocube.ListRecordsRequest.aoi:type_name -> geocube.AOI
	4,  // 19: geocube.ListRecordsResponseItem.record:type_name -> geocube.Record
	32, // 20: geocube.RecordFilters.tags:type_name -> geocube.RecordFilters.TagsEntry
	33, // 21: geocube.RecordFilters.from_time:type_name -> google.protobuf.Timestamp
	33, // 22: geocube.RecordFilters.to_time:type_name -> google.protobuf.Timestamp
	26, // 23: geocube.RecordFiltersWithAOI.filters:type_name -> geocube.RecordFilters
	3,  // 24: geocube.RecordFiltersWithAOI.aoi:type_name -> geocube.AOI
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_pb_records_proto_init() }
func file_pb_records_proto_init() {
	if File_pb_records_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_records_proto_rawDesc), len(file_pb_records_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_records_proto_goTypes,
		DependencyIndexes: file_pb_records_proto_depIdxs,
		MessageInfos:      file_pb_records_proto_msgTypes,
	}.Build()
	File_pb_records_proto = out.File
	file_pb_records_proto_goTypes = nil
	file_pb_records_proto_depIdxs = nil
}
