// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: pb/variables.proto

package geocube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Resampling algorithms (supported by GDAL)
type Resampling int32

const (
	Resampling_UNDEFINED   Resampling = 0
	Resampling_NEAR        Resampling = 1
	Resampling_BILINEAR    Resampling = 2
	Resampling_CUBIC       Resampling = 3
	Resampling_CUBICSPLINE Resampling = 4
	Resampling_LANCZOS     Resampling = 5
	Resampling_AVERAGE     Resampling = 6
	Resampling_MODE        Resampling = 7
	Resampling_MAX         Resampling = 8
	Resampling_MIN         Resampling = 9
	Resampling_MED         Resampling = 10
	Resampling_Q1          Resampling = 11
	Resampling_Q3          Resampling = 12
)

// Enum value maps for Resampling.
var (
	Resampling_name = map[int32]string{
		0:  "UNDEFINED",
		1:  "NEAR",
		2:  "BILINEAR",
		3:  "CUBIC",
		4:  "CUBICSPLINE",
		5:  "LANCZOS",
		6:  "AVERAGE",
		7:  "MODE",
		8:  "MAX",
		9:  "MIN",
		10: "MED",
		11: "Q1",
		12: "Q3",
	}
	Resampling_value = map[string]int32{
		"UNDEFINED":   0,
		"NEAR":        1,
		"BILINEAR":    2,
		"CUBIC":       3,
		"CUBICSPLINE": 4,
		"LANCZOS":     5,
		"AVERAGE":     6,
		"MODE":        7,
		"MAX":         8,
		"MIN":         9,
		"MED":         10,
		"Q1":          11,
		"Q3":          12,
	}
)

func (x Resampling) Enum() *Resampling {
	p := new(Resampling)
	*p = x
	return p
}

func (x Resampling) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resampling) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_variables_proto_enumTypes[0].Descriptor()
}

func (Resampling) Type() protoreflect.EnumType {
	return &file_pb_variables_proto_enumTypes[0]
}

func (x Resampling) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resampling.Descriptor instead.
func (Resampling) EnumDescriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{0}
}

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Null at creation
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_pb_variables_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// *
// Variable
type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                     // Internal UUID-4 of the variable (ignored at creation)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                 // Name of the variable (Alpha-numerics characters, dashs, dots and underscores)
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`                                                                 // Unit of the variable (for user information only)
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                                   // Description of the variable (for user information only)
	Dformat       *DataFormat            `protobuf:"bytes,5,opt,name=dformat,proto3" json:"dformat,omitempty"`                                                           // Format of the data. Range.Min and Range.Max are used for data mapping from internal data format of a dataset (See IndexDatasets for more details), DType and NoData are used for the outputs of GetCube.
	Bands         []string               `protobuf:"bytes,6,rep,name=bands,proto3" json:"bands,omitempty"`                                                               // Name of each band. Can be empty when the variable refers to only one band, must be unique otherwise.
	Palette       string                 `protobuf:"bytes,7,opt,name=palette,proto3" json:"palette,omitempty"`                                                           // Name of the default palette for color rendering.
	ResamplingAlg Resampling             `protobuf:"varint,8,opt,name=resampling_alg,json=resamplingAlg,proto3,enum=geocube.Resampling" json:"resampling_alg,omitempty"` // Default resampling algorithm in case of reprojection.
	Instances     []*Instance            `protobuf:"bytes,9,rep,name=instances,proto3" json:"instances,omitempty"`                                                       // List of instances of the variable (ignored at creation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_pb_variables_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{1}
}

func (x *Variable) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Variable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Variable) GetDformat() *DataFormat {
	if x != nil {
		return x.Dformat
	}
	return nil
}

func (x *Variable) GetBands() []string {
	if x != nil {
		return x.Bands
	}
	return nil
}

func (x *Variable) GetPalette() string {
	if x != nil {
		return x.Palette
	}
	return ""
}

func (x *Variable) GetResamplingAlg() Resampling {
	if x != nil {
		return x.ResamplingAlg
	}
	return Resampling_UNDEFINED
}

func (x *Variable) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

// *
// Define a new variable.
// Return an error if the name already exists.
type CreateVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *Variable              `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVariableRequest) Reset() {
	*x = CreateVariableRequest{}
	mi := &file_pb_variables_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariableRequest) ProtoMessage() {}

func (x *CreateVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariableRequest.ProtoReflect.Descriptor instead.
func (*CreateVariableRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVariableRequest) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

// *
// Return the id of the new variable.
type CreateVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVariableResponse) Reset() {
	*x = CreateVariableResponse{}
	mi := &file_pb_variables_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariableResponse) ProtoMessage() {}

func (x *CreateVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariableResponse.ProtoReflect.Descriptor instead.
func (*CreateVariableResponse) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVariableResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// *
// Instantiate a variable.
// Return an error if the instance_name already exists for this variable.
type InstantiateVariableRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VariableId       string                 `protobuf:"bytes,1,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
	InstanceName     string                 `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	InstanceMetadata map[string]string      `protobuf:"bytes,3,rep,name=instance_metadata,json=instanceMetadata,proto3" json:"instance_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InstantiateVariableRequest) Reset() {
	*x = InstantiateVariableRequest{}
	mi := &file_pb_variables_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstantiateVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantiateVariableRequest) ProtoMessage() {}

func (x *InstantiateVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantiateVariableRequest.ProtoReflect.Descriptor instead.
func (*InstantiateVariableRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{4}
}

func (x *InstantiateVariableRequest) GetVariableId() string {
	if x != nil {
		return x.VariableId
	}
	return ""
}

func (x *InstantiateVariableRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *InstantiateVariableRequest) GetInstanceMetadata() map[string]string {
	if x != nil {
		return x.InstanceMetadata
	}
	return nil
}

// *
// Return the new instance (its id, name and metadata)
type InstantiateVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstantiateVariableResponse) Reset() {
	*x = InstantiateVariableResponse{}
	mi := &file_pb_variables_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstantiateVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantiateVariableResponse) ProtoMessage() {}

func (x *InstantiateVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantiateVariableResponse.ProtoReflect.Descriptor instead.
func (*InstantiateVariableResponse) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{5}
}

func (x *InstantiateVariableResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// *
// Read a variable given either its id, its name or the id of one of its instance
type GetVariableRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetVariableRequest_Id
	//	*GetVariableRequest_Name
	//	*GetVariableRequest_InstanceId
	Identifier    isGetVariableRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableRequest) Reset() {
	*x = GetVariableRequest{}
	mi := &file_pb_variables_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableRequest) ProtoMessage() {}

func (x *GetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableRequest.ProtoReflect.Descriptor instead.
func (*GetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{6}
}

func (x *GetVariableRequest) GetIdentifier() isGetVariableRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetVariableRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetVariableRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetVariableRequest) GetName() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetVariableRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *GetVariableRequest) GetInstanceId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetVariableRequest_InstanceId); ok {
			return x.InstanceId
		}
	}
	return ""
}

type isGetVariableRequest_Identifier interface {
	isGetVariableRequest_Identifier()
}

type GetVariableRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"` // UUID-4 of the variable
}

type GetVariableRequest_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"` // Name of the variable
}

type GetVariableRequest_InstanceId struct {
	InstanceId string `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3,oneof"` // UUID-4 of an instance
}

func (*GetVariableRequest_Id) isGetVariableRequest_Identifier() {}

func (*GetVariableRequest_Name) isGetVariableRequest_Identifier() {}

func (*GetVariableRequest_InstanceId) isGetVariableRequest_Identifier() {}

// *
// Return the variable and its instances
type GetVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *Variable              `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableResponse) Reset() {
	*x = GetVariableResponse{}
	mi := &file_pb_variables_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableResponse) ProtoMessage() {}

func (x *GetVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableResponse.ProtoReflect.Descriptor instead.
func (*GetVariableResponse) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{7}
}

func (x *GetVariableResponse) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

// *
// List variables given a name pattern
type ListVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // Pattern of the name of the variable (support * and ? for all or any characters, (?i) suffix for case-insensitiveness)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // Limit the number of variables returned
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`   // Navigate through results (start at 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVariablesRequest) Reset() {
	*x = ListVariablesRequest{}
	mi := &file_pb_variables_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariablesRequest) ProtoMessage() {}

func (x *ListVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariablesRequest.ProtoReflect.Descriptor instead.
func (*ListVariablesRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{8}
}

func (x *ListVariablesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListVariablesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVariablesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// *
// Return a stream of variables
type ListVariablesResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *Variable              `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVariablesResponseItem) Reset() {
	*x = ListVariablesResponseItem{}
	mi := &file_pb_variables_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVariablesResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariablesResponseItem) ProtoMessage() {}

func (x *ListVariablesResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariablesResponseItem.ProtoReflect.Descriptor instead.
func (*ListVariablesResponseItem) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{9}
}

func (x *ListVariablesResponseItem) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

// *
// Update the non-critical fields of a variable
// Return an error if the name is to be updated but the new name already exists.
type UpdateVariableRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                     // UUID-4 of the variable to update
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                 // [Optional] New name of the variable. Empty to ignore
	Unit          *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`                                                                 // [Optional] New unit of the variable. Empty to ignore
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                                   // [Optional] New description of the variable. Empty to ignore
	Palette       *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=palette,proto3" json:"palette,omitempty"`                                                           // [Optional] New default palette of the variable. Empty to ignore
	ResamplingAlg Resampling              `protobuf:"varint,6,opt,name=resampling_alg,json=resamplingAlg,proto3,enum=geocube.Resampling" json:"resampling_alg,omitempty"` // [Optional] New default resampling algorithm of the variable. UNDEFINED to ignore
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVariableRequest) Reset() {
	*x = UpdateVariableRequest{}
	mi := &file_pb_variables_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariableRequest) ProtoMessage() {}

func (x *UpdateVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariableRequest.ProtoReflect.Descriptor instead.
func (*UpdateVariableRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVariableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVariableRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateVariableRequest) GetUnit() *wrapperspb.StringValue {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *UpdateVariableRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateVariableRequest) GetPalette() *wrapperspb.StringValue {
	if x != nil {
		return x.Palette
	}
	return nil
}

func (x *UpdateVariableRequest) GetResamplingAlg() Resampling {
	if x != nil {
		return x.ResamplingAlg
	}
	return Resampling_UNDEFINED
}

// *
// Return nothing
type UpdateVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVariableResponse) Reset() {
	*x = UpdateVariableResponse{}
	mi := &file_pb_variables_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariableResponse) ProtoMessage() {}

func (x *UpdateVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariableResponse.ProtoReflect.Descriptor instead.
func (*UpdateVariableResponse) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{11}
}

// *
// Update an instance
// Return an error if the name is to be updated but the new name already exists.
type UpdateInstanceRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                                                // UUID-4 of the instance to update
	Name            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                                            // [Optional] New name of the variable. Empty to ignore
	AddMetadata     map[string]string       `protobuf:"bytes,3,rep,name=add_metadata,json=addMetadata,proto3" json:"add_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Pairs of metadata (key, values) to be inserted or updated
	DelMetadataKeys []string                `protobuf:"bytes,4,rep,name=del_metadata_keys,json=delMetadataKeys,proto3" json:"del_metadata_keys,omitempty"`                                                             // Metadata keys to be deleted
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateInstanceRequest) Reset() {
	*x = UpdateInstanceRequest{}
	mi := &file_pb_variables_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInstanceRequest) ProtoMessage() {}

func (x *UpdateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInstanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInstanceRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateInstanceRequest) GetAddMetadata() map[string]string {
	if x != nil {
		return x.AddMetadata
	}
	return nil
}

func (x *UpdateInstanceRequest) GetDelMetadataKeys() []string {
	if x != nil {
		return x.DelMetadataKeys
	}
	return nil
}

// *
// Return nothing
type UpdateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInstanceResponse) Reset() {
	*x = UpdateInstanceResponse{}
	mi := &file_pb_variables_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInstanceResponse) ProtoMessage() {}

func (x *UpdateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInstanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{13}
}

// *
// Delete a variable
// Return an error if the variable has still instances
type DeleteVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID-4 of the variable to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVariableRequest) Reset() {
	*x = DeleteVariableRequest{}
	mi := &file_pb_variables_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableRequest) ProtoMessage() {}

func (x *DeleteVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableRequest.ProtoReflect.Descriptor instead.
func (*DeleteVariableRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteVariableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// *
// Return nothing
type DeleteVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVariableResponse) Reset() {
	*x = DeleteVariableResponse{}
	mi := &file_pb_variables_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableResponse) ProtoMessage() {}

func (x *DeleteVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableResponse.ProtoReflect.Descriptor instead.
func (*DeleteVariableResponse) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{15}
}

// *
// Delete an instance
// Return an error if the instance is linked to datasets.
type DeleteInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID-4 of the instance to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceRequest) Reset() {
	*x = DeleteInstanceRequest{}
	mi := &file_pb_variables_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceRequest) ProtoMessage() {}

func (x *DeleteInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstanceRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// *
// Return nothing
type DeleteInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceResponse) Reset() {
	*x = DeleteInstanceResponse{}
	mi := &file_pb_variables_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceResponse) ProtoMessage() {}

func (x *DeleteInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInstanceResponse) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{17}
}

// *
// Define a color mapping from a value [0-1] to a RGBA value.
type ColorPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float32                `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	R             uint32                 `protobuf:"varint,2,opt,name=r,proto3" json:"r,omitempty"`
	G             uint32                 `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	B             uint32                 `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`
	A             uint32                 `protobuf:"varint,5,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorPoint) Reset() {
	*x = ColorPoint{}
	mi := &file_pb_variables_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorPoint) ProtoMessage() {}

func (x *ColorPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorPoint.ProtoReflect.Descriptor instead.
func (*ColorPoint) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{18}
}

func (x *ColorPoint) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ColorPoint) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *ColorPoint) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *ColorPoint) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *ColorPoint) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

// *
// Define a palette with a name and a set of colorPoint.
// Maps all values in [0,1] to an RGBA value, using piecewise curve defined by colorPoints.
// All intermediate values are linearly interpolated.
type Palette struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // Name of the palette (Alpha-numerics characters, dots, dashes and underscores are supported)
	Colors        []*ColorPoint          `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty"` // Set of colorPoints. At least two points must be defined, corresponding to value=0 and value=1.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Palette) Reset() {
	*x = Palette{}
	mi := &file_pb_variables_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Palette) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Palette) ProtoMessage() {}

func (x *Palette) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Palette.ProtoReflect.Descriptor instead.
func (*Palette) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{19}
}

func (x *Palette) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Palette) GetColors() []*ColorPoint {
	if x != nil {
		return x.Colors
	}
	return nil
}

// *
// Create a new palette or update it if already exists (provided replace=True)
type CreatePaletteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Palette       *Palette               `protobuf:"bytes,1,opt,name=palette,proto3" json:"palette,omitempty"`  // Palette to be created
	Replace       bool                   `protobuf:"varint,2,opt,name=replace,proto3" json:"replace,omitempty"` // Replace the current existing palette if exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaletteRequest) Reset() {
	*x = CreatePaletteRequest{}
	mi := &file_pb_variables_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaletteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaletteRequest) ProtoMessage() {}

func (x *CreatePaletteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaletteRequest.ProtoReflect.Descriptor instead.
func (*CreatePaletteRequest) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{20}
}

func (x *CreatePaletteRequest) GetPalette() *Palette {
	if x != nil {
		return x.Palette
	}
	return nil
}

func (x *CreatePaletteRequest) GetReplace() bool {
	if x != nil {
		return x.Replace
	}
	return false
}

// *
// Return nothing.
type CreatePaletteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaletteResponse) Reset() {
	*x = CreatePaletteResponse{}
	mi := &file_pb_variables_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaletteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaletteResponse) ProtoMessage() {}

func (x *CreatePaletteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_variables_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaletteResponse.ProtoReflect.Descriptor instead.
func (*CreatePaletteResponse) Descriptor() ([]byte, []int) {
	return file_pb_variables_proto_rawDescGZIP(), []int{21}
}

var File_pb_variables_proto protoreflect.FileDescriptor

const file_pb_variables_proto_rawDesc = "" +
	"\n" +
	"\x12pb/variables.proto\x12\ageocube\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13pb/dataformat.proto\"\xa8\x01\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12;\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1f.geocube.Instance.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x02\n" +
	"\bVariable\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12-\n" +
	"\adformat\x18\x05 \x01(\v2\x13.geocube.DataFormatR\adformat\x12\x14\n" +
	"\x05bands\x18\x06 \x03(\tR\x05bands\x12\x18\n" +
	"\apalette\x18\a \x01(\tR\apalette\x12:\n" +
	"\x0eresampling_alg\x18\b \x01(\x0e2\x13.geocube.ResamplingR\rresamplingAlg\x12/\n" +
	"\tinstances\x18\t \x03(\v2\x11.geocube.InstanceR\tinstances\"F\n" +
	"\x15CreateVariableRequest\x12-\n" +
	"\bvariable\x18\x01 \x01(\v2\x11.geocube.VariableR\bvariable\"(\n" +
	"\x16CreateVariableResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8f\x02\n" +
	"\x1aInstantiateVariableRequest\x12\x1f\n" +
	"\vvariable_id\x18\x01 \x01(\tR\n" +
	"variableId\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12f\n" +
	"\x11instance_metadata\x18\x03 \x03(\v29.geocube.InstantiateVariableRequest.InstanceMetadataEntryR\x10instanceMetadata\x1aC\n" +
	"\x15InstanceMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x1bInstantiateVariableResponse\x12-\n" +
	"\binstance\x18\x01 \x01(\v2\x11.geocube.InstanceR\binstance\"m\n" +
	"\x12GetVariableRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x12!\n" +
	"\vinstance_id\x18\x03 \x01(\tH\x00R\n" +
	"instanceIdB\f\n" +
	"\n" +
	"identifier\"D\n" +
	"\x13GetVariableResponse\x12-\n" +
	"\bvariable\x18\x01 \x01(\v2\x11.geocube.VariableR\bvariable\"T\n" +
	"\x14ListVariablesRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"J\n" +
	"\x19ListVariablesResponseItem\x12-\n" +
	"\bvariable\x18\x01 \x01(\v2\x11.geocube.VariableR\bvariable\"\xbf\x02\n" +
	"\x15UpdateVariableRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x120\n" +
	"\x04unit\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x04unit\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x126\n" +
	"\apalette\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\apalette\x12:\n" +
	"\x0eresampling_alg\x18\x06 \x01(\x0e2\x13.geocube.ResamplingR\rresamplingAlg\"\x18\n" +
	"\x16UpdateVariableResponse\"\x99\x02\n" +
	"\x15UpdateInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x12R\n" +
	"\fadd_metadata\x18\x03 \x03(\v2/.geocube.UpdateInstanceRequest.AddMetadataEntryR\vaddMetadata\x12*\n" +
	"\x11del_metadata_keys\x18\x04 \x03(\tR\x0fdelMetadataKeys\x1a>\n" +
	"\x10AddMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x16UpdateInstanceResponse\"'\n" +
	"\x15DeleteVariableRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteVariableResponse\"'\n" +
	"\x15DeleteInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteInstanceResponse\"Z\n" +
	"\n" +
	"colorPoint\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x02R\x05value\x12\f\n" +
	"\x01r\x18\x02 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x03 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x04 \x01(\rR\x01b\x12\f\n" +
	"\x01a\x18\x05 \x01(\rR\x01a\"J\n" +
	"\aPalette\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06colors\x18\x02 \x03(\v2\x13.geocube.colorPointR\x06colors\"\\\n" +
	"\x14CreatePaletteRequest\x12*\n" +
	"\apalette\x18\x01 \x01(\v2\x10.geocube.PaletteR\apalette\x12\x18\n" +
	"\areplace\x18\x02 \x01(\bR\areplace\"\x17\n" +
	"\x15CreatePaletteResponse*\x9e\x01\n" +
	"\n" +
	"Resampling\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\b\n" +
	"\x04NEAR\x10\x01\x12\f\n" +
	"\bBILINEAR\x10\x02\x12\t\n" +
	"\x05CUBIC\x10\x03\x12\x0f\n" +
	"\vCUBICSPLINE\x10\x04\x12\v\n" +
	"\aLANCZOS\x10\x05\x12\v\n" +
	"\aAVERAGE\x10\x06\x12\b\n" +
	"\x04MODE\x10\a\x12\a\n" +
	"\x03MAX\x10\b\x12\a\n" +
	"\x03MIN\x10\t\x12\a\n" +
	"\x03MED\x10\n" +
	"\x12\x06\n" +
	"\x02Q1\x10\v\x12\x06\n" +
	"\x02Q3\x10\fB\x0eZ\f./pb;geocubeb\x06proto3"

var (
	file_pb_variables_proto_rawDescOnce sync.Once
	file_pb_variables_proto_rawDescData []byte
)

func file_pb_variables_proto_rawDescGZIP() []byte {
	file_pb_variables_proto_rawDescOnce.Do(func() {
		file_pb_variables_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_variables_proto_rawDesc), len(file_pb_variables_proto_rawDesc)))
	})
	return file_pb_variables_proto_rawDescData
}

var file_pb_variables_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_variables_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pb_variables_proto_goTypes = []any{
	(Resampling)(0),                     // 0: geocube.Resampling
	(*Instance)(nil),                    // 1: geocube.Instance
	(*Variable)(nil),                    // 2: geocube.Variable
	(*CreateVariableRequest)(nil),       // 3: geocube.CreateVariableRequest
	(*CreateVariableResponse)(nil),      // 4: geocube.CreateVariableResponse
	(*InstantiateVariableRequest)(nil),  // 5: geocube.InstantiateVariableRequest
	(*InstantiateVariableResponse)(nil), // 6: geocube.InstantiateVariableResponse
	(*GetVariableRequest)(nil),          // 7: geocube.GetVariableRequest
	(*GetVariableResponse)(nil),         // 8: geocube.GetVariableResponse
	(*ListVariablesRequest)(nil),        // 9: geocube.ListVariablesRequest
	(*ListVariablesResponseItem)(nil),   // 10: geocube.ListVariablesResponseItem
	(*UpdateVariableRequest)(nil),       // 11: geocube.UpdateVariableRequest
	(*UpdateVariableResponse)(nil),      // 12: geocube.UpdateVariableResponse
	(*UpdateInstanceRequest)(nil),       // 13: geocube.UpdateInstanceRequest
	(*UpdateInstanceResponse)(nil),      // 14: geocube.UpdateInstanceResponse
	(*DeleteVariableRequest)(nil),       // 15: geocube.DeleteVariableRequest
	(*DeleteVariableResponse)(nil),      // 16: geocube.DeleteVariableResponse
	(*DeleteInstanceRequest)(nil),       // 17: geocube.DeleteInstanceRequest
	(*DeleteInstanceResponse)(nil),      // 18: geocube.DeleteInstanceResponse
	(*ColorPoint)(nil),                  // 19: geocube.colorPoint
	(*Palette)(nil),                     // 20: geocube.Palette
	(*CreatePaletteRequest)(nil),        // 21: geocube.CreatePaletteRequest
	(*CreatePaletteResponse)(nil),       // 22: geocube.CreatePaletteResponse
	nil,                                 // 23: geocube.Instance.MetadataEntry
	nil,                                 // 24: geocube.InstantiateVariableRequest.InstanceMetadataEntry
	nil,                                 // 25: geocube.UpdateInstanceRequest.AddMetadataEntry
	(*DataFormat)(nil),                  // 26: geocube.DataFormat
	(*wrapperspb.StringValue)(nil),      // 27: google.protobuf.StringValue
}
var file_pb_variables_proto_depIdxs = []int32{
	23, // 0: geocube.Instance.metadata:type_name -> geocube.Instance.MetadataEntry
	26, // 1: geocube.Variable.dformat:type_name -> geocube.DataFormat
	0,  // 2: geocube.Variable.resampling_alg:type_name -> geocube.Resampling
	1,  // 3: geocube.Variable.instances:type_name -> geocube.Instance
	2,  // 4: geocube.CreateVariableRequest.variable:type_name -> geocube.Variable
	24, // 5: geocube.InstantiateVariableRequest.instance_metadata:type_name -> geocube.InstantiateVariableRequest.InstanceMetadataEntry
	1,  // 6: geocube.InstantiateVariableResponse.instance:type_name -> geocube.Instance
	2,  // 7: geocube.GetVariableResponse.variable:type_name -> geocube.Variable
	2,  // 8: geocube.ListVariablesResponseItem.variable:type_name -> geocube.Variable
	27, // 9: geocube.UpdateVariableRequest.name:type_name -> google.protobuf.StringValue
	27, // 10: geocube.UpdateVariableRequest.unit:type_name -> google.protobuf.StringValue
	27, // 11: geocube.UpdateVariableRequest.description:type_name -> google.protobuf.StringValue
	27, // 12: geocube.UpdateVariableRequest.palette:type_name -> google.protobuf.StringValue
	0,  // 13: geocube.UpdateVariableRequest.resampling_alg:type_name -> geocube.Resampling
	27, // 14: geocube.UpdateInstanceRequest.name:type_name -> google.protobuf.StringValue
	25, // 15: geocube.UpdateInstanceRequest.add_metadata:type_name -> geocube.UpdateInstanceRequest.AddMetadataEntry
	19, // 16: geocube.Palette.colors:type_name -> geocube.colorPoint
	20, // 17: geocube.CreatePaletteRequest.palette:type_name -> geocube.Palette
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pb_variables_proto_init() }
func file_pb_variables_proto_init() {
	if File_pb_variables_proto != nil {
		return
	}
	file_pb_dataformat_proto_init()
	file_pb_variables_proto_msgTypes[6].OneofWrappers = []any{
		(*GetVariableRequest_Id)(nil),
		(*GetVariableRequest_Name)(nil),
		(*GetVariableRequest_InstanceId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_variables_proto_rawDesc), len(file_pb_variables_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_variables_proto_goTypes,
		DependencyIndexes: file_pb_variables_proto_depIdxs,
		EnumInfos:         file_pb_variables_proto_enumTypes,
		MessageInfos:      file_pb_variables_proto_msgTypes,
	}.Build()
	File_pb_variables_proto = out.File
	file_pb_variables_proto_goTypes = nil
	file_pb_variables_proto_depIdxs = nil
}
