apiVersion: v1
kind: Deployment
metadata:
  name: consolidater-autoscaler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consolidater-autoscaler
  template:
    metadata:
      labels:
        app: consolidater-autoscaler
    spec:
      containers:
        - name: autoscaler
          image: $(CONTAINER_REGISTRY)/autoscaler:d4d8d196
          imagePullPolicy: Always
          args:
            - -update=30s
            - -subscription=consolidations
            - -rc=consolidater
            - -ns=default
            - -ratio=1
            - -minratio=1
            - -step=16
            - -max=256
            - -min=0
            - -pod.cost.path=/termination_cost
            - -pod.cost.port=9000
          resources:
            requests:
              cpu: 1m
              memory: 30Mi
