apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoscaler-role
rules:
  - verbs:
      - get
      - list
      - delete
      - create
    resources:
      - pods
  - verbs:
      - get
    resources:
      - replicationcontrollers