apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-autoscaled-pods
subjects:
  - kind: ServiceAccount
    name: autoscaler-service-account
    namespace: default
roleRef:
  kind: "Role"
  name: autoscaler-role
  apiGroup: "rbac.authorization.k8s.io"



